/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: hc_pre_linear_reduce_1
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void
hc_pre_linear_reduce_1(__gm__ float *v1, __gm__ float *v2, int64_t v3, int64_t v4, int64_t v5, int32_t v6, int32_t v7) {
    const int64_t v8 = 4;
    const int64_t v9 = 16;
    const int64_t v10 = 1;
    const int64_t v11 = 32;
    const int64_t v12 = 2048;
    const int64_t v13 = 0;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %linear_block_inline14293__ssa_v0, %1
    int64_t v14 = (int64_t)((uint64_t)((int64_t)v6) * (uint64_t)v9);
    // pto: %mixes_total_inline14262__tile
    Tile<
        TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v15 = Tile<
            TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v9, v11);
    // pto: %mixes_total_inline14262__tile
    uint64_t v16 = (uint64_t)v13;
    TASSIGN(v15, v16);
    // pto: %2
    int64_t v17 = v14 < v13 ? v13 : v14;
    // pto: %mixes_partials_inline14253__ssa_v1_pview
    pto::Shape<1, 1, 1, 16, 32> v18 = pto::Shape<1, 1, 1, 16, 32>();
    // pto: %mixes_partials_inline14253__ssa_v1_pview
    pto::Stride<512, 512, 512, 32, 1> v19 = pto::Stride<512, 512, 512, 32, 1>();
    // pto: %mixes_partials_inline14253__ssa_v1_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v20 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(
            v1 + (v13 + v17 * v11), v18, v19
        );
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    TLOAD(v15, v20);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    for (int64_t i21 = v10; i21 < v8; i21 += v10) {
        // pto: %3, %4
        int64_t v22 = (int64_t)((uint64_t)((int64_t)((uint64_t)i21 * (uint64_t)v5)) + (uint64_t)v14);
        // pto: %t__tile
        Tile<
            TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v23 = Tile<
                TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v9, v11);
        // pto: %t__tile
        uint64_t v24 = (uint64_t)v12;
        TASSIGN(v23, v24);
        // pto: %6
        pto::Shape<1, 1, 1, 16, 32> v25 = pto::Shape<1, 1, 1, 16, 32>();
        // pto: %6
        pto::Stride<512, 512, 512, 32, 1> v26 = pto::Stride<512, 512, 512, 32, 1>();
        // pto: %5, %6
        GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v27 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(
                v1 + (v13 + (v22 < v13 ? v13 : v22) * v11), v25, v26
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v23, v27);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %0
        Tile<
            TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v28 = Tile<
                TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v9, v11);
        // pto: %0
        uint64_t v29 = (uint64_t)v13;
        TASSIGN(v28, v29);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        TADD(v28, v15, v23);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    }
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    // pto: %mixes_raw_inline14254__ssa_v0_pview
    pto::Shape<1, 1, 1, 16, 32> v30 = pto::Shape<1, 1, 1, 16, 32>();
    // pto: %mixes_raw_inline14254__ssa_v0_pview
    pto::Stride<512, 512, 512, 32, 1> v31 = pto::Stride<512, 512, 512, 32, 1>();
    // pto: %mixes_raw_inline14254__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v32 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(
            v2 + (v13 + v17 * v11), v30, v31
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v32, v15);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: mixes_partials_inline14253__ssa_v1
    __gm__ ChipTensor *mixes_partials_inline14253__ssa_v1_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *mixes_partials_inline14253__ssa_v1 =
        reinterpret_cast<__gm__ float *>(mixes_partials_inline14253__ssa_v1_tensor->buffer.addr) +
        mixes_partials_inline14253__ssa_v1_tensor->start_offset;

    // Unpack tensor: mixes_raw_inline14254__ssa_v0
    __gm__ ChipTensor *mixes_raw_inline14254__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ float *mixes_raw_inline14254__ssa_v0 =
        reinterpret_cast<__gm__ float *>(mixes_raw_inline14254__ssa_v0_tensor->buffer.addr) +
        mixes_raw_inline14254__ssa_v0_tensor->start_offset;

    // Unpack scalar: t_linear_inline14281__ssa_v0
    union {
        uint64_t u64;
        int64_t val;
    } t_linear_inline14281__ssa_v0_conv;
    t_linear_inline14281__ssa_v0_conv.u64 = args[2];
    int64_t t_linear_inline14281__ssa_v0 = t_linear_inline14281__ssa_v0_conv.val;

    // Extract dynamic dim: linear_partial_rows_inline14229__ssa_v0
    int64_t linear_partial_rows_inline14229__ssa_v0 =
        static_cast<int64_t>(mixes_partials_inline14253__ssa_v1_tensor->shapes[0]);

    // Extract dynamic dim: t_linear_inline14281__ssa_v0_1
    int64_t t_linear_inline14281__ssa_v0_1 = static_cast<int64_t>(mixes_raw_inline14254__ssa_v0_tensor->shapes[0]);

    // Forward to ptoas-generated function
    hc_pre_linear_reduce_1(
        mixes_partials_inline14253__ssa_v1, mixes_raw_inline14254__ssa_v0, t_linear_inline14281__ssa_v0,
        linear_partial_rows_inline14229__ssa_v0, t_linear_inline14281__ssa_v0_1, __pypto_spmd_block_idx,
        __pypto_spmd_block_num
    );
}
