/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: hc_post_8
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void hc_post_8(
    __gm__ float *v1, __gm__ float *v2, __gm__ bfloat16_t *v3, __gm__ float *v4, __gm__ float *v5, int64_t v6,
    int64_t v7, int32_t v8, int32_t v9
) {
    const int64_t v10 = 12288;
    const int64_t v11 = 8192;
    SaturationMode v12 = SaturationMode::OFF;
    RoundMode v13 = RoundMode::CAST_ROUND;
    const int64_t v14 = 12;
    const int64_t v15 = 2;
    const int64_t v16 = 16;
    const int64_t v17 = 4096;
    const int64_t v18 = 8;
    const int64_t v19 = 4;
    const int64_t v20 = 1;
    const int64_t v21 = 114688;
    const int64_t v22 = 98304;
    const int64_t v23 = 81920;
    const int64_t v24 = 49152;
    const int64_t v25 = 32768;
    const int64_t v26 = 16384;
    const int64_t v27 = 0;
    const int64_t v28 = 131072;
    const int64_t v29 = 65536;
    const int64_t v30 = 147456;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %block_inline2839_inline12857__ssa_v0
    int64_t v31 = (int64_t)v8;
    // pto: %41
    int64_t v32 = v31 % v19;
    // pto: %40, %42
    int64_t v33 = (int64_t)((uint64_t)(v31 / v19) * (uint64_t)v19);
    // pto: %43
    int64_t v34 = (int64_t)((uint64_t)v33 + (uint64_t)v19);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
    for (int64_t i35 = v33; i35 < v34; i35 += v15) {
        // pto: %flat_offset_mul, %flat_offset, %post_w_inline2844_inline12853__tile
        float v36 = (v2)[(int64_t)((uint64_t)((int64_t)((uint64_t)i35 * (uint64_t)v19)) + (uint64_t)v32)];
        // pto: %45
        int64_t v37 = (int64_t)((uint64_t)i35 + (uint64_t)v20);
        // pto: %46, %47, %44
        float v38 = (v2)[(int64_t)((uint64_t)((int64_t)((uint64_t)v37 * (uint64_t)v19)) + (uint64_t)v32)];
        // pto: %t__tile
        Tile<
            TileType::Vec, bfloat16_t, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v39 = Tile<
                TileType::Vec, bfloat16_t, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %t__tile
        uint64_t v40 = (uint64_t)v30;
        TASSIGN(v39, v40);
        // pto: %48
        int64_t v41 = i35 < v27 ? v27 : i35;
        // pto: %ffn_out_inline12872__phi_v3_pview
        pto::Shape<1, 1, 1, 1, 4096> v42 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %ffn_out_inline12872__phi_v3_pview
        pto::Stride<4096, 4096, 4096, 4096, 1> v43 = pto::Stride<4096, 4096, 4096, 4096, 1>();
        // pto: %ffn_out_inline12872__phi_v3_pview
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>
            v44 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(
                v3 + (v27 + v41 * v17), v42, v43
            );
        TLOAD(v39, v44);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %0
        Tile<
            TileType::Vec, bfloat16_t, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v45 = Tile<
                TileType::Vec, bfloat16_t, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %0
        uint64_t v46 = (uint64_t)v29;
        TASSIGN(v45, v46);
        // pto: %50
        int64_t v47 = v37 < v27 ? v27 : v37;
        // pto: %51
        pto::Shape<1, 1, 1, 1, 4096> v48 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %51
        pto::Stride<4096, 4096, 4096, 4096, 1> v49 = pto::Stride<4096, 4096, 4096, 4096, 1>();
        // pto: %51
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>
            v50 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(
                v3 + (v27 + v47 * v17), v48, v49
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v45, v50);
        // pto: %x_row_inline2846_inline12879__tile
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v51 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %x_row_inline2846_inline12879__tile
        uint64_t v52 = (uint64_t)v28;
        TASSIGN(v51, v52);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
        TCVT(v51, v39, v13, v12);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        // pto: %y_row_inline2843_inline12852__tile
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v53 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %y_row_inline2843_inline12852__tile
        uint64_t v54 = (uint64_t)v28;
        TASSIGN(v53, v54);
        pipe_barrier(PIPE_V);
        TMULS(v53, v51, v36);
        // pto: %52
        int64_t v55 = (int64_t)((uint64_t)i35 * (uint64_t)v16);
        // pto: %53, %comb_w_inline2840_inline13020__tile
        float v56 = (v4)[(int64_t)((uint64_t)v55 + (uint64_t)v32)];
        // pto: %55
        int64_t v57 = (int64_t)((uint64_t)v32 + (uint64_t)v19);
        // pto: %57, %54
        float v58 = (v4)[(int64_t)((uint64_t)v55 + (uint64_t)v57)];
        // pto: %59
        int64_t v59 = (int64_t)((uint64_t)v32 + (uint64_t)v18);
        // pto: %61, %58
        float v60 = (v4)[(int64_t)((uint64_t)v55 + (uint64_t)v59)];
        // pto: %63
        int64_t v61 = (int64_t)((uint64_t)v32 + (uint64_t)v14);
        // pto: %65, %62
        float v62 = (v4)[(int64_t)((uint64_t)v55 + (uint64_t)v61)];
        // pto: %res_row_inline2833_inline12851__tile
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v63 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %res_row_inline2833_inline12851__tile
        uint64_t v64 = (uint64_t)v30;
        TASSIGN(v63, v64);
        // pto: %residual_flat_inline2836_inline12859__ssa_v0_pview
        pto::Shape<1, 1, 1, 1, 4096> v65 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %residual_flat_inline2836_inline12859__ssa_v0_pview
        pto::Stride<16384, 16384, 16384, 16384, 1> v66 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %residual_flat_inline2836_inline12859__ssa_v0_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v67 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v27 + v41 * v26), v65, v66
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        TLOAD(v63, v67);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        // pto: %1
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v68 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %1
        uint64_t v69 = (uint64_t)v27;
        TASSIGN(v68, v69);
        // pto: %70
        pto::Shape<1, 1, 1, 1, 4096> v70 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %70
        pto::Stride<16384, 16384, 16384, 16384, 1> v71 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %70
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v72 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v17 + v41 * v26), v70, v71
            );
        TLOAD(v68, v72);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        // pto: %2
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v73 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %2
        uint64_t v74 = (uint64_t)v26;
        TASSIGN(v73, v74);
        // pto: %73
        pto::Shape<1, 1, 1, 1, 4096> v75 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %73
        pto::Stride<16384, 16384, 16384, 16384, 1> v76 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %73
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v77 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v11 + v41 * v26), v75, v76
            );
        TLOAD(v73, v77);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        // pto: %3
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v78 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %3
        uint64_t v79 = (uint64_t)v25;
        TASSIGN(v78, v79);
        // pto: %76
        pto::Shape<1, 1, 1, 1, 4096> v80 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %76
        pto::Stride<16384, 16384, 16384, 16384, 1> v81 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %76
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v82 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v10 + v41 * v26), v80, v81
            );
        TLOAD(v78, v82);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
        // pto: %weighted_inline2832_inline12850__tile
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v83 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %weighted_inline2832_inline12850__tile
        uint64_t v84 = (uint64_t)v30;
        TASSIGN(v83, v84);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        TMULS(v83, v63, v56);
        // pto: %4
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v85 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %4
        uint64_t v86 = (uint64_t)v30;
        TASSIGN(v85, v86);
        pipe_barrier(PIPE_V);
        TADD(v85, v53, v83);
        // pto: %5
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v87 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %5
        uint64_t v88 = (uint64_t)v27;
        TASSIGN(v87, v88);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        TMULS(v87, v68, v58);
        // pto: %6
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v89 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %6
        uint64_t v90 = (uint64_t)v27;
        TASSIGN(v89, v90);
        pipe_barrier(PIPE_V);
        TADD(v89, v85, v87);
        // pto: %7
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v91 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %7
        uint64_t v92 = (uint64_t)v26;
        TASSIGN(v91, v92);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        TMULS(v91, v73, v60);
        // pto: %8
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v93 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %8
        uint64_t v94 = (uint64_t)v26;
        TASSIGN(v93, v94);
        pipe_barrier(PIPE_V);
        TADD(v93, v89, v91);
        // pto: %9
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v95 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %9
        uint64_t v96 = (uint64_t)v25;
        TASSIGN(v95, v96);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
        TMULS(v95, v78, v62);
        // pto: %10
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v97 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %10
        uint64_t v98 = (uint64_t)v28;
        TASSIGN(v97, v98);
        pipe_barrier(PIPE_V);
        TADD(v97, v93, v95);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        // pto: %78
        int64_t v99 = (int64_t)((uint64_t)v32 * (uint64_t)v17);
        // pto: %79
        int64_t v100 = v99 < v27 ? v27 : v99;
        // pto: %y_flat_inline2837_inline12858__iter_v1_pview
        pto::Shape<1, 1, 1, 1, 4096> v101 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %y_flat_inline2837_inline12858__iter_v1_pview
        pto::Stride<16384, 16384, 16384, 16384, 1> v102 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %y_flat_inline2837_inline12858__iter_v1_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v103 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v1 + ((v27 + v41 * v26) + v100), v101, v102
            );
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        pipe_barrier(PIPE_MTE3);
        TSTORE(v103, v97);
        set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
        // pto: %11
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v104 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %11
        uint64_t v105 = (uint64_t)v24;
        TASSIGN(v104, v105);
        wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
        TCVT(v104, v45, v13, v12);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
        // pto: %12
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v106 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %12
        uint64_t v107 = (uint64_t)v24;
        TASSIGN(v106, v107);
        pipe_barrier(PIPE_V);
        TMULS(v106, v104, v38);
        // pto: %82
        int64_t v108 = (int64_t)((uint64_t)v37 * (uint64_t)v16);
        // pto: %83, %80
        float v109 = (v4)[(int64_t)((uint64_t)v108 + (uint64_t)v32)];
        // pto: %88, %84
        float v110 = (v4)[(int64_t)((uint64_t)v108 + (uint64_t)v57)];
        // pto: %93, %89
        float v111 = (v4)[(int64_t)((uint64_t)v108 + (uint64_t)v59)];
        // pto: %98, %94
        float v112 = (v4)[(int64_t)((uint64_t)v108 + (uint64_t)v61)];
        // pto: %13
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v113 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %13
        uint64_t v114 = (uint64_t)v29;
        TASSIGN(v113, v114);
        // pto: %102
        pto::Shape<1, 1, 1, 1, 4096> v115 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %102
        pto::Stride<16384, 16384, 16384, 16384, 1> v116 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %102
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v117 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v27 + v47 * v26), v115, v116
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
        TLOAD(v113, v117);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID5);
        // pto: %14
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v118 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %14
        uint64_t v119 = (uint64_t)v23;
        TASSIGN(v118, v119);
        // pto: %106
        pto::Shape<1, 1, 1, 1, 4096> v120 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %106
        pto::Stride<16384, 16384, 16384, 16384, 1> v121 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %106
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v122 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v17 + v47 * v26), v120, v121
            );
        TLOAD(v118, v122);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID6);
        // pto: %15
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v123 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %15
        uint64_t v124 = (uint64_t)v22;
        TASSIGN(v123, v124);
        // pto: %110
        pto::Shape<1, 1, 1, 1, 4096> v125 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %110
        pto::Stride<16384, 16384, 16384, 16384, 1> v126 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %110
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v127 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v11 + v47 * v26), v125, v126
            );
        TLOAD(v123, v127);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID7);
        // pto: %16
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v128 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %16
        uint64_t v129 = (uint64_t)v21;
        TASSIGN(v128, v129);
        // pto: %114
        pto::Shape<1, 1, 1, 1, 4096> v130 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %114
        pto::Stride<16384, 16384, 16384, 16384, 1> v131 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %114
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v132 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v10 + v47 * v26), v130, v131
            );
        TLOAD(v128, v132);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %17
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v133 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %17
        uint64_t v134 = (uint64_t)v29;
        TASSIGN(v133, v134);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID5);
        TMULS(v133, v113, v109);
        // pto: %18
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v135 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %18
        uint64_t v136 = (uint64_t)v29;
        TASSIGN(v135, v136);
        pipe_barrier(PIPE_V);
        TADD(v135, v106, v133);
        // pto: %19
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v137 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %19
        uint64_t v138 = (uint64_t)v23;
        TASSIGN(v137, v138);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID6);
        TMULS(v137, v118, v110);
        // pto: %20
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v139 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %20
        uint64_t v140 = (uint64_t)v23;
        TASSIGN(v139, v140);
        pipe_barrier(PIPE_V);
        TADD(v139, v135, v137);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        // pto: %21
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v141 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %21
        uint64_t v142 = (uint64_t)v22;
        TASSIGN(v141, v142);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID7);
        TMULS(v141, v123, v111);
        // pto: %22
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v143 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %22
        uint64_t v144 = (uint64_t)v22;
        TASSIGN(v143, v144);
        pipe_barrier(PIPE_V);
        TADD(v143, v139, v141);
        // pto: %23
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v145 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %23
        uint64_t v146 = (uint64_t)v21;
        TASSIGN(v145, v146);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        TMULS(v145, v128, v112);
        // pto: %24
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v147 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %24
        uint64_t v148 = (uint64_t)v24;
        TASSIGN(v147, v148);
        pipe_barrier(PIPE_V);
        TADD(v147, v143, v145);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        // pto: %y_flat_inline2837_inline12858__tile_pview
        pto::Shape<1, 1, 1, 1, 4096> v149 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %y_flat_inline2837_inline12858__tile_pview
        pto::Stride<16384, 16384, 16384, 16384, 1> v150 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %y_flat_inline2837_inline12858__tile_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v151 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v1 + ((v27 + v47 * v26) + v100), v149, v150
            );
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        pipe_barrier(PIPE_MTE3);
        TSTORE(v151, v147);
        set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
    }
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
    // pto: %120, %121, %122
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
    if ((int64_t)((uint64_t)((int64_t)((uint64_t)v33 - (uint64_t)v34)) + (uint64_t)v19) == v20) {
        // pto: %124, %125, %123
        float v152 = (v2)[(int64_t)((uint64_t)((int64_t)((uint64_t)v34 * (uint64_t)v19)) + (uint64_t)v32)];
        // pto: %25
        Tile<
            TileType::Vec, bfloat16_t, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v153 = Tile<
                TileType::Vec, bfloat16_t, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %25
        uint64_t v154 = (uint64_t)v30;
        TASSIGN(v153, v154);
        // pto: %126
        int64_t v155 = v34 < v27 ? v27 : v34;
        // pto: %127
        pto::Shape<1, 1, 1, 1, 4096> v156 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %127
        pto::Stride<4096, 4096, 4096, 4096, 1> v157 = pto::Stride<4096, 4096, 4096, 4096, 1>();
        // pto: %127
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>
            v158 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(
                v3 + (v27 + v155 * v17), v156, v157
            );
        TLOAD(v153, v158);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %26
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v159 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %26
        uint64_t v160 = (uint64_t)v28;
        TASSIGN(v159, v160);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        TCVT(v159, v153, v13, v12);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
        // pto: %27
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v161 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %27
        uint64_t v162 = (uint64_t)v28;
        TASSIGN(v161, v162);
        pipe_barrier(PIPE_V);
        TMULS(v161, v159, v152);
        // pto: %129
        int64_t v163 = (int64_t)((uint64_t)v34 * (uint64_t)v16);
        // pto: %130, %128
        float v164 = (v4)[(int64_t)((uint64_t)v163 + (uint64_t)v32)];
        // pto: %134, %132, %131
        float v165 = (v4)[(int64_t)((uint64_t)v163 + (uint64_t)((int64_t)((uint64_t)v32 + (uint64_t)v19)))];
        // pto: %138, %136, %135
        float v166 = (v4)[(int64_t)((uint64_t)v163 + (uint64_t)((int64_t)((uint64_t)v32 + (uint64_t)v18)))];
        // pto: %142, %140, %139
        float v167 = (v4)[(int64_t)((uint64_t)v163 + (uint64_t)((int64_t)((uint64_t)v32 + (uint64_t)v14)))];
        // pto: %28
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v168 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %28
        uint64_t v169 = (uint64_t)v30;
        TASSIGN(v168, v169);
        // pto: %145
        pto::Shape<1, 1, 1, 1, 4096> v170 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %145
        pto::Stride<16384, 16384, 16384, 16384, 1> v171 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %145
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v172 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v27 + v155 * v26), v170, v171
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
        TLOAD(v168, v172);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %29
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v173 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %29
        uint64_t v174 = (uint64_t)v27;
        TASSIGN(v173, v174);
        // pto: %148
        pto::Shape<1, 1, 1, 1, 4096> v175 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %148
        pto::Stride<16384, 16384, 16384, 16384, 1> v176 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %148
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v177 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v17 + v155 * v26), v175, v176
            );
        TLOAD(v173, v177);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        // pto: %30
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v178 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %30
        uint64_t v179 = (uint64_t)v26;
        TASSIGN(v178, v179);
        // pto: %151
        pto::Shape<1, 1, 1, 1, 4096> v180 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %151
        pto::Stride<16384, 16384, 16384, 16384, 1> v181 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %151
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v182 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v11 + v155 * v26), v180, v181
            );
        TLOAD(v178, v182);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        // pto: %31
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v183 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %31
        uint64_t v184 = (uint64_t)v25;
        TASSIGN(v183, v184);
        // pto: %154
        pto::Shape<1, 1, 1, 1, 4096> v185 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %154
        pto::Stride<16384, 16384, 16384, 16384, 1> v186 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %154
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v187 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v5 + (v10 + v155 * v26), v185, v186
            );
        TLOAD(v183, v187);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        // pto: %32
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v188 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %32
        uint64_t v189 = (uint64_t)v30;
        TASSIGN(v188, v189);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        TMULS(v188, v168, v164);
        // pto: %33
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v190 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %33
        uint64_t v191 = (uint64_t)v30;
        TASSIGN(v190, v191);
        pipe_barrier(PIPE_V);
        TADD(v190, v161, v188);
        // pto: %34
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v192 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %34
        uint64_t v193 = (uint64_t)v27;
        TASSIGN(v192, v193);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        TMULS(v192, v173, v165);
        // pto: %35
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v194 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %35
        uint64_t v195 = (uint64_t)v27;
        TASSIGN(v194, v195);
        pipe_barrier(PIPE_V);
        TADD(v194, v190, v192);
        // pto: %36
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v196 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %36
        uint64_t v197 = (uint64_t)v26;
        TASSIGN(v196, v197);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        TMULS(v196, v178, v166);
        // pto: %37
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v198 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %37
        uint64_t v199 = (uint64_t)v26;
        TASSIGN(v198, v199);
        pipe_barrier(PIPE_V);
        TADD(v198, v194, v196);
        // pto: %38
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v200 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %38
        uint64_t v201 = (uint64_t)v25;
        TASSIGN(v200, v201);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        TMULS(v200, v183, v167);
        // pto: %39
        Tile<
            TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v202 = Tile<
                TileType::Vec, float, 1, 4096, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v20, v17);
        // pto: %39
        uint64_t v203 = (uint64_t)v28;
        TASSIGN(v202, v203);
        pipe_barrier(PIPE_V);
        TADD(v202, v198, v200);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
        // pto: %157
        int64_t v204 = (int64_t)((uint64_t)v32 * (uint64_t)v17);
        // pto: %y_flat_inline2837_inline12858__rv_v2_main_pview
        pto::Shape<1, 1, 1, 1, 4096> v205 = pto::Shape<1, 1, 1, 1, 4096>();
        // pto: %y_flat_inline2837_inline12858__rv_v2_main_pview
        pto::Stride<16384, 16384, 16384, 16384, 1> v206 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        // pto: %y_flat_inline2837_inline12858__rv_v2_main_pview, %158
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>
            v207 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 1, 4096>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(
                v1 + ((v27 + v155 * v26) + (v204 < v27 ? v27 : v204)), v205, v206
            );
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
        pipe_barrier(PIPE_MTE3);
        TSTORE(v207, v202);
    }
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: y_flat_inline2837_inline12858__ssa_v0
    __gm__ ChipTensor *y_flat_inline2837_inline12858__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *y_flat_inline2837_inline12858__ssa_v0 =
        reinterpret_cast<__gm__ float *>(y_flat_inline2837_inline12858__ssa_v0_tensor->buffer.addr) +
        y_flat_inline2837_inline12858__ssa_v0_tensor->start_offset;

    // Unpack tensor: post_ffn_inline12972__ssa_v1
    __gm__ ChipTensor *post_ffn_inline12972__ssa_v1_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ float *post_ffn_inline12972__ssa_v1 =
        reinterpret_cast<__gm__ float *>(post_ffn_inline12972__ssa_v1_tensor->buffer.addr) +
        post_ffn_inline12972__ssa_v1_tensor->start_offset;

    // Unpack tensor: ffn_out_inline12872__phi_v3
    __gm__ ChipTensor *ffn_out_inline12872__phi_v3_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ bfloat16_t *ffn_out_inline12872__phi_v3 =
        reinterpret_cast<__gm__ bfloat16_t *>(ffn_out_inline12872__phi_v3_tensor->buffer.addr) +
        ffn_out_inline12872__phi_v3_tensor->start_offset;

    // Unpack tensor: comb_ffn_inline13000__ssa_v0
    __gm__ ChipTensor *comb_ffn_inline13000__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ float *comb_ffn_inline13000__ssa_v0 =
        reinterpret_cast<__gm__ float *>(comb_ffn_inline13000__ssa_v0_tensor->buffer.addr) +
        comb_ffn_inline13000__ssa_v0_tensor->start_offset;

    // Unpack tensor: residual_flat_inline2836_inline12859__ssa_v0
    __gm__ ChipTensor *residual_flat_inline2836_inline12859__ssa_v0_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[4]);
    __gm__ float *residual_flat_inline2836_inline12859__ssa_v0 =
        reinterpret_cast<__gm__ float *>(residual_flat_inline2836_inline12859__ssa_v0_tensor->buffer.addr) +
        residual_flat_inline2836_inline12859__ssa_v0_tensor->start_offset;

    // Extract dynamic dim: t_dim_inline2845_inline12860__ssa_v0
    int64_t t_dim_inline2845_inline12860__ssa_v0 =
        static_cast<int64_t>(y_flat_inline2837_inline12858__ssa_v0_tensor->shapes[0]);

    // Extract dynamic dim: T_DYN
    int64_t T_DYN = static_cast<int64_t>(post_ffn_inline12972__ssa_v1_tensor->shapes[0]);

    // Forward to ptoas-generated function
    hc_post_8(
        y_flat_inline2837_inline12858__ssa_v0, post_ffn_inline12972__ssa_v1, ffn_out_inline12872__phi_v3,
        comb_ffn_inline13000__ssa_v0, residual_flat_inline2836_inline12859__ssa_v0,
        t_dim_inline2845_inline12860__ssa_v0, T_DYN, __pypto_spmd_block_idx, __pypto_spmd_block_num
    );
}
