/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: idx_qr_proj_dequant_0
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void idx_qr_proj_dequant_0(
    __gm__ float *v1, __gm__ int32_t *v2, __gm__ float *v3, __gm__ float *v4, int32_t v5, int32_t v6
) {
    SaturationMode v7 = SaturationMode::OFF;
    RoundMode v8 = RoundMode::CAST_NONE;
    const int64_t v9 = 1024;
    const int64_t v10 = 8;
    const int64_t v11 = 1;
    const int64_t v12 = 36864;
    const int64_t v13 = 4096;
    const int64_t v14 = 0;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %ot_inline2028_inline12517__ssa_v0, %3
    int64_t v15 = (int64_t)((uint64_t)((int64_t)v5) * (uint64_t)v9);
    // pto: %t__tile
    Tile<
        TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v16 = Tile<
            TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v11, v9);
    // pto: %t__tile
    uint64_t v17 = (uint64_t)v14;
    TASSIGN(v16, v17);
    // pto: %4
    int64_t v18 = v15 < v14 ? v14 : v15;
    // pto: %csa_idx_wq_b_scale_last_inline518__ssa_v0_pview
    pto::Shape<1, 1, 1, 1, 1024> v19 = pto::Shape<1, 1, 1, 1, 1024>();
    // pto: %csa_idx_wq_b_scale_last_inline518__ssa_v0_pview
    pto::Stride<1024, 1024, 1024, 1024, 1> v20 = pto::Stride<1024, 1024, 1024, 1024, 1>();
    // pto: %csa_idx_wq_b_scale_last_inline518__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 1024>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND> v21 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 1024>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND>(
            v1 + (v14 + v18), v19, v20
        );
    TLOAD(v16, v21);
    // pto: %wq_scale_inline1989_inline12267__tile
    Tile<
        TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v22 = Tile<
            TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v11, v9);
    // pto: %wq_scale_inline1989_inline12267__tile
    uint64_t v23 = (uint64_t)v14;
    TASSIGN(v22, v23);
    // pto: %0
    Tile<
        TileType::Vec, int32_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v24 = Tile<
            TileType::Vec, int32_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v10, v9);
    // pto: %0
    uint64_t v25 = (uint64_t)v13;
    TASSIGN(v24, v25);
    // pto: %qr_acc_pad_inline2023_inline12697__rv_v2_pview
    pto::Shape<1, 1, 1, 8, 1024> v26 = pto::Shape<1, 1, 1, 8, 1024>();
    // pto: %qr_acc_pad_inline2023_inline12697__rv_v2_pview
    pto::Stride<65536, 65536, 65536, 8192, 1> v27 = pto::Stride<65536, 65536, 65536, 8192, 1>();
    // pto: %qr_acc_pad_inline2023_inline12697__rv_v2_pview
    GlobalTensor<int32_t, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND>
        v28 = GlobalTensor<
            int32_t, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND>(
            v2 + (v14 + v18), v26, v27
        );
    TLOAD(v24, v28);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    // pto: %acc_fp32_inline2000_inline12698__tile
    Tile<
        TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v29 = Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v10, v9);
    // pto: %acc_fp32_inline2000_inline12698__tile
    uint64_t v30 = (uint64_t)v13;
    TASSIGN(v29, v30);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TCVT(v29, v24, v8, v7);
    // pto: %1
    Tile<
        TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v31 = Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v10, v11);
    // pto: %1
    uint64_t v32 = (uint64_t)v12;
    TASSIGN(v31, v32);
    // pto: %qr_scale_inline12682__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 1> v33 = pto::Shape<1, 1, 1, 8, 1>();
    // pto: %qr_scale_inline12682__ssa_v0_pview
    pto::Stride<8, 8, 8, 1, 8> v34 = pto::Stride<8, 8, 8, 1, 8>();
    // pto: %qr_scale_inline12682__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1>, pto::Stride<8, 8, 8, 1, 8>, pto::Layout::DN> v35 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1>, pto::Stride<8, 8, 8, 1, 8>, pto::Layout::DN>(v3, v33, v34);
    TLOAD(v31, v35);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    // pto: %2
    Tile<
        TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v36 = Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v10, v9);
    // pto: %2
    uint64_t v37 = (uint64_t)v13;
    TASSIGN(v36, v37);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    pipe_barrier(PIPE_V);
    TROWEXPANDMUL(v36, v29, v31);
    // pto: %qr_dequant_inline1962_inline12699__tile
    Tile<
        TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v38 = Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v10, v9);
    // pto: %qr_dequant_inline1962_inline12699__tile
    uint64_t v39 = (uint64_t)v13;
    TASSIGN(v38, v39);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v38, v36, v22);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    // pto: %qr_proj_inline2001_inline12361__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 1024> v40 = pto::Shape<1, 1, 1, 8, 1024>();
    // pto: %qr_proj_inline2001_inline12361__ssa_v0_pview
    pto::Stride<65536, 65536, 65536, 8192, 1> v41 = pto::Stride<65536, 65536, 65536, 8192, 1>();
    // pto: %qr_proj_inline2001_inline12361__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND> v42 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND>(
            v4 + (v14 + v18), v40, v41
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v42, v38);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: csa_idx_wq_b_scale_last_inline518__ssa_v0
    __gm__ ChipTensor *csa_idx_wq_b_scale_last_inline518__ssa_v0_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *csa_idx_wq_b_scale_last_inline518__ssa_v0 =
        reinterpret_cast<__gm__ float *>(csa_idx_wq_b_scale_last_inline518__ssa_v0_tensor->buffer.addr) +
        csa_idx_wq_b_scale_last_inline518__ssa_v0_tensor->start_offset;

    // Unpack tensor: qr_acc_pad_inline2023_inline12697__rv_v2
    __gm__ ChipTensor *qr_acc_pad_inline2023_inline12697__rv_v2_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ int32_t *qr_acc_pad_inline2023_inline12697__rv_v2 =
        reinterpret_cast<__gm__ int32_t *>(qr_acc_pad_inline2023_inline12697__rv_v2_tensor->buffer.addr) +
        qr_acc_pad_inline2023_inline12697__rv_v2_tensor->start_offset;

    // Unpack tensor: qr_scale_inline12682__ssa_v0
    __gm__ ChipTensor *qr_scale_inline12682__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ float *qr_scale_inline12682__ssa_v0 =
        reinterpret_cast<__gm__ float *>(qr_scale_inline12682__ssa_v0_tensor->buffer.addr) +
        qr_scale_inline12682__ssa_v0_tensor->start_offset;

    // Unpack tensor: qr_proj_inline2001_inline12361__ssa_v0
    __gm__ ChipTensor *qr_proj_inline2001_inline12361__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ float *qr_proj_inline2001_inline12361__ssa_v0 =
        reinterpret_cast<__gm__ float *>(qr_proj_inline2001_inline12361__ssa_v0_tensor->buffer.addr) +
        qr_proj_inline2001_inline12361__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    idx_qr_proj_dequant_0(
        csa_idx_wq_b_scale_last_inline518__ssa_v0, qr_acc_pad_inline2023_inline12697__rv_v2,
        qr_scale_inline12682__ssa_v0, qr_proj_inline2001_inline12361__ssa_v0, __pypto_spmd_block_idx,
        __pypto_spmd_block_num
    );
}
