/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: kv_and_cache_write_0
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void kv_and_cache_write_0(
    __gm__ float *v1, __gm__ int8_t *v2, __gm__ float *v3, __gm__ int32_t *v4, __gm__ int64_t *v5, __gm__ float *v6,
    int64_t v7
) {
    RoundMode v8 = RoundMode::CAST_TRUNC;
    RoundMode v9 = RoundMode::CAST_ROUND;
    SaturationMode v10 = SaturationMode::OFF;
    RoundMode v11 = RoundMode::CAST_RINT;
    const int64_t v12 = 3;
    const float v13 = 127.0f;
    const float v14 = 9.99999974E-5f;
    const int64_t v15 = 2;
    const int64_t v16 = 4;
    const int64_t v17 = 1;
    const int64_t v18 = 16;
    const int64_t v19 = 8192;
    const int64_t v20 = 0;
    const int64_t v21 = 16448;
    const int64_t v22 = 8256;
    const int64_t v23 = 128;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %t__tile
    Tile<
        TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v24 = Tile<
            TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v23);
    // pto: %t__tile
    uint64_t v25 = (uint64_t)v22;
    TASSIGN(v24, v25);
    // pto: %kv_final_inline15242__rv_v2_pview
    pto::Shape<1, 1, 1, 16, 128> v26 = pto::Shape<1, 1, 1, 16, 128>();
    // pto: %kv_final_inline15242__rv_v2_pview
    pto::Stride<2048, 2048, 2048, 128, 1> v27 = pto::Stride<2048, 2048, 2048, 128, 1>();
    // pto: %kv_final_inline15242__rv_v2_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND> v28 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND>(
            v1, v26, v27
        );
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v24, v28);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    // pto: %0
    Tile<
        TileType::Vec, bfloat16_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v29 = Tile<
            TileType::Vec, bfloat16_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v23);
    // pto: %0
    uint64_t v30 = (uint64_t)v21;
    TASSIGN(v29, v30);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TCVT(v29, v24, v11, v10);
    // pto: %kv_blk_f32_inline15319__tile
    Tile<
        TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v31 = Tile<
            TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v23);
    // pto: %kv_blk_f32_inline15319__tile
    uint64_t v32 = (uint64_t)v22;
    TASSIGN(v31, v32);
    pipe_barrier(PIPE_V);
    TCVT(v31, v29, v9, v10);
    // pto: %1
    Tile<
        TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v33 = Tile<
            TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v23);
    // pto: %1
    uint64_t v34 = (uint64_t)v21;
    TASSIGN(v33, v34);
    pipe_barrier(PIPE_V);
    TABS(v33, v31);
    // pto: %tmp_tile
    Tile<
        TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v35 = Tile<
            TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v23);
    // pto: %tmp_tile
    uint64_t v36 = (uint64_t)v20;
    TASSIGN(v35, v36);
    // pto: %2
    Tile<
        TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v37 = Tile<
            TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v17);
    // pto: %2
    uint64_t v38 = (uint64_t)v19;
    TASSIGN(v37, v38);
    pipe_barrier(PIPE_V);
    TROWMAX(v37, v33, v35);
    // pto: %kv_amax_inline15241__tile
    Tile<
        TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v39 = Tile<
            TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v18);
    // pto: %kv_amax_inline15241__tile
    uint64_t v40 = (uint64_t)v19;
    TASSIGN(v39, v40);
    // pto: %3
    Tile<
        TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v41 = Tile<
            TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v18);
    // pto: %3
    uint64_t v42 = (uint64_t)v21;
    TASSIGN(v41, v42);
    pipe_barrier(PIPE_V);
    TEXPANDS(v41, v14);
    // pto: %kv_amax_v1_inline15293__tile
    Tile<
        TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v43 = Tile<
            TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v18);
    // pto: %kv_amax_v1_inline15293__tile
    uint64_t v44 = (uint64_t)v21;
    TASSIGN(v43, v44);
    pipe_barrier(PIPE_V);
    TMAX(v43, v39, v41);
    // pto: %4
    Tile<
        TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v45 = Tile<
            TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v18);
    // pto: %4
    uint64_t v46 = (uint64_t)v20;
    TASSIGN(v45, v46);
    TEXPANDS(v45, v13);
    // pto: %kv_scale_q_row_inline15240__tile
    Tile<
        TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v47 = Tile<
            TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v18);
    // pto: %kv_scale_q_row_inline15240__tile
    uint64_t v48 = (uint64_t)v21;
    TASSIGN(v47, v48);
    pipe_barrier(PIPE_V);
    TDIV(v47, v45, v43);
    // pto: %5
    Tile<
        TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v49 = Tile<
            TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v18);
    // pto: %5
    uint64_t v50 = (uint64_t)v20;
    TASSIGN(v49, v50);
    pipe_barrier(PIPE_V);
    TRECIP(v49, v47);
    set_flag(PIPE_V, PIPE_S, EVENT_ID0);
    // pto: %kv_scale_dq_col_inline15239__tile
    Tile<
        TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v51 = Tile<
            TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v17);
    // pto: %kv_scale_dq_col_inline15239__tile
    uint64_t v52 = (uint64_t)v20;
    TASSIGN(v51, v52);
    // pto: %kv_scale_q_col_inline15347__tile
    Tile<
        TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v53 = Tile<
            TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v17);
    // pto: %kv_scale_q_col_inline15347__tile
    uint64_t v54 = (uint64_t)v21;
    TASSIGN(v53, v54);
    // pto: %kv_scaled_inline15318__tile
    Tile<
        TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v55 = Tile<
            TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v23);
    // pto: %kv_scaled_inline15318__tile
    uint64_t v56 = (uint64_t)v22;
    TASSIGN(v55, v56);
    TROWEXPANDMUL(v55, v31, v53);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    // pto: %kv_i32_inline15238__tile
    Tile<
        TileType::Vec, int32_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v57 = Tile<
            TileType::Vec, int32_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v23);
    // pto: %kv_i32_inline15238__tile
    uint64_t v58 = (uint64_t)v22;
    TASSIGN(v57, v58);
    pipe_barrier(PIPE_V);
    TCVT(v57, v55, v11, v10);
    // pto: %kv_half_inline15333__tile
    Tile<
        TileType::Vec, half, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v59 = Tile<
            TileType::Vec, half, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v23);
    // pto: %kv_half_inline15333__tile
    uint64_t v60 = (uint64_t)v22;
    TASSIGN(v59, v60);
    pipe_barrier(PIPE_V);
    TCVT(v59, v57, v9, v10);
    // pto: %kv_i8_blk_inline15346__tile
    Tile<
        TileType::Vec, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v61 = Tile<
            TileType::Vec, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v18, v23);
    // pto: %kv_i8_blk_inline15346__tile
    uint64_t v62 = (uint64_t)v22;
    TASSIGN(v61, v62);
    pipe_barrier(PIPE_V);
    TCVT(v61, v59, v8, v10);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_S, EVENT_ID0);
    for (int64_t i63 = v20; i63 < v16; i63 += v17) {
        // pto: %flat_offset_mul
        int64_t v64 = (int64_t)((uint64_t)i63 * (uint64_t)v15);
        // pto: %first_pos_b_inline15338__tile
        int32_t v65 = (v4)[v64];
        // pto: %7, %8
        int64_t v66 = (int64_t)v65 % v16;
        // pto: %9
        if (v66 >= v15) {
            // pto: %kv_row_fp32_inline15236__tile
            Tile<
                TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v67 = Tile<
                    TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v17, v23);
            // pto: %kv_row_fp32_inline15236__tile
            uint64_t v68 = (uint64_t)v21;
            TASSIGN(v67, v68);
            // pto: %12
            pto::Shape<1, 1, 1, 1, 128> v69 = pto::Shape<1, 1, 1, 1, 128>();
            // pto: %12
            pto::Stride<128, 128, 128, 128, 1> v70 = pto::Stride<128, 128, 128, 128, 1>();
            // pto: %11, %12
            GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v71 =
                GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(
                    v1 + (v20 + (i63 < v20 ? v20 : i63) * v23), v69, v70
                );
            wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
            TLOAD(v67, v71);
            set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
            // pto: %14, %10, %cache_row_i64_inline15345__tile
            int64_t v72 = (v5)[(int64_t)((uint64_t)v64 + (uint64_t)((int64_t)((uint64_t)v12 - (uint64_t)v66)))];
            // pto: %16
            wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
            if (v72 >= v20) {
                // pto: %kv_flat_inline15314__iter_v1_pview
                pto::Shape<1, 1, 1, 1, 128> v73 = pto::Shape<1, 1, 1, 1, 128>();
                // pto: %kv_flat_inline15314__iter_v1_pview
                pto::Stride<128, 128, 128, 128, 1> v74 = pto::Stride<128, 128, 128, 128, 1>();
                // pto: %19, %kv_flat_inline15314__iter_v1_pview
                GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>
                    v75 = GlobalTensor<
                        float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(
                        v3 + (v20 + (v64 < v20 ? v20 : v64) * v23), v73, v74
                    );
                TSTORE(v75, v67);
                // pto: %6
                Tile<
                    TileType::Vec, int8_t, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v76 = Tile<
                        TileType::Vec, int8_t, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                        CompactMode::Null>(v17, v23);
                // pto: %6
                uint64_t v77 = (uint64_t)v22;
                TASSIGN(v76, v77);
                // pto: %slice_view
                Tile<
                    TileType::Vec, int8_t, 1, 128, BLayout::RowMajor, 1, 128, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v78;
                // pto: %slice_view
                Tile<
                    TileType::Vec, int8_t, 1, 128, BLayout::RowMajor, 1, 128, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v79 = v78;
                // pto: %slice_view
                uint64_t v80 =
                    (uint64_t)((int64_t)((uint64_t)((int64_t)((uint64_t)i63 * (uint64_t)v23)) + (uint64_t)v22));
                TASSIGN(v79, v80);
                // pto: %idx_kv_cache_flat_inline15300__iter_v1_pview
                pto::Shape<1, 1, 1, 1, 128> v81 = pto::Shape<1, 1, 1, 1, 128>();
                // pto: %idx_kv_cache_flat_inline15300__iter_v1_pview
                pto::Stride<128, 128, 128, 128, 1> v82 = pto::Stride<128, 128, 128, 128, 1>();
                // pto: %20, %idx_kv_cache_flat_inline15300__iter_v1_pview
                GlobalTensor<int8_t, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>
                    v83 = GlobalTensor<
                        int8_t, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(
                        v2 + (v20 + (v72 < v20 ? v20 : v72) * v23), v81, v82
                    );
                pipe_barrier(PIPE_MTE3);
                TSTORE(v83, v79);
                // pto: %21
                float v84 = v51.GetValue(i63);
                (v6)[v72] = v84;
            }
            set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
        }
    }
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    pipe_barrier(PIPE_ALL);
    dcci((__gm__ void *)0, cache_line_t::ENTIRE_DATA_CACHE);
    dsb((mem_dsb_t)0);
#endif  // __DAV_VEC__

    pipe_barrier(PIPE_ALL);
    dcci((__gm__ void *)0, cache_line_t::ENTIRE_DATA_CACHE);
    dsb((mem_dsb_t)0);
    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Unpack tensor: kv_final_inline15242__rv_v2
    __gm__ ChipTensor *kv_final_inline15242__rv_v2_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *kv_final_inline15242__rv_v2 =
        reinterpret_cast<__gm__ float *>(kv_final_inline15242__rv_v2_tensor->buffer.addr) +
        kv_final_inline15242__rv_v2_tensor->start_offset;

    // Unpack tensor: idx_kv_cache_flat_inline15300__ssa_v0
    __gm__ ChipTensor *idx_kv_cache_flat_inline15300__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ int8_t *idx_kv_cache_flat_inline15300__ssa_v0 =
        reinterpret_cast<__gm__ int8_t *>(idx_kv_cache_flat_inline15300__ssa_v0_tensor->buffer.addr) +
        idx_kv_cache_flat_inline15300__ssa_v0_tensor->start_offset;

    // Unpack tensor: kv_flat_inline15314__ssa_v0
    __gm__ ChipTensor *kv_flat_inline15314__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ float *kv_flat_inline15314__ssa_v0 =
        reinterpret_cast<__gm__ float *>(kv_flat_inline15314__ssa_v0_tensor->buffer.addr) +
        kv_flat_inline15314__ssa_v0_tensor->start_offset;

    // Unpack tensor: position_ids_bsd_inline12252__ssa_v0
    __gm__ ChipTensor *position_ids_bsd_inline12252__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ int32_t *position_ids_bsd_inline12252__ssa_v0 =
        reinterpret_cast<__gm__ int32_t *>(position_ids_bsd_inline12252__ssa_v0_tensor->buffer.addr) +
        position_ids_bsd_inline12252__ssa_v0_tensor->start_offset;

    // Unpack tensor: idx_slot_mapping_bsd_inline12777__ssa_v0
    __gm__ ChipTensor *idx_slot_mapping_bsd_inline12777__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[4]);
    __gm__ int64_t *idx_slot_mapping_bsd_inline12777__ssa_v0 =
        reinterpret_cast<__gm__ int64_t *>(idx_slot_mapping_bsd_inline12777__ssa_v0_tensor->buffer.addr) +
        idx_slot_mapping_bsd_inline12777__ssa_v0_tensor->start_offset;

    // Unpack tensor: idx_kv_scale_flat_inline15317__ssa_v0
    __gm__ ChipTensor *idx_kv_scale_flat_inline15317__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[5]);
    __gm__ float *idx_kv_scale_flat_inline15317__ssa_v0 =
        reinterpret_cast<__gm__ float *>(idx_kv_scale_flat_inline15317__ssa_v0_tensor->buffer.addr) +
        idx_kv_scale_flat_inline15317__ssa_v0_tensor->start_offset;

    // Extract dynamic dim: idx_block_num_inline15303__ssa_v0
    int64_t idx_block_num_inline15303__ssa_v0 =
        (static_cast<int64_t>(idx_kv_cache_flat_inline15300__ssa_v0_tensor->shapes[0]) / 128);

    // Forward to ptoas-generated function
    kv_and_cache_write_0(
        kv_final_inline15242__rv_v2, idx_kv_cache_flat_inline15300__ssa_v0, kv_flat_inline15314__ssa_v0,
        position_ids_bsd_inline12252__ssa_v0, idx_slot_mapping_bsd_inline12777__ssa_v0,
        idx_kv_scale_flat_inline15317__ssa_v0, idx_block_num_inline15303__ssa_v0
    );
}
