/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: kv_rms_norm_rope
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void kv_rms_norm_rope(
    __gm__ float *v1, __gm__ bfloat16_t *v2, __gm__ bfloat16_t *v3, __gm__ float *v4, __gm__ float *v5,
    __gm__ int32_t *v6, int64_t v7, int64_t v8, int32_t v9, int32_t v10
) {
    const int64_t v11 = 448;
    unsigned v12 = 448;
    unsigned v13 = 384;
    const int64_t v14 = 384;
    RoundMode v15 = RoundMode::CAST_RINT;
    SaturationMode v16 = SaturationMode::OFF;
    RoundMode v17 = RoundMode::CAST_ROUND;
    const int64_t v18 = 512;
    const int64_t v19 = 6;
    const float v20 = 9.99999997E-7f;
    const float v21 = 0.001953125f;
    const int64_t v22 = 128;
    const int64_t v23 = 2;
    const float v24 = 0.0f;
    const int64_t v25 = 8;
    const int64_t v26 = 64;
    const int64_t v27 = 1;
    const int64_t v28 = 12352;
    const int64_t v29 = 12608;
    const int64_t v30 = 10272;
    const int64_t v31 = 4128;
    const int64_t v32 = 4096;
    const int64_t v33 = 12864;
    const int64_t v34 = 6176;
    const int64_t v35 = 0;
    const int64_t v36 = 10304;
    const int64_t v37 = 256;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %tg_idx_inline903_inline8829__ssa_v0, %34
    int64_t v38 = (int64_t)((uint64_t)((int64_t)v9) * (uint64_t)v25);
    // pto: %kv_sq_sum_inline781_inline8965__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v39 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v25);
    // pto: %kv_sq_sum_inline781_inline8965__tile
    uint64_t v40 = (uint64_t)v36;
    TASSIGN(v39, v40);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TEXPANDS(v39, v24);
    for (int64_t i41 = v35; i41 < v25; i41 += v23) {
        // pto: %35
        int64_t v42 = (int64_t)((uint64_t)i41 * (uint64_t)v26);
        // pto: %37
        int64_t v43 = (int64_t)((uint64_t)v42 + (uint64_t)v26);
        // pto: %kv_chunk_inline824_inline9058__tile
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v44 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %kv_chunk_inline824_inline9058__tile
        uint64_t v45 = (uint64_t)v35;
        TASSIGN(v44, v45);
        // pto: %38
        int64_t v46 = v38 < v35 ? v35 : v38;
        // pto: %kv_fp32_inline844_inline9035__ssa_v1_pview
        pto::Shape<1, 1, 1, 8, 64> v47 = pto::Shape<1, 1, 1, 8, 64>();
        // pto: %kv_fp32_inline844_inline9035__ssa_v1_pview
        pto::Stride<4096, 4096, 4096, 512, 1> v48 = pto::Stride<4096, 4096, 4096, 512, 1>();
        // pto: %kv_fp32_inline844_inline9035__ssa_v1_pview, %39
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND> v49 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
                v1 + ((v35 + v46 * v18) + (v42 < v35 ? v35 : v42)), v47, v48
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v44, v49);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %0
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v50 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %0
        uint64_t v51 = (uint64_t)v34;
        TASSIGN(v50, v51);
        // pto: %42
        pto::Shape<1, 1, 1, 8, 64> v52 = pto::Shape<1, 1, 1, 8, 64>();
        // pto: %42
        pto::Stride<4096, 4096, 4096, 512, 1> v53 = pto::Stride<4096, 4096, 4096, 512, 1>();
        // pto: %42, %41
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND> v54 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
                v1 + ((v35 + v46 * v18) + (v43 < v35 ? v35 : v43)), v52, v53
            );
        TLOAD(v50, v54);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        // pto: %t__tile
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v55 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %t__tile
        uint64_t v56 = (uint64_t)v33;
        TASSIGN(v55, v56);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        TMUL(v55, v44, v44);
        // pto: %tmp_tile
        Tile<
            TileType::Vec, float, 8, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v57 = Tile<
                TileType::Vec, float, 8, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v22);
        // pto: %tmp_tile
        uint64_t v58 = (uint64_t)v35;
        TASSIGN(v57, v58);
        // pto: %1
        Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v59 = Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v27);
        // pto: %1
        uint64_t v60 = (uint64_t)v32;
        TASSIGN(v59, v60);
        pipe_barrier(PIPE_V);
        TROWSUM(v59, v55, v57);
        // pto: %2
        Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v61 = Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v25);
        // pto: %2
        uint64_t v62 = (uint64_t)v32;
        TASSIGN(v61, v62);
        // pto: %3
        Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v63 = Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v25);
        // pto: %3
        uint64_t v64 = (uint64_t)v35;
        TASSIGN(v63, v64);
        pipe_barrier(PIPE_V);
        TADD(v63, v39, v61);
        // pto: %4
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v65 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %4
        uint64_t v66 = (uint64_t)v31;
        TASSIGN(v65, v66);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        TMUL(v65, v50, v50);
        // pto: %5
        Tile<
            TileType::Vec, float, 8, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v67 = Tile<
                TileType::Vec, float, 8, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v22);
        // pto: %5
        uint64_t v68 = (uint64_t)v34;
        TASSIGN(v67, v68);
        // pto: %6
        Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v69 = Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v27);
        // pto: %6
        uint64_t v70 = (uint64_t)v30;
        TASSIGN(v69, v70);
        pipe_barrier(PIPE_V);
        TROWSUM(v69, v65, v67);
        // pto: %7
        Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v71 = Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v25);
        // pto: %7
        uint64_t v72 = (uint64_t)v30;
        TASSIGN(v71, v72);
        // pto: %8
        Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v73 = Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v25);
        // pto: %8
        uint64_t v74 = (uint64_t)v36;
        TASSIGN(v73, v74);
        pipe_barrier(PIPE_V);
        TADD(v73, v63, v71);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    }
    // pto: %9
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v75 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v25);
    // pto: %9
    uint64_t v76 = (uint64_t)v35;
    TASSIGN(v75, v76);
    pipe_barrier(PIPE_V);
    TMULS(v75, v39, v21);
    // pto: %10
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v77 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v25);
    // pto: %10
    uint64_t v78 = (uint64_t)v35;
    TASSIGN(v77, v78);
    pipe_barrier(PIPE_V);
    TADDS(v77, v75, v20);
    // pto: %rsqrt_tmp
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v79 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v25);
    // pto: %rsqrt_tmp
    uint64_t v80 = (uint64_t)v34;
    TASSIGN(v79, v80);
    // pto: %kv_inv_rms_inline778_inline8806__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v81 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v25);
    // pto: %kv_inv_rms_inline778_inline8806__tile
    uint64_t v82 = (uint64_t)v29;
    TASSIGN(v81, v82);
    pipe_barrier(PIPE_V);
    TRSQRT(v81, v77, v79);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    // pto: %kv_inv_rms_t_inline894_inline9061__tile
    Tile<
        TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v83 = Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v27);
    // pto: %kv_inv_rms_t_inline894_inline9061__tile
    uint64_t v84 = (uint64_t)v29;
    TASSIGN(v83, v84);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    for (int64_t i85 = v35; i85 < v19; i85 += v23) {
        // pto: %43
        int64_t v86 = (int64_t)((uint64_t)i85 * (uint64_t)v26);
        // pto: %45
        int64_t v87 = (int64_t)((uint64_t)v86 + (uint64_t)v26);
        // pto: %11
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v88 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %11
        uint64_t v89 = (uint64_t)v35;
        TASSIGN(v88, v89);
        // pto: %46
        int64_t v90 = v38 < v35 ? v35 : v38;
        // pto: %47
        int64_t v91 = v86 < v35 ? v35 : v86;
        // pto: %48
        pto::Shape<1, 1, 1, 8, 64> v92 = pto::Shape<1, 1, 1, 8, 64>();
        // pto: %48
        pto::Stride<4096, 4096, 4096, 512, 1> v93 = pto::Stride<4096, 4096, 4096, 512, 1>();
        // pto: %48
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND> v94 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
                v1 + ((v35 + v90 * v18) + v91), v92, v93
            );
        wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
        TLOAD(v88, v94);
        // pto: %12
        Tile<
            TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v95 = Tile<
                TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %12
        uint64_t v96 = (uint64_t)v36;
        TASSIGN(v95, v96);
        // pto: %gamma_ckv_l0_inline646__ssa_v0_pview
        pto::Shape<1, 1, 1, 1, 64> v97 = pto::Shape<1, 1, 1, 1, 64>();
        // pto: %gamma_ckv_l0_inline646__ssa_v0_pview
        pto::Stride<64, 64, 64, 64, 1> v98 = pto::Stride<64, 64, 64, 64, 1>();
        // pto: %gamma_ckv_l0_inline646__ssa_v0_pview
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND> v99 =
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND>(
                v3 + (v35 + v91), v97, v98
            );
        TLOAD(v95, v99);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        // pto: %13
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v100 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %13
        uint64_t v101 = (uint64_t)v34;
        TASSIGN(v100, v101);
        // pto: %51
        int64_t v102 = v87 < v35 ? v35 : v87;
        // pto: %52
        pto::Shape<1, 1, 1, 8, 64> v103 = pto::Shape<1, 1, 1, 8, 64>();
        // pto: %52
        pto::Stride<4096, 4096, 4096, 512, 1> v104 = pto::Stride<4096, 4096, 4096, 512, 1>();
        // pto: %52
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND> v105 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
                v1 + ((v35 + v90 * v18) + v102), v103, v104
            );
        wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
        TLOAD(v100, v105);
        // pto: %14
        Tile<
            TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v106 = Tile<
                TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %14
        uint64_t v107 = (uint64_t)v28;
        TASSIGN(v106, v107);
        // pto: %54
        pto::Shape<1, 1, 1, 1, 64> v108 = pto::Shape<1, 1, 1, 1, 64>();
        // pto: %54
        pto::Stride<64, 64, 64, 64, 1> v109 = pto::Stride<64, 64, 64, 64, 1>();
        // pto: %54
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND> v110 =
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND>(
                v3 + (v35 + v102), v108, v109
            );
        TLOAD(v106, v110);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        // pto: %gamma_kv_cast_inline775_inline9043__tile
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v111 = Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %gamma_kv_cast_inline775_inline9043__tile
        uint64_t v112 = (uint64_t)v33;
        TASSIGN(v111, v112);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        TCVT(v111, v95, v17, v16);
        // pto: %gamma_kv_chunk_inline774_inline9063__tile
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v113 = Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %gamma_kv_chunk_inline774_inline9063__tile
        uint64_t v114 = (uint64_t)v33;
        TASSIGN(v113, v114);
        // pto: %15
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v115 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %15
        uint64_t v116 = (uint64_t)v35;
        TASSIGN(v115, v116);
        TROWEXPANDMUL(v115, v88, v83);
        // pto: %kv_normed_inline773_inline9066__tile
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v117 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %kv_normed_inline773_inline9066__tile
        uint64_t v118 = (uint64_t)v35;
        TASSIGN(v117, v118);
        pipe_barrier(PIPE_V);
        TCOLEXPANDMUL(v117, v115, v113);
        // pto: %16
        Tile<
            TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v119 = Tile<
                TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %16
        uint64_t v120 = (uint64_t)v35;
        TASSIGN(v119, v120);
        pipe_barrier(PIPE_V);
        TCVT(v119, v117, v15, v16);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        // pto: %kv_view_inline863_inline8978__iter_v1_pview
        pto::Shape<1, 1, 1, 8, 64> v121 = pto::Shape<1, 1, 1, 8, 64>();
        // pto: %kv_view_inline863_inline8978__iter_v1_pview
        pto::Stride<4096, 4096, 4096, 512, 1> v122 = pto::Stride<4096, 4096, 4096, 512, 1>();
        // pto: %kv_view_inline863_inline8978__iter_v1_pview
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>
            v123 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
                v2 + ((v35 + v90 * v18) + v91), v121, v122
            );
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        pipe_barrier(PIPE_MTE3);
        TSTORE(v123, v119);
        set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
        // pto: %17
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v124 = Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %17
        uint64_t v125 = (uint64_t)v31;
        TASSIGN(v124, v125);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        TCVT(v124, v106, v17, v16);
        // pto: %18
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v126 = Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %18
        uint64_t v127 = (uint64_t)v31;
        TASSIGN(v126, v127);
        // pto: %19
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v128 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %19
        uint64_t v129 = (uint64_t)v34;
        TASSIGN(v128, v129);
        TROWEXPANDMUL(v128, v100, v83);
        // pto: %20
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v130 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %20
        uint64_t v131 = (uint64_t)v34;
        TASSIGN(v130, v131);
        pipe_barrier(PIPE_V);
        TCOLEXPANDMUL(v130, v128, v126);
        // pto: %21
        Tile<
            TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v132 = Tile<
                TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v26);
        // pto: %21
        uint64_t v133 = (uint64_t)v34;
        TASSIGN(v132, v133);
        pipe_barrier(PIPE_V);
        TCVT(v132, v130, v15, v16);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        // pto: %kv_view_inline863_inline8978__tile_pview
        pto::Shape<1, 1, 1, 8, 64> v134 = pto::Shape<1, 1, 1, 8, 64>();
        // pto: %kv_view_inline863_inline8978__tile_pview
        pto::Stride<4096, 4096, 4096, 512, 1> v135 = pto::Stride<4096, 4096, 4096, 512, 1>();
        // pto: %kv_view_inline863_inline8978__tile_pview
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>
            v136 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
                v2 + ((v35 + v90 * v18) + v102), v134, v135
            );
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        pipe_barrier(PIPE_MTE3);
        TSTORE(v136, v132);
        set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    }
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    // pto: %22
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v137 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %22
    uint64_t v138 = (uint64_t)v35;
    TASSIGN(v137, v138);
    // pto: %60
    int64_t v139 = v38 < v35 ? v35 : v38;
    // pto: %61
    pto::Shape<1, 1, 1, 8, 64> v140 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %61
    pto::Stride<4096, 4096, 4096, 512, 1> v141 = pto::Stride<4096, 4096, 4096, 512, 1>();
    // pto: %61
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND> v142 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
            v1 + (v14 + v139 * v18), v140, v141
        );
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    TLOAD(v137, v142);
    // pto: %23
    Tile<
        TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v143 = Tile<
            TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v26);
    // pto: %23
    uint64_t v144 = (uint64_t)v33;
    TASSIGN(v143, v144);
    // pto: %62
    pto::Shape<1, 1, 1, 1, 64> v145 = pto::Shape<1, 1, 1, 1, 64>();
    // pto: %62
    pto::Stride<64, 64, 64, 64, 1> v146 = pto::Stride<64, 64, 64, 64, 1>();
    // pto: %62
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND> v147 =
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND>(
            v3 + v13, v145, v146
        );
    TLOAD(v143, v147);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
    // pto: %24
    Tile<
        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v148 = Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v26);
    // pto: %24
    uint64_t v149 = (uint64_t)v34;
    TASSIGN(v148, v149);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    TCVT(v148, v143, v17, v16);
    // pto: %25
    Tile<
        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v150 = Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v26);
    // pto: %25
    uint64_t v151 = (uint64_t)v34;
    TASSIGN(v150, v151);
    // pto: %26
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v152 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %26
    uint64_t v153 = (uint64_t)v35;
    TASSIGN(v152, v153);
    TROWEXPANDMUL(v152, v137, v83);
    // pto: %27
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v154 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %27
    uint64_t v155 = (uint64_t)v35;
    TASSIGN(v154, v155);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v154, v152, v150);
    // pto: %28
    Tile<
        TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v156 = Tile<
            TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %28
    uint64_t v157 = (uint64_t)v35;
    TASSIGN(v156, v157);
    pipe_barrier(PIPE_V);
    TCVT(v156, v154, v15, v16);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    // pto: %kv_view_inline863_inline8978__rv_v2_main_pview
    pto::Shape<1, 1, 1, 8, 64> v158 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %kv_view_inline863_inline8978__rv_v2_main_pview
    pto::Stride<4096, 4096, 4096, 512, 1> v159 = pto::Stride<4096, 4096, 4096, 512, 1>();
    // pto: %kv_view_inline863_inline8978__rv_v2_main_pview
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND> v160 =
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
            v2 + (v14 + v139 * v18), v158, v159
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    TSTORE(v160, v156);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    // pto: %29
    Tile<
        TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v161 = Tile<
            TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v26);
    // pto: %29
    uint64_t v162 = (uint64_t)v35;
    TASSIGN(v161, v162);
    // pto: %65
    pto::Shape<1, 1, 1, 1, 64> v163 = pto::Shape<1, 1, 1, 1, 64>();
    // pto: %65
    pto::Stride<64, 64, 64, 64, 1> v164 = pto::Stride<64, 64, 64, 64, 1>();
    // pto: %65
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND> v165 =
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND>(
            v3 + v12, v163, v164
        );
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    TLOAD(v161, v165);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID5);
    // pto: %gamma_rope_cast_inline830_inline9069__tile
    Tile<
        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v166 = Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v26);
    // pto: %gamma_rope_cast_inline830_inline9069__tile
    uint64_t v167 = (uint64_t)v34;
    TASSIGN(v166, v167);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID5);
    TCVT(v166, v161, v17, v16);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    // pto: %gamma_rope_inline791_inline9065__tile
    Tile<
        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v168 = Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v26);
    // pto: %gamma_rope_inline791_inline9065__tile
    uint64_t v169 = (uint64_t)v34;
    TASSIGN(v168, v169);
    // pto: %kv_rope_chunk_inline790_inline9067__tile
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v170 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %kv_rope_chunk_inline790_inline9067__tile
    uint64_t v171 = (uint64_t)v35;
    TASSIGN(v170, v171);
    // pto: %67
    pto::Shape<1, 1, 1, 8, 64> v172 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %67
    pto::Stride<4096, 4096, 4096, 512, 1> v173 = pto::Stride<4096, 4096, 4096, 512, 1>();
    // pto: %67
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND> v174 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
            v1 + (v11 + v139 * v18), v172, v173
        );
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    TLOAD(v170, v174);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID6);
    // pto: %30
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v175 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %30
    uint64_t v176 = (uint64_t)v35;
    TASSIGN(v175, v176);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID6);
    TROWEXPANDMUL(v175, v170, v83);
    // pto: %kv_rope_norm_chunk_inline772_inline9072__tile
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v177 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %kv_rope_norm_chunk_inline772_inline9072__tile
    uint64_t v178 = (uint64_t)v35;
    TASSIGN(v177, v178);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v177, v175, v168);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
    // pto: %kv_cos_il_inline789_inline9074__tile
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v179 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %kv_cos_il_inline789_inline9074__tile
    uint64_t v180 = (uint64_t)v34;
    TASSIGN(v179, v180);
    // pto: %q_rope_cos_il_inline862_inline8877__ssa_v1_pview
    pto::Shape<1, 1, 1, 8, 64> v181 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %q_rope_cos_il_inline862_inline8877__ssa_v1_pview
    pto::Stride<512, 512, 512, 64, 1> v182 = pto::Stride<512, 512, 512, 64, 1>();
    // pto: %q_rope_cos_il_inline862_inline8877__ssa_v1_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v183 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
            v4 + (v35 + v139 * v26), v181, v182
        );
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
    TLOAD(v179, v183);
    // pto: %kv_sin_signed_inline776_inline9084__tile
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v184 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %kv_sin_signed_inline776_inline9084__tile
    uint64_t v185 = (uint64_t)v33;
    TASSIGN(v184, v185);
    // pto: %q_rope_sin_signed_inline898_inline8960__ssa_v1_pview
    pto::Shape<1, 1, 1, 8, 64> v186 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %q_rope_sin_signed_inline898_inline8960__ssa_v1_pview
    pto::Stride<512, 512, 512, 64, 1> v187 = pto::Stride<512, 512, 512, 64, 1>();
    // pto: %q_rope_sin_signed_inline898_inline8960__ssa_v1_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v188 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
            v5 + (v35 + v139 * v26), v186, v187
        );
    TLOAD(v184, v188);
    // pto: %31
    Tile<
        TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v189 = Tile<
            TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %31
    uint64_t v190 = (uint64_t)v31;
    TASSIGN(v189, v190);
    // pto: %q_rope_swap_idx_inline864_inline8934__ssa_v1_pview
    pto::Shape<1, 1, 1, 8, 64> v191 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %q_rope_swap_idx_inline864_inline8934__ssa_v1_pview
    pto::Stride<512, 512, 512, 64, 1> v192 = pto::Stride<512, 512, 512, 64, 1>();
    // pto: %q_rope_swap_idx_inline864_inline8934__ssa_v1_pview
    GlobalTensor<int32_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v193 =
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
            v6 + (v35 + v139 * v26), v191, v192
        );
    TLOAD(v189, v193);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID7);
    // pto: %gather_acc_init
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v194 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %gather_acc_init
    uint64_t v195 = (uint64_t)v36;
    TASSIGN(v194, v195);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID7);
    for (int64_t i196 = v35; i196 < v25; i196 += v27) {
        // pto: %gather_inp_row
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v197 = Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %gather_inp_row
        uint64_t v198 = (uint64_t)v35;
        TASSIGN(v197, v198);
        // pto: %slice_view
        int64_t v199 = (int64_t)((uint64_t)i196 * (uint64_t)v37);
        // pto: %slice_view
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v200;
        // pto: %slice_view
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v201 = v200;
        // pto: %slice_view
        uint64_t v202 = (uint64_t)v199;
        TASSIGN(v201, v202);
        // pto: %gather_idx_row
        Tile<
            TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v203 = Tile<
                TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %gather_idx_row
        uint64_t v204 = (uint64_t)v31;
        TASSIGN(v203, v204);
        // pto: %71
        Tile<
            TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v205;
        // pto: %71
        Tile<
            TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v206 = v205;
        // pto: %71
        uint64_t v207 = (uint64_t)((int64_t)((uint64_t)v199 + (uint64_t)v31));
        TASSIGN(v206, v207);
        // pto: %gather_row_tmp
        Tile<
            TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v208 = Tile<
                TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %gather_row_tmp
        uint64_t v209 = (uint64_t)v28;
        TASSIGN(v208, v209);
        // pto: %gather_row
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v210 = Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v26);
        // pto: %gather_row
        uint64_t v211 = (uint64_t)v29;
        TASSIGN(v210, v211);
        pipe_barrier(PIPE_V);
        TGATHER(v210, v201, v206, v208);
        // pto: %assemble_view
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v212;
        // pto: %assemble_view
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v213 = v212;
        // pto: %assemble_view
        uint64_t v214 = (uint64_t)((int64_t)((uint64_t)v199 + (uint64_t)v36));
        TASSIGN(v213, v214);
        pipe_barrier(PIPE_V);
        TMOV(v213, v210);
    }
    // pto: %kv_swapped_inline771_inline8882__tile
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v215 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %kv_swapped_inline771_inline8882__tile
    uint64_t v216 = (uint64_t)v36;
    TASSIGN(v215, v216);
    // pto: %32
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v217 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %32
    uint64_t v218 = (uint64_t)v35;
    TASSIGN(v217, v218);
    TMUL(v217, v177, v179);
    // pto: %33
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v219 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %33
    uint64_t v220 = (uint64_t)v34;
    TASSIGN(v219, v220);
    pipe_barrier(PIPE_V);
    TMUL(v219, v215, v184);
    // pto: %kv_rope_rot_inline770_inline9075__tile
    Tile<
        TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v221 = Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %kv_rope_rot_inline770_inline9075__tile
    uint64_t v222 = (uint64_t)v35;
    TASSIGN(v221, v222);
    pipe_barrier(PIPE_V);
    TADD(v221, v217, v219);
    // pto: %kv_rope_i16_inline793_inline9037__tile
    Tile<
        TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v223 = Tile<
            TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %kv_rope_i16_inline793_inline9037__tile
    uint64_t v224 = (uint64_t)v35;
    TASSIGN(v223, v224);
    pipe_barrier(PIPE_V);
    TCVT(v223, v221, v15, v16);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
    // pto: %kv_view_inline863_inline8978__rv_v2_pview
    pto::Shape<1, 1, 1, 8, 64> v225 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %kv_view_inline863_inline8978__rv_v2_pview
    pto::Stride<4096, 4096, 4096, 512, 1> v226 = pto::Stride<4096, 4096, 4096, 512, 1>();
    // pto: %kv_view_inline863_inline8978__rv_v2_pview
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND> v227 =
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<4096, 4096, 4096, 512, 1>, pto::Layout::ND>(
            v2 + (v11 + v139 * v18), v225, v226
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
    TSTORE(v227, v223);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: kv_fp32_inline844_inline9035__ssa_v1
    __gm__ ChipTensor *kv_fp32_inline844_inline9035__ssa_v1_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *kv_fp32_inline844_inline9035__ssa_v1 =
        reinterpret_cast<__gm__ float *>(kv_fp32_inline844_inline9035__ssa_v1_tensor->buffer.addr) +
        kv_fp32_inline844_inline9035__ssa_v1_tensor->start_offset;

    // Unpack tensor: kv_view_inline863_inline8978__ssa_v0
    __gm__ ChipTensor *kv_view_inline863_inline8978__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ bfloat16_t *kv_view_inline863_inline8978__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(kv_view_inline863_inline8978__ssa_v0_tensor->buffer.addr) +
        kv_view_inline863_inline8978__ssa_v0_tensor->start_offset;

    // Unpack tensor: gamma_ckv_l0_inline646__ssa_v0
    __gm__ ChipTensor *gamma_ckv_l0_inline646__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ bfloat16_t *gamma_ckv_l0_inline646__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(gamma_ckv_l0_inline646__ssa_v0_tensor->buffer.addr) +
        gamma_ckv_l0_inline646__ssa_v0_tensor->start_offset;

    // Unpack tensor: q_rope_cos_il_inline862_inline8877__ssa_v1
    __gm__ ChipTensor *q_rope_cos_il_inline862_inline8877__ssa_v1_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ float *q_rope_cos_il_inline862_inline8877__ssa_v1 =
        reinterpret_cast<__gm__ float *>(q_rope_cos_il_inline862_inline8877__ssa_v1_tensor->buffer.addr) +
        q_rope_cos_il_inline862_inline8877__ssa_v1_tensor->start_offset;

    // Unpack tensor: q_rope_sin_signed_inline898_inline8960__ssa_v1
    __gm__ ChipTensor *q_rope_sin_signed_inline898_inline8960__ssa_v1_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[4]);
    __gm__ float *q_rope_sin_signed_inline898_inline8960__ssa_v1 =
        reinterpret_cast<__gm__ float *>(q_rope_sin_signed_inline898_inline8960__ssa_v1_tensor->buffer.addr) +
        q_rope_sin_signed_inline898_inline8960__ssa_v1_tensor->start_offset;

    // Unpack tensor: q_rope_swap_idx_inline864_inline8934__ssa_v1
    __gm__ ChipTensor *q_rope_swap_idx_inline864_inline8934__ssa_v1_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[5]);
    __gm__ int32_t *q_rope_swap_idx_inline864_inline8934__ssa_v1 =
        reinterpret_cast<__gm__ int32_t *>(q_rope_swap_idx_inline864_inline8934__ssa_v1_tensor->buffer.addr) +
        q_rope_swap_idx_inline864_inline8934__ssa_v1_tensor->start_offset;

    // Extract dynamic dim: t_matmul_inline856_inline8847__ssa_v0
    int64_t t_matmul_inline856_inline8847__ssa_v0 =
        static_cast<int64_t>(kv_fp32_inline844_inline9035__ssa_v1_tensor->shapes[0]);

    // Extract dynamic dim: t_dim_inline889_inline8972__ssa_v0
    int64_t t_dim_inline889_inline8972__ssa_v0 =
        static_cast<int64_t>(kv_view_inline863_inline8978__ssa_v0_tensor->shapes[0]);

    // Forward to ptoas-generated function
    kv_rms_norm_rope(
        kv_fp32_inline844_inline9035__ssa_v1, kv_view_inline863_inline8978__ssa_v0, gamma_ckv_l0_inline646__ssa_v0,
        q_rope_cos_il_inline862_inline8877__ssa_v1, q_rope_sin_signed_inline898_inline8960__ssa_v1,
        q_rope_swap_idx_inline864_inline8934__ssa_v1, t_matmul_inline856_inline8847__ssa_v0,
        t_dim_inline889_inline8972__ssa_v0, __pypto_spmd_block_idx, __pypto_spmd_block_num
    );
}
