/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: moe_signal_clear
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void moe_signal_clear(
    __gm__ float *v1, __gm__ int32_t *v2, __gm__ int32_t *v3, __gm__ int32_t *v4, __gm__ int64_t *v5,
    __gm__ int64_t *v6, __gm__ int64_t *v7, int64_t v8
) {
    const int64_t v9 = 0;
    const int64_t v10 = 2;
    const int64_t v11 = 1;
    const int32_t v12 = 0;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    for (int64_t i13 = v9; i13 < v10; i13 += v11) {
        (v2)[i13] = v12;
        // pto: %arrived__ssa_v0_pview
        pto::Shape<1, 1, 1, 2, 1> v14 = pto::Shape<1, 1, 1, 2, 1>();
        // pto: %arrived__ssa_v0_pview
        pto::Stride<2, 2, 2, 1, 2> v15 = pto::Stride<2, 2, 2, 1, 2>();
        // pto: %arrived__ssa_v0_pview
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 2>, pto::Layout::DN> v16 =
            GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 2>, pto::Layout::DN>(v2, v14, v15);
        __gm__ int32_t *v17 = PTOAS__GLOBAL_TENSOR_DATA(v16);
        PTOAS__DCCI_SINGLE_CACHE_LINE(v17);
        pipe_barrier(PIPE_ALL);
        dsb(DSB_DDR);
        (v3)[i13] = v12;
        // pto: %data_arrived__ssa_v0_pview
        pto::Shape<1, 1, 1, 2, 1> v18 = pto::Shape<1, 1, 1, 2, 1>();
        // pto: %data_arrived__ssa_v0_pview
        pto::Stride<2, 2, 2, 1, 2> v19 = pto::Stride<2, 2, 2, 1, 2>();
        // pto: %data_arrived__ssa_v0_pview
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 2>, pto::Layout::DN> v20 =
            GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 2>, pto::Layout::DN>(v3, v18, v19);
        __gm__ int32_t *v21 = PTOAS__GLOBAL_TENSOR_DATA(v20);
        PTOAS__DCCI_SINGLE_CACHE_LINE(v21);
        pipe_barrier(PIPE_ALL);
        dsb(DSB_DDR);
        (v4)[i13] = v12;
        // pto: %combine_arrived__ssa_v0_pview
        pto::Shape<1, 1, 1, 2, 1> v22 = pto::Shape<1, 1, 1, 2, 1>();
        // pto: %combine_arrived__ssa_v0_pview
        pto::Stride<2, 2, 2, 1, 2> v23 = pto::Stride<2, 2, 2, 1, 2>();
        // pto: %combine_arrived__ssa_v0_pview
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 2>, pto::Layout::DN> v24 =
            GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 2>, pto::Layout::DN>(v4, v22, v23);
        __gm__ int32_t *v25 = PTOAS__GLOBAL_TENSOR_DATA(v24);
        PTOAS__DCCI_SINGLE_CACHE_LINE(v25);
        pipe_barrier(PIPE_ALL);
        dsb(DSB_DDR);
    }
    pipe_barrier(PIPE_ALL);
    dcci((__gm__ void *)0, cache_line_t::ENTIRE_DATA_CACHE);
    dsb((mem_dsb_t)0);
#endif  // __DAV_VEC__

    pipe_barrier(PIPE_ALL);
    dcci((__gm__ void *)0, cache_line_t::ENTIRE_DATA_CACHE);
    dsb((mem_dsb_t)0);
    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Unpack tensor: pre_hc_hidden_out__ssa_v0
    __gm__ ChipTensor *pre_hc_hidden_out__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *pre_hc_hidden_out__ssa_v0 =
        reinterpret_cast<__gm__ float *>(pre_hc_hidden_out__ssa_v0_tensor->buffer.addr) +
        pre_hc_hidden_out__ssa_v0_tensor->start_offset;

    // Unpack tensor: arrived__ssa_v0
    __gm__ ChipTensor *arrived__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ int32_t *arrived__ssa_v0 =
        reinterpret_cast<__gm__ int32_t *>(arrived__ssa_v0_tensor->buffer.addr) + arrived__ssa_v0_tensor->start_offset;

    // Unpack tensor: data_arrived__ssa_v0
    __gm__ ChipTensor *data_arrived__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ int32_t *data_arrived__ssa_v0 =
        reinterpret_cast<__gm__ int32_t *>(data_arrived__ssa_v0_tensor->buffer.addr) +
        data_arrived__ssa_v0_tensor->start_offset;

    // Unpack tensor: combine_arrived__ssa_v0
    __gm__ ChipTensor *combine_arrived__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ int32_t *combine_arrived__ssa_v0 =
        reinterpret_cast<__gm__ int32_t *>(combine_arrived__ssa_v0_tensor->buffer.addr) +
        combine_arrived__ssa_v0_tensor->start_offset;

    // Unpack CommContext: arrived_ctx
    __gm__ int64_t *arrived_ctx = reinterpret_cast<__gm__ int64_t *>(args[4]);

    // Unpack CommContext: data_arrived_ctx
    __gm__ int64_t *data_arrived_ctx = reinterpret_cast<__gm__ int64_t *>(args[5]);

    // Unpack CommContext: combine_arrived_ctx
    __gm__ int64_t *combine_arrived_ctx = reinterpret_cast<__gm__ int64_t *>(args[6]);

    // Extract dynamic dim: T_DYN
    int64_t T_DYN = static_cast<int64_t>(pre_hc_hidden_out__ssa_v0_tensor->shapes[0]);

    // Forward to ptoas-generated function
    moe_signal_clear(
        pre_hc_hidden_out__ssa_v0, arrived__ssa_v0, data_arrived__ssa_v0, combine_arrived__ssa_v0, arrived_ctx,
        data_arrived_ctx, combine_arrived_ctx, T_DYN
    );
}
