/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: pack_x_hc
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void
pack_x_hc(__gm__ float *v1, __gm__ int64_t *v2, __gm__ bfloat16_t *v3, int64_t v4, int32_t v5, int32_t v6) {
    SaturationMode v7 = SaturationMode::OFF;
    RoundMode v8 = RoundMode::CAST_ROUND;
    const int64_t v9 = 4096;
    const int64_t v10 = 4;
    const int64_t v11 = 512;
    const int64_t v12 = 48;
    const int64_t v13 = 64;
    const int64_t v14 = 8;
    const int64_t v15 = 1;
    const int64_t v16 = 1024;
    const int64_t v17 = 0;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %block_inline8699__ssa_v0
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    for (int64_t i18 = (int64_t)v5; i18 < v13; i18 += v12) {
        // pto: %0
        int64_t v19 = i18 / v14;
        // pto: %1, %2
        int64_t v20 = (int64_t)((uint64_t)(i18 % v14) * (uint64_t)v11);
        // pto: %token_id_inline8695__tile
        int64_t v21 = (v2)[v19];
        // pto: %t__tile
        Tile<
            TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v22 = Tile<
                TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v11);
        // pto: %t__tile
        uint64_t v23 = (uint64_t)v17;
        TASSIGN(v22, v23);
        // pto: %5
        int64_t v24 = v20 < v17 ? v17 : v20;
        // pto: %embed_weight__ssa_v0_pview
        pto::Shape<1, 1, 1, 1, 512> v25 = pto::Shape<1, 1, 1, 1, 512>();
        // pto: %embed_weight__ssa_v0_pview
        pto::Stride<4096, 4096, 4096, 4096, 1> v26 = pto::Stride<4096, 4096, 4096, 4096, 1>();
        // pto: %4, %embed_weight__ssa_v0_pview
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>
            v27 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(
                v3 + ((v17 + (v21 < v17 ? v17 : v21) * v9) + v24), v25, v26
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v22, v27);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %hidden_chunk_inline8693__tile
        Tile<
            TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v28 = Tile<
                TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v11);
        // pto: %hidden_chunk_inline8693__tile
        uint64_t v29 = (uint64_t)v16;
        TASSIGN(v28, v29);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
        TCVT(v28, v22, v8, v7);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        for (int64_t j30 = v17; j30 < v10; j30 += v15) {
            // pto: %6, %7
            int64_t v31 = (int64_t)((uint64_t)((int64_t)((uint64_t)v19 * (uint64_t)v10)) + (uint64_t)j30);
            // pto: %x_hc_flat_inline8701__iter_v3_pview
            pto::Shape<1, 1, 1, 1, 512> v32 = pto::Shape<1, 1, 1, 1, 512>();
            // pto: %x_hc_flat_inline8701__iter_v3_pview
            pto::Stride<4096, 4096, 4096, 4096, 1> v33 = pto::Stride<4096, 4096, 4096, 4096, 1>();
            // pto: %8, %x_hc_flat_inline8701__iter_v3_pview
            GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>
                v34 = GlobalTensor<
                    float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(
                    v1 + ((v17 + (v31 < v17 ? v17 : v31) * v9) + v24), v32, v33
                );
            pipe_barrier(PIPE_MTE3);
            TSTORE(v34, v28);
        }
        set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    }
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: x_hc_flat_inline8701__ssa_v0
    __gm__ ChipTensor *x_hc_flat_inline8701__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *x_hc_flat_inline8701__ssa_v0 =
        reinterpret_cast<__gm__ float *>(x_hc_flat_inline8701__ssa_v0_tensor->buffer.addr) +
        x_hc_flat_inline8701__ssa_v0_tensor->start_offset;

    // Unpack tensor: input_ids__ssa_v0
    __gm__ ChipTensor *input_ids__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ int64_t *input_ids__ssa_v0 = reinterpret_cast<__gm__ int64_t *>(input_ids__ssa_v0_tensor->buffer.addr) +
                                        input_ids__ssa_v0_tensor->start_offset;

    // Unpack tensor: embed_weight__ssa_v0
    __gm__ ChipTensor *embed_weight__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ bfloat16_t *embed_weight__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(embed_weight__ssa_v0_tensor->buffer.addr) +
        embed_weight__ssa_v0_tensor->start_offset;

    // Extract dynamic dim: PACK_X_HC_VOCAB_DYN
    int64_t PACK_X_HC_VOCAB_DYN = static_cast<int64_t>(embed_weight__ssa_v0_tensor->shapes[0]);

    // Forward to ptoas-generated function
    pack_x_hc(
        x_hc_flat_inline8701__ssa_v0, input_ids__ssa_v0, embed_weight__ssa_v0, PACK_X_HC_VOCAB_DYN,
        __pypto_spmd_block_idx, __pypto_spmd_block_num
    );
}
