/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: proj_b_act_2
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void
proj_b_act_2(__gm__ float *v1, __gm__ int32_t *v2, __gm__ float *v3, __gm__ bfloat16_t *v4, int32_t v5, int32_t v6) {
    RoundMode v7 = RoundMode::CAST_RINT;
    SaturationMode v8 = SaturationMode::OFF;
    RoundMode v9 = RoundMode::CAST_NONE;
    const int64_t v10 = 2;
    const float v11 = 0.0f;
    const int64_t v12 = 512;
    const int64_t v13 = 8;
    const int64_t v14 = 1;
    const int64_t v15 = 4096;
    const int64_t v16 = 51232;
    const int64_t v17 = 34848;
    const int64_t v18 = 34816;
    const int64_t v19 = 18432;
    const int64_t v20 = 2048;
    const int64_t v21 = 0;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %act_idx_inline1429_inline11283__ssa_v0, %8
    int64_t v22 = (int64_t)((uint64_t)((int64_t)v5) * (uint64_t)v12);
    // pto: %wb_scale_inline1510_inline11688__tile
    Tile<
        TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v23 = Tile<
            TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v12);
    // pto: %wb_scale_inline1510_inline11688__tile
    uint64_t v24 = (uint64_t)v21;
    TASSIGN(v23, v24);
    // pto: %10
    int64_t v25 = v22 < v21 ? v21 : v22;
    // pto: %wo_b_scale_hca_inline546__ssa_v0_pview
    pto::Shape<1, 1, 1, 1, 512> v26 = pto::Shape<1, 1, 1, 1, 512>();
    // pto: %wo_b_scale_hca_inline546__ssa_v0_pview
    pto::Stride<512, 512, 512, 512, 1> v27 = pto::Stride<512, 512, 512, 512, 1>();
    // pto: %wo_b_scale_hca_inline546__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v28 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(
            v1 + (v21 + v25), v26, v27
        );
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    TLOAD(v23, v28);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
    // pto: %wb_scale_chunk_inline1535_inline11444__tile
    Tile<
        TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v29 = Tile<
            TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v12);
    // pto: %wb_scale_chunk_inline1535_inline11444__tile
    uint64_t v30 = (uint64_t)v21;
    TASSIGN(v29, v30);
    // pto: %acc_inline1442_inline11461__tile
    Tile<
        TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v31 = Tile<
            TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v13, v12);
    // pto: %acc_inline1442_inline11461__tile
    uint64_t v32 = (uint64_t)v20;
    TASSIGN(v31, v32);
    TEXPANDS(v31, v11);
    for (int64_t i33 = v21; i33 < v13; i33 += v10) {
        // pto: %11, %12
        int64_t v34 = (int64_t)((uint64_t)((int64_t)((uint64_t)i33 * (uint64_t)v15)) + (uint64_t)v22);
        // pto: %15
        int64_t v35 = (int64_t)((uint64_t)v34 + (uint64_t)v15);
        // pto: %p_g_inline1426_inline11279__tile
        Tile<
            TileType::Vec, int32_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v36 = Tile<
                TileType::Vec, int32_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %p_g_inline1426_inline11279__tile
        uint64_t v37 = (uint64_t)v19;
        TASSIGN(v36, v37);
        // pto: %partials_inline1608_inline11714__rv_v2_pview
        pto::Shape<1, 1, 1, 8, 512> v38 = pto::Shape<1, 1, 1, 8, 512>();
        // pto: %partials_inline1608_inline11714__rv_v2_pview
        pto::Stride<262144, 262144, 262144, 32768, 1> v39 = pto::Stride<262144, 262144, 262144, 32768, 1>();
        // pto: %17, %partials_inline1608_inline11714__rv_v2_pview
        GlobalTensor<
            int32_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>
            v40 = GlobalTensor<
                int32_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>(
                v2 + (v21 + (v34 < v21 ? v21 : v34)), v38, v39
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v36, v40);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %g_scale_row_inline1425_inline11362__tile
        Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v41 = Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v14, v13);
        // pto: %g_scale_row_inline1425_inline11362__tile
        uint64_t v42 = (uint64_t)v18;
        TASSIGN(v41, v42);
        // pto: %act_scale_dq_inline1577_inline11391__rv_v2_pview
        pto::Shape<1, 1, 1, 1, 8> v43 = pto::Shape<1, 1, 1, 1, 8>();
        // pto: %act_scale_dq_inline1577_inline11391__rv_v2_pview
        pto::Stride<8, 8, 8, 8, 1> v44 = pto::Stride<8, 8, 8, 8, 1>();
        // pto: %18, %act_scale_dq_inline1577_inline11391__rv_v2_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND> v45 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND>(
                v3 + (v21 + (i33 < v21 ? v21 : i33) * v13), v43, v44
            );
        TLOAD(v41, v45);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        // pto: %0
        Tile<
            TileType::Vec, int32_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v46 = Tile<
                TileType::Vec, int32_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %0
        uint64_t v47 = (uint64_t)v17;
        TASSIGN(v46, v47);
        // pto: %22
        pto::Shape<1, 1, 1, 8, 512> v48 = pto::Shape<1, 1, 1, 8, 512>();
        // pto: %22
        pto::Stride<262144, 262144, 262144, 32768, 1> v49 = pto::Stride<262144, 262144, 262144, 32768, 1>();
        // pto: %21, %22
        GlobalTensor<
            int32_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>
            v50 = GlobalTensor<
                int32_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>(
                v2 + (v21 + (v35 < v21 ? v21 : v35)), v48, v49
            );
        TLOAD(v46, v50);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        // pto: %1
        Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v51 = Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v14, v13);
        // pto: %1
        uint64_t v52 = (uint64_t)v16;
        TASSIGN(v51, v52);
        // pto: %23
        int64_t v53 = (int64_t)((uint64_t)i33 + (uint64_t)v14);
        // pto: %26
        pto::Shape<1, 1, 1, 1, 8> v54 = pto::Shape<1, 1, 1, 1, 8>();
        // pto: %26
        pto::Stride<8, 8, 8, 8, 1> v55 = pto::Stride<8, 8, 8, 8, 1>();
        // pto: %24, %26
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND> v56 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND>(
                v3 + (v21 + (v53 < v21 ? v21 : v53) * v13), v54, v55
            );
        TLOAD(v51, v56);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        // pto: %g_scale_inline1424_inline11518__tile
        Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v57 = Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v14);
        // pto: %g_scale_inline1424_inline11518__tile
        uint64_t v58 = (uint64_t)v18;
        TASSIGN(v57, v58);
        // pto: %p_g_f32_inline1441_inline11278__tile
        Tile<
            TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v59 = Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %p_g_f32_inline1441_inline11278__tile
        uint64_t v60 = (uint64_t)v19;
        TASSIGN(v59, v60);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        TCVT(v59, v36, v9, v8);
        // pto: %p_g_scaled_inline1423_inline11277__tile
        Tile<
            TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v61 = Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %p_g_scaled_inline1423_inline11277__tile
        uint64_t v62 = (uint64_t)v19;
        TASSIGN(v61, v62);
        pipe_barrier(PIPE_V);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        TROWEXPANDMUL(v61, v59, v57);
        // pto: %2
        Tile<
            TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v63 = Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %2
        uint64_t v64 = (uint64_t)v19;
        TASSIGN(v63, v64);
        pipe_barrier(PIPE_V);
        TADD(v63, v31, v61);
        // pto: %3
        Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v65 = Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v14);
        // pto: %3
        uint64_t v66 = (uint64_t)v16;
        TASSIGN(v65, v66);
        // pto: %4
        Tile<
            TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v67 = Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %4
        uint64_t v68 = (uint64_t)v17;
        TASSIGN(v67, v68);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        TCVT(v67, v46, v9, v8);
        // pto: %5
        Tile<
            TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v69 = Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %5
        uint64_t v70 = (uint64_t)v17;
        TASSIGN(v69, v70);
        pipe_barrier(PIPE_V);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        TROWEXPANDMUL(v69, v67, v65);
        // pto: %6
        Tile<
            TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v71 = Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %6
        uint64_t v72 = (uint64_t)v20;
        TASSIGN(v71, v72);
        pipe_barrier(PIPE_V);
        TADD(v71, v63, v69);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    }
    // pto: %out_t_inline1565_inline11397__tile
    Tile<
        TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v73 = Tile<
            TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v13, v12);
    // pto: %out_t_inline1565_inline11397__tile
    uint64_t v74 = (uint64_t)v20;
    TASSIGN(v73, v74);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
    TCOLEXPANDMUL(v73, v31, v29);
    // pto: %out_bf16_inline1422_inline11276__tile
    Tile<
        TileType::Vec, bfloat16_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v75 = Tile<
            TileType::Vec, bfloat16_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v13, v12);
    // pto: %out_bf16_inline1422_inline11276__tile
    uint64_t v76 = (uint64_t)v20;
    TASSIGN(v75, v76);
    pipe_barrier(PIPE_V);
    TCVT(v75, v73, v7, v8);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    // pto: %attn_out_inline11390__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 512> v77 = pto::Shape<1, 1, 1, 8, 512>();
    // pto: %attn_out_inline11390__ssa_v0_pview
    pto::Stride<32768, 32768, 32768, 4096, 1> v78 = pto::Stride<32768, 32768, 32768, 4096, 1>();
    // pto: %attn_out_inline11390__ssa_v0_pview
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<32768, 32768, 32768, 4096, 1>, pto::Layout::ND>
        v79 = GlobalTensor<
            bfloat16_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<32768, 32768, 32768, 4096, 1>, pto::Layout::ND>(
            v4 + (v21 + v25), v77, v78
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v79, v75);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: wo_b_scale_hca_inline546__ssa_v0
    __gm__ ChipTensor *wo_b_scale_hca_inline546__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *wo_b_scale_hca_inline546__ssa_v0 =
        reinterpret_cast<__gm__ float *>(wo_b_scale_hca_inline546__ssa_v0_tensor->buffer.addr) +
        wo_b_scale_hca_inline546__ssa_v0_tensor->start_offset;

    // Unpack tensor: partials_inline1608_inline11714__rv_v2
    __gm__ ChipTensor *partials_inline1608_inline11714__rv_v2_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ int32_t *partials_inline1608_inline11714__rv_v2 =
        reinterpret_cast<__gm__ int32_t *>(partials_inline1608_inline11714__rv_v2_tensor->buffer.addr) +
        partials_inline1608_inline11714__rv_v2_tensor->start_offset;

    // Unpack tensor: act_scale_dq_inline1577_inline11391__rv_v2
    __gm__ ChipTensor *act_scale_dq_inline1577_inline11391__rv_v2_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ float *act_scale_dq_inline1577_inline11391__rv_v2 =
        reinterpret_cast<__gm__ float *>(act_scale_dq_inline1577_inline11391__rv_v2_tensor->buffer.addr) +
        act_scale_dq_inline1577_inline11391__rv_v2_tensor->start_offset;

    // Unpack tensor: attn_out_inline11390__ssa_v0
    __gm__ ChipTensor *attn_out_inline11390__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ bfloat16_t *attn_out_inline11390__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(attn_out_inline11390__ssa_v0_tensor->buffer.addr) +
        attn_out_inline11390__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    proj_b_act_2(
        wo_b_scale_hca_inline546__ssa_v0, partials_inline1608_inline11714__rv_v2,
        act_scale_dq_inline1577_inline11391__rv_v2, attn_out_inline11390__ssa_v0, __pypto_spmd_block_idx,
        __pypto_spmd_block_num
    );
}
