/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: qproj_dequant_rms_nope_rope_3
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void qproj_dequant_rms_nope_rope_3(
    __gm__ bfloat16_t *v1, __gm__ float *v2, __gm__ float *v3, __gm__ float *v4, __gm__ int32_t *v5, __gm__ int32_t *v6,
    __gm__ float *v7, int64_t v8, int64_t v9, int64_t v10, int64_t v11, int32_t v12, int32_t v13
) {
    RoundMode v14 = RoundMode::CAST_RINT;
    SaturationMode v15 = SaturationMode::OFF;
    RoundMode v16 = RoundMode::CAST_NONE;
    const int64_t v17 = 32768;
    const int64_t v18 = 448;
    const float v19 = 9.99999997E-7f;
    const float v20 = 0.001953125f;
    const int64_t v21 = 512;
    const int64_t v22 = 2;
    const int64_t v23 = 8;
    const int64_t v24 = 4;
    const int64_t v25 = 64;
    const int64_t v26 = 1;
    const int64_t v27 = 101184;
    const int64_t v28 = 20224;
    const int64_t v29 = 100928;
    const int64_t v30 = 100896;
    const int64_t v31 = 84512;
    const int64_t v32 = 67872;
    const int64_t v33 = 3840;
    const int64_t v34 = 67616;
    const int64_t v35 = 67584;
    const int64_t v36 = 51200;
    const int64_t v37 = 68128;
    const int64_t v38 = 18432;
    const int64_t v39 = 34816;
    const int64_t v40 = 2048;
    const int64_t v41 = 0;
    const int64_t v42 = 103520;
    const int64_t v43 = 101472;
    const int64_t v44 = 101440;
    const int64_t v45 = 256;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_view
    int64_t v46 = v10 * v26;
    // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_view
    int64_t v47 = v26 * v46;
    // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_view
    pto::Shape<1, 1, 1, -1, -1> v48 = pto::Shape<1, 1, 1, -1, -1>(v26, v26, v26, v10, v26);
    // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_view
    pto::Stride<-1, -1, -1, -1, -1> v49 = pto::Stride<-1, -1, -1, -1, -1>(v26 * v47, v47, v46, v26, v10);
    // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_view
    GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v50 =
        GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(
            v2, v48, v49
        );
    // pto: %hg_idx_inline1796_inline12791__ssa_v0, %32
    int64_t v51 = (int64_t)((uint64_t)((int64_t)v12) * (uint64_t)v24);
    // pto: %33
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    for (int64_t i52 = v41; i52 < (v10 / v23); i52 += v26) {
        // pto: %34
        int64_t v53 = (int64_t)((uint64_t)i52 * (uint64_t)v23);
        // pto: %qr_scale_dq_t_inline1798_inline12333__tile
        Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v54 = Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v23, v26);
        // pto: %qr_scale_dq_t_inline1798_inline12333__tile
        uint64_t v55 = (uint64_t)v44;
        TASSIGN(v54, v55);
        // pto: %35
        int64_t v56 = v53 < v41 ? v41 : v53;
        // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_pview
        __gm__ float *v57 = PTOAS__GLOBAL_TENSOR_DATA(v50);
        // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_pview
        int64_t v58 = v23 * v26;
        // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_pview
        int64_t v59 = v26 * v58;
        // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_pview
        pto::Shape<1, 1, 1, 8, 1> v60 = pto::Shape<1, 1, 1, 8, 1>(v26, v26, v26, v23, v26);
        // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_pview
        pto::Stride<-1, -1, -1, -1, -1> v61 = pto::Stride<-1, -1, -1, -1, -1>(v26 * v59, v59, v58, v26, v10);
        // pto: %qr_scale_view_inline1722_inline12507__ssa_v1_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v62 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(
                v57 + ((v41 + v56 * v26) + v41 * v10), v60, v61
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v54, v62);
        // pto: %q_cos_il_inline1800_inline12457__tile
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v63 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v23, v25);
        // pto: %q_cos_il_inline1800_inline12457__tile
        uint64_t v64 = (uint64_t)v43;
        TASSIGN(v63, v64);
        // pto: %q_rope_cos_il_inline1745_inline12266__ssa_v1_pview
        pto::Shape<1, 1, 1, 8, 64> v65 = pto::Shape<1, 1, 1, 8, 64>();
        // pto: %q_rope_cos_il_inline1745_inline12266__ssa_v1_pview
        pto::Stride<512, 512, 512, 64, 1> v66 = pto::Stride<512, 512, 512, 64, 1>();
        // pto: %q_rope_cos_il_inline1745_inline12266__ssa_v1_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v67 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
                v3 + (v41 + v56 * v25), v65, v66
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        TLOAD(v63, v67);
        // pto: %q_sin_signed_inline1802_inline12331__tile
        Tile<
            TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v68 = Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v23, v25);
        // pto: %q_sin_signed_inline1802_inline12331__tile
        uint64_t v69 = (uint64_t)v42;
        TASSIGN(v68, v69);
        // pto: %q_rope_sin_signed_inline1781_inline12527__ssa_v1_pview
        pto::Shape<1, 1, 1, 8, 64> v70 = pto::Shape<1, 1, 1, 8, 64>();
        // pto: %q_rope_sin_signed_inline1781_inline12527__ssa_v1_pview
        pto::Stride<512, 512, 512, 64, 1> v71 = pto::Stride<512, 512, 512, 64, 1>();
        // pto: %q_rope_sin_signed_inline1781_inline12527__ssa_v1_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v72 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
                v4 + (v41 + v56 * v25), v70, v71
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
        TLOAD(v68, v72);
        // pto: %q_swap_idx_inline1804_inline12746__tile
        Tile<
            TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v73 = Tile<
                TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v23, v25);
        // pto: %q_swap_idx_inline1804_inline12746__tile
        uint64_t v74 = (uint64_t)v41;
        TASSIGN(v73, v74);
        // pto: %q_rope_swap_idx_inline1747_inline12787__ssa_v1_pview
        pto::Shape<1, 1, 1, 8, 64> v75 = pto::Shape<1, 1, 1, 8, 64>();
        // pto: %q_rope_swap_idx_inline1747_inline12787__ssa_v1_pview
        pto::Stride<512, 512, 512, 64, 1> v76 = pto::Stride<512, 512, 512, 64, 1>();
        // pto: %q_rope_swap_idx_inline1747_inline12787__ssa_v1_pview
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v77 =
            GlobalTensor<int32_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
                v5 + (v41 + v56 * v25), v75, v76
            );
        TLOAD(v73, v77);
        for (int64_t j78 = v41; j78 < v24; j78 += v22) {
            // pto: %39, %40
            int64_t v79 = (int64_t)((uint64_t)((int64_t)((uint64_t)v51 + (uint64_t)j78)) * (uint64_t)v21);
            // pto: %42, %41, %43
            int64_t v80 =
                (int64_t)((uint64_t)((int64_t)((uint64_t)v51 + (uint64_t)((int64_t)((uint64_t)j78 + (uint64_t)v26)))) *
                          (uint64_t)v21);
            // pto: %q_head_acc_inline1679_inline12339__tile
            Tile<
                TileType::Vec, int32_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v81 = Tile<
                    TileType::Vec, int32_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %q_head_acc_inline1679_inline12339__tile
            uint64_t v82 = (uint64_t)v40;
            TASSIGN(v81, v82);
            // pto: %45
            int64_t v83 = v79 < v41 ? v41 : v79;
            // pto: %q_proj_i32_inline1756_inline12345__rv_v2_pview
            pto::Shape<1, 1, 1, 8, 512> v84 = pto::Shape<1, 1, 1, 8, 512>();
            // pto: %q_proj_i32_inline1756_inline12345__rv_v2_pview
            pto::Stride<262144, 262144, 262144, 32768, 1> v85 = pto::Stride<262144, 262144, 262144, 32768, 1>();
            // pto: %q_proj_i32_inline1756_inline12345__rv_v2_pview
            GlobalTensor<
                int32_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>
                v86 = GlobalTensor<
                    int32_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<262144, 262144, 262144, 32768, 1>,
                    pto::Layout::ND>(v6 + ((v41 + v56 * v17) + v83), v84, v85);
            wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
            TLOAD(v81, v86);
            set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
            // pto: %t__tile
            Tile<
                TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v87 = Tile<
                    TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v21);
            // pto: %t__tile
            uint64_t v88 = (uint64_t)v39;
            TASSIGN(v87, v88);
            // pto: %wq_b_scale_last_inline574__ssa_v0_pview
            pto::Shape<1, 1, 1, 1, 512> v89 = pto::Shape<1, 1, 1, 1, 512>();
            // pto: %wq_b_scale_last_inline574__ssa_v0_pview
            pto::Stride<512, 512, 512, 512, 1> v90 = pto::Stride<512, 512, 512, 512, 1>();
            // pto: %wq_b_scale_last_inline574__ssa_v0_pview
            GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v91 =
                GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(
                    v7 + (v41 + v83), v89, v90
                );
            TLOAD(v87, v91);
            set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
            // pto: %0
            Tile<
                TileType::Vec, int32_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v92 = Tile<
                    TileType::Vec, int32_t, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %0
            uint64_t v93 = (uint64_t)v38;
            TASSIGN(v92, v93);
            // pto: %48
            int64_t v94 = v80 < v41 ? v41 : v80;
            // pto: %49
            pto::Shape<1, 1, 1, 8, 512> v95 = pto::Shape<1, 1, 1, 8, 512>();
            // pto: %49
            pto::Stride<262144, 262144, 262144, 32768, 1> v96 = pto::Stride<262144, 262144, 262144, 32768, 1>();
            // pto: %49
            GlobalTensor<
                int32_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>
                v97 = GlobalTensor<
                    int32_t, pto::Shape<1, 1, 1, 8, 512>, pto::Stride<262144, 262144, 262144, 32768, 1>,
                    pto::Layout::ND>(v6 + ((v41 + v56 * v17) + v94), v95, v96);
            wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
            TLOAD(v92, v97);
            set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
            // pto: %1
            Tile<
                TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v98 = Tile<
                    TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v21);
            // pto: %1
            uint64_t v99 = (uint64_t)v37;
            TASSIGN(v98, v99);
            // pto: %51
            pto::Shape<1, 1, 1, 1, 512> v100 = pto::Shape<1, 1, 1, 1, 512>();
            // pto: %51
            pto::Stride<512, 512, 512, 512, 1> v101 = pto::Stride<512, 512, 512, 512, 1>();
            // pto: %51
            GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v102 =
                GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(
                    v7 + (v41 + v94), v100, v101
                );
            TLOAD(v98, v102);
            set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
            // pto: %q_head_scale_inline1807_inline12321__tile
            Tile<
                TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v103 = Tile<
                    TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v21);
            // pto: %q_head_scale_inline1807_inline12321__tile
            uint64_t v104 = (uint64_t)v39;
            TASSIGN(v103, v104);
            // pto: %q_head_acc_fp32_inline1757_inline12494__tile
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v105 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %q_head_acc_fp32_inline1757_inline12494__tile
            uint64_t v106 = (uint64_t)v40;
            TASSIGN(v105, v106);
            wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
            TCVT(v105, v81, v16, v15);
            // pto: %q_head_row_scaled_inline1809_inline12319__tile
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v107 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %q_head_row_scaled_inline1809_inline12319__tile
            uint64_t v108 = (uint64_t)v40;
            TASSIGN(v107, v108);
            pipe_barrier(PIPE_V);
            TROWEXPANDMUL(v107, v105, v54);
            // pto: %q_head_dq_inline1718_inline12316__tile
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v109 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %q_head_dq_inline1718_inline12316__tile
            uint64_t v110 = (uint64_t)v40;
            TASSIGN(v109, v110);
            pipe_barrier(PIPE_V);
            wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
            TCOLEXPANDMUL(v109, v107, v103);
            // pto: %q_head_sq_inline1810_inline12616__tile
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v111 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %q_head_sq_inline1810_inline12616__tile
            uint64_t v112 = (uint64_t)v39;
            TASSIGN(v111, v112);
            pipe_barrier(PIPE_V);
            TMUL(v111, v109, v109);
            // pto: %tmp_tile
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v113 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %tmp_tile
            uint64_t v114 = (uint64_t)v36;
            TASSIGN(v113, v114);
            // pto: %q_head_sq_row_inline1799_inline12707__tile
            Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v115 = Tile<
                    TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v26);
            // pto: %q_head_sq_row_inline1799_inline12707__tile
            uint64_t v116 = (uint64_t)v35;
            TASSIGN(v115, v116);
            pipe_barrier(PIPE_V);
            TROWSUM(v115, v111, v113);
            // pto: %q_head_sq_sum_inline1815_inline12311__tile
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v117 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %q_head_sq_sum_inline1815_inline12311__tile
            uint64_t v118 = (uint64_t)v35;
            TASSIGN(v117, v118);
            // pto: %q_head_sq_mean_inline1801_inline12287__tile
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v119 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %q_head_sq_mean_inline1801_inline12287__tile
            uint64_t v120 = (uint64_t)v39;
            TASSIGN(v119, v120);
            pipe_barrier(PIPE_V);
            TMULS(v119, v117, v20);
            // pto: %q_head_var_inline1792_inline12314__tile
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v121 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %q_head_var_inline1792_inline12314__tile
            uint64_t v122 = (uint64_t)v39;
            TASSIGN(v121, v122);
            pipe_barrier(PIPE_V);
            TADDS(v121, v119, v19);
            // pto: %rsqrt_tmp
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v123 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %rsqrt_tmp
            uint64_t v124 = (uint64_t)v36;
            TASSIGN(v123, v124);
            // pto: %q_head_inv_rms_inline1785_inline12402__tile
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v125 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %q_head_inv_rms_inline1785_inline12402__tile
            uint64_t v126 = (uint64_t)v34;
            TASSIGN(v125, v126);
            pipe_barrier(PIPE_V);
            TRSQRT(v125, v121, v123);
            // pto: %q_head_inv_rms_t_inline1811_inline12310__tile
            Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v127 = Tile<
                    TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v26);
            // pto: %q_head_inv_rms_t_inline1811_inline12310__tile
            uint64_t v128 = (uint64_t)v34;
            TASSIGN(v127, v128);
            // pto: %2
            Tile<
                TileType::Vec, float, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v129 = Tile<
                    TileType::Vec, float, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v18);
            // pto: %2
            uint64_t v130 = (uint64_t)v40;
            TASSIGN(v129, v130);
            // pto: %slice_view
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, 8, 448, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v131;
            // pto: %slice_view
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, 8, 448, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v132 = v131;
            // pto: %slice_view
            uint64_t v133 = (uint64_t)v40;
            TASSIGN(v132, v133);
            // pto: %q_nope_normed_inline1812_inline12306__tile
            Tile<
                TileType::Vec, float, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v134 = Tile<
                    TileType::Vec, float, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v18);
            // pto: %q_nope_normed_inline1812_inline12306__tile
            uint64_t v135 = (uint64_t)v39;
            TASSIGN(v134, v135);
            pipe_barrier(PIPE_V);
            TROWEXPANDMUL(v134, v132, v127);
            // pto: %q_nope_bf16_inline1719_inline12629__tile
            Tile<
                TileType::Vec, bfloat16_t, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v136 = Tile<
                    TileType::Vec, bfloat16_t, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v18);
            // pto: %q_nope_bf16_inline1719_inline12629__tile
            uint64_t v137 = (uint64_t)v39;
            TASSIGN(v136, v137);
            pipe_barrier(PIPE_V);
            TCVT(v136, v134, v14, v15);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
            // pto: %q_rope_chunk_raw_inline1706_inline12305__tile
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v138 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %q_rope_chunk_raw_inline1706_inline12305__tile
            uint64_t v139 = (uint64_t)v33;
            TASSIGN(v138, v139);
            // pto: %52
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v140;
            // pto: %52
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v141 = v140;
            // pto: %52
            uint64_t v142 = (uint64_t)v33;
            TASSIGN(v141, v142);
            // pto: %q_rope_chunk_inline1814_inline12350__tile
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v143 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %q_rope_chunk_inline1814_inline12350__tile
            uint64_t v144 = (uint64_t)v40;
            TASSIGN(v143, v144);
            TROWEXPANDMUL(v143, v141, v127);
            // pto: %gather_acc_init
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v145 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %gather_acc_init
            uint64_t v146 = (uint64_t)v36;
            TASSIGN(v145, v146);
            for (int64_t k147 = v41; k147 < v23; k147 += v26) {
                // pto: %gather_inp_row
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v148 = Tile<
                        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                        CompactMode::Null>(v26, v25);
                // pto: %gather_inp_row
                uint64_t v149 = (uint64_t)v40;
                TASSIGN(v148, v149);
                // pto: %53
                int64_t v150 = (int64_t)((uint64_t)k147 * (uint64_t)v45);
                // pto: %53
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v151;
                // pto: %53
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v152 = v151;
                // pto: %53
                uint64_t v153 = (uint64_t)((int64_t)((uint64_t)v150 + (uint64_t)v40));
                TASSIGN(v152, v153);
                // pto: %gather_idx_row
                Tile<
                    TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v154 = Tile<
                        TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                        CompactMode::Null>(v26, v25);
                // pto: %gather_idx_row
                uint64_t v155 = (uint64_t)v41;
                TASSIGN(v154, v155);
                // pto: %54
                Tile<
                    TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v156;
                // pto: %54
                Tile<
                    TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v157 = v156;
                // pto: %54
                uint64_t v158 = (uint64_t)v150;
                TASSIGN(v157, v158);
                // pto: %gather_row_tmp
                Tile<
                    TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v159 = Tile<
                        TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                        CompactMode::Null>(v26, v25);
                // pto: %gather_row_tmp
                uint64_t v160 = (uint64_t)v34;
                TASSIGN(v159, v160);
                // pto: %gather_row
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v161 = Tile<
                        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                        CompactMode::Null>(v26, v25);
                // pto: %gather_row
                uint64_t v162 = (uint64_t)v32;
                TASSIGN(v161, v162);
                pipe_barrier(PIPE_V);
                TGATHER(v161, v152, v157, v159);
                // pto: %assemble_view
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v163;
                // pto: %assemble_view
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v164 = v163;
                // pto: %assemble_view
                uint64_t v165 = (uint64_t)((int64_t)((uint64_t)v150 + (uint64_t)v36));
                TASSIGN(v164, v165);
                pipe_barrier(PIPE_V);
                TMOV(v164, v161);
            }
            // pto: %q_rope_swapped_inline1732_inline12405__tile
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v166 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %q_rope_swapped_inline1732_inline12405__tile
            uint64_t v167 = (uint64_t)v36;
            TASSIGN(v166, v167);
            // pto: %q_rope_base_inline1813_inline12411__tile
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v168 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %q_rope_base_inline1813_inline12411__tile
            uint64_t v169 = (uint64_t)v40;
            TASSIGN(v168, v169);
            pipe_barrier(PIPE_V);
            TMUL(v168, v143, v63);
            // pto: %q_rope_delta_inline1680_inline12419__tile
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v170 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %q_rope_delta_inline1680_inline12419__tile
            uint64_t v171 = (uint64_t)v36;
            TASSIGN(v170, v171);
            TMUL(v170, v166, v68);
            // pto: %q_rope_rot_inline1816_inline12550__tile
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v172 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %q_rope_rot_inline1816_inline12550__tile
            uint64_t v173 = (uint64_t)v40;
            TASSIGN(v172, v173);
            pipe_barrier(PIPE_V);
            TADD(v172, v168, v170);
            // pto: %q_rope_bf16_inline1760_inline12493__tile
            Tile<
                TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v174 = Tile<
                    TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %q_rope_bf16_inline1760_inline12493__tile
            uint64_t v175 = (uint64_t)v40;
            TASSIGN(v174, v175);
            pipe_barrier(PIPE_V);
            TCVT(v174, v172, v14, v15);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
            // pto: %q_flat_inline1694_inline12396__iter_v3_pview
            pto::Shape<1, 1, 1, 8, 448> v176 = pto::Shape<1, 1, 1, 8, 448>();
            // pto: %q_flat_inline1694_inline12396__iter_v3_pview
            pto::Stride<262144, 262144, 262144, 32768, 1> v177 = pto::Stride<262144, 262144, 262144, 32768, 1>();
            // pto: %q_flat_inline1694_inline12396__iter_v3_pview
            GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 8, 448>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>
                v178 = GlobalTensor<
                    bfloat16_t, pto::Shape<1, 1, 1, 8, 448>, pto::Stride<262144, 262144, 262144, 32768, 1>,
                    pto::Layout::ND>(v1 + ((v41 + v56 * v17) + v83), v176, v177);
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
            pipe_barrier(PIPE_MTE3);
            TSTORE(v178, v136);
            // pto: %59
            int64_t v179 = (int64_t)((uint64_t)v79 + (uint64_t)v18);
            // pto: %q_flat_inline1694_inline12396__tile_pview
            pto::Shape<1, 1, 1, 8, 64> v180 = pto::Shape<1, 1, 1, 8, 64>();
            // pto: %q_flat_inline1694_inline12396__tile_pview
            pto::Stride<262144, 262144, 262144, 32768, 1> v181 = pto::Stride<262144, 262144, 262144, 32768, 1>();
            // pto: %q_flat_inline1694_inline12396__tile_pview, %60
            GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>
                v182 = GlobalTensor<
                    bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<262144, 262144, 262144, 32768, 1>,
                    pto::Layout::ND>(v1 + ((v41 + v56 * v17) + (v179 < v41 ? v41 : v179)), v180, v181);
            pipe_barrier(PIPE_MTE3);
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
            TSTORE(v182, v174);
            set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
            // pto: %3
            Tile<
                TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v183 = Tile<
                    TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v21);
            // pto: %3
            uint64_t v184 = (uint64_t)v37;
            TASSIGN(v183, v184);
            // pto: %4
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v185 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %4
            uint64_t v186 = (uint64_t)v38;
            TASSIGN(v185, v186);
            wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
            TCVT(v185, v92, v16, v15);
            // pto: %5
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v187 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %5
            uint64_t v188 = (uint64_t)v38;
            TASSIGN(v187, v188);
            pipe_barrier(PIPE_V);
            TROWEXPANDMUL(v187, v185, v54);
            // pto: %6
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v189 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %6
            uint64_t v190 = (uint64_t)v38;
            TASSIGN(v189, v190);
            pipe_barrier(PIPE_V);
            wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
            TCOLEXPANDMUL(v189, v187, v183);
            // pto: %7
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v191 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %7
            uint64_t v192 = (uint64_t)v37;
            TASSIGN(v191, v192);
            pipe_barrier(PIPE_V);
            TMUL(v191, v189, v189);
            // pto: %8
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v193 = Tile<
                    TileType::Vec, float, 8, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v21);
            // pto: %8
            uint64_t v194 = (uint64_t)v31;
            TASSIGN(v193, v194);
            // pto: %9
            Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v195 = Tile<
                    TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v26);
            // pto: %9
            uint64_t v196 = (uint64_t)v30;
            TASSIGN(v195, v196);
            pipe_barrier(PIPE_V);
            TROWSUM(v195, v191, v193);
            // pto: %10
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v197 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %10
            uint64_t v198 = (uint64_t)v30;
            TASSIGN(v197, v198);
            // pto: %11
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v199 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %11
            uint64_t v200 = (uint64_t)v37;
            TASSIGN(v199, v200);
            pipe_barrier(PIPE_V);
            TMULS(v199, v197, v20);
            // pto: %12
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v201 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %12
            uint64_t v202 = (uint64_t)v37;
            TASSIGN(v201, v202);
            pipe_barrier(PIPE_V);
            TADDS(v201, v199, v19);
            // pto: %13
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v203 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %13
            uint64_t v204 = (uint64_t)v31;
            TASSIGN(v203, v204);
            // pto: %14
            Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v205 = Tile<
                    TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v26, v23);
            // pto: %14
            uint64_t v206 = (uint64_t)v29;
            TASSIGN(v205, v206);
            pipe_barrier(PIPE_V);
            TRSQRT(v205, v201, v203);
            // pto: %15
            Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v207 = Tile<
                    TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v26);
            // pto: %15
            uint64_t v208 = (uint64_t)v29;
            TASSIGN(v207, v208);
            // pto: %16
            Tile<
                TileType::Vec, float, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v209 = Tile<
                    TileType::Vec, float, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v18);
            // pto: %16
            uint64_t v210 = (uint64_t)v38;
            TASSIGN(v209, v210);
            // pto: %61
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, 8, 448, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v211;
            // pto: %61
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, 8, 448, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v212 = v211;
            // pto: %61
            uint64_t v213 = (uint64_t)v38;
            TASSIGN(v212, v213);
            // pto: %17
            Tile<
                TileType::Vec, float, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v214 = Tile<
                    TileType::Vec, float, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v18);
            // pto: %17
            uint64_t v215 = (uint64_t)v37;
            TASSIGN(v214, v215);
            pipe_barrier(PIPE_V);
            TROWEXPANDMUL(v214, v212, v207);
            // pto: %18
            Tile<
                TileType::Vec, bfloat16_t, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v216 = Tile<
                    TileType::Vec, bfloat16_t, 8, 448, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v18);
            // pto: %18
            uint64_t v217 = (uint64_t)v37;
            TASSIGN(v216, v217);
            pipe_barrier(PIPE_V);
            TCVT(v216, v214, v14, v15);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
            // pto: %19
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v218 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %19
            uint64_t v219 = (uint64_t)v28;
            TASSIGN(v218, v219);
            // pto: %62
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v220;
            // pto: %62
            Tile<
                TileType::Vec, float, 8, 512, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v221 = v220;
            // pto: %62
            uint64_t v222 = (uint64_t)v28;
            TASSIGN(v221, v222);
            // pto: %20
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v223 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %20
            uint64_t v224 = (uint64_t)v38;
            TASSIGN(v223, v224);
            TROWEXPANDMUL(v223, v221, v207);
            // pto: %21
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v225 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %21
            uint64_t v226 = (uint64_t)v31;
            TASSIGN(v225, v226);
            for (int64_t k227 = v41; k227 < v23; k227 += v26) {
                // pto: %22
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v228 = Tile<
                        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                        CompactMode::Null>(v26, v25);
                // pto: %22
                uint64_t v229 = (uint64_t)v38;
                TASSIGN(v228, v229);
                // pto: %64
                int64_t v230 = (int64_t)((uint64_t)k227 * (uint64_t)v45);
                // pto: %64
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v231;
                // pto: %64
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v232 = v231;
                // pto: %64
                uint64_t v233 = (uint64_t)((int64_t)((uint64_t)v230 + (uint64_t)v38));
                TASSIGN(v232, v233);
                // pto: %23
                Tile<
                    TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v234 = Tile<
                        TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                        CompactMode::Null>(v26, v25);
                // pto: %23
                uint64_t v235 = (uint64_t)v41;
                TASSIGN(v234, v235);
                // pto: %65
                Tile<
                    TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v236;
                // pto: %65
                Tile<
                    TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v237 = v236;
                // pto: %65
                uint64_t v238 = (uint64_t)v230;
                TASSIGN(v237, v238);
                // pto: %24
                Tile<
                    TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v239 = Tile<
                        TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                        CompactMode::Null>(v26, v25);
                // pto: %24
                uint64_t v240 = (uint64_t)v29;
                TASSIGN(v239, v240);
                // pto: %25
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v241 = Tile<
                        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                        CompactMode::Null>(v26, v25);
                // pto: %25
                uint64_t v242 = (uint64_t)v27;
                TASSIGN(v241, v242);
                pipe_barrier(PIPE_V);
                TGATHER(v241, v232, v237, v239);
                // pto: %66
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v243;
                // pto: %66
                Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>
                    v244 = v243;
                // pto: %66
                uint64_t v245 = (uint64_t)((int64_t)((uint64_t)v230 + (uint64_t)v31));
                TASSIGN(v244, v245);
                pipe_barrier(PIPE_V);
                TMOV(v244, v241);
            }
            // pto: %27
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v246 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %27
            uint64_t v247 = (uint64_t)v31;
            TASSIGN(v246, v247);
            // pto: %28
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v248 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %28
            uint64_t v249 = (uint64_t)v38;
            TASSIGN(v248, v249);
            pipe_barrier(PIPE_V);
            TMUL(v248, v223, v63);
            // pto: %29
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v250 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %29
            uint64_t v251 = (uint64_t)v31;
            TASSIGN(v250, v251);
            TMUL(v250, v246, v68);
            // pto: %30
            Tile<
                TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v252 = Tile<
                    TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %30
            uint64_t v253 = (uint64_t)v38;
            TASSIGN(v252, v253);
            pipe_barrier(PIPE_V);
            TADD(v252, v248, v250);
            // pto: %31
            Tile<
                TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v254 = Tile<
                    TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v23, v25);
            // pto: %31
            uint64_t v255 = (uint64_t)v38;
            TASSIGN(v254, v255);
            pipe_barrier(PIPE_V);
            TCVT(v254, v252, v14, v15);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
            // pto: %70
            pto::Shape<1, 1, 1, 8, 448> v256 = pto::Shape<1, 1, 1, 8, 448>();
            // pto: %70
            pto::Stride<262144, 262144, 262144, 32768, 1> v257 = pto::Stride<262144, 262144, 262144, 32768, 1>();
            // pto: %70
            GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 8, 448>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>
                v258 = GlobalTensor<
                    bfloat16_t, pto::Shape<1, 1, 1, 8, 448>, pto::Stride<262144, 262144, 262144, 32768, 1>,
                    pto::Layout::ND>(v1 + ((v41 + v56 * v17) + v94), v256, v257);
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
            pipe_barrier(PIPE_MTE3);
            TSTORE(v258, v216);
            // pto: %73
            int64_t v259 = (int64_t)((uint64_t)v80 + (uint64_t)v18);
            // pto: %75
            pto::Shape<1, 1, 1, 8, 64> v260 = pto::Shape<1, 1, 1, 8, 64>();
            // pto: %75
            pto::Stride<262144, 262144, 262144, 32768, 1> v261 = pto::Stride<262144, 262144, 262144, 32768, 1>();
            // pto: %75, %74
            GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<262144, 262144, 262144, 32768, 1>, pto::Layout::ND>
                v262 = GlobalTensor<
                    bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<262144, 262144, 262144, 32768, 1>,
                    pto::Layout::ND>(v1 + ((v41 + v56 * v17) + (v259 < v41 ? v41 : v259)), v260, v261);
            pipe_barrier(PIPE_MTE3);
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
            TSTORE(v262, v254);
            set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
        }
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    }
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: q_flat_inline1694_inline12396__ssa_v0
    __gm__ ChipTensor *q_flat_inline1694_inline12396__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ bfloat16_t *q_flat_inline1694_inline12396__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(q_flat_inline1694_inline12396__ssa_v0_tensor->buffer.addr) +
        q_flat_inline1694_inline12396__ssa_v0_tensor->start_offset;

    // Unpack tensor: qr_scale_view_inline1722_inline12507__ssa_v1
    __gm__ ChipTensor *qr_scale_view_inline1722_inline12507__ssa_v1_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ float *qr_scale_view_inline1722_inline12507__ssa_v1 =
        reinterpret_cast<__gm__ float *>(qr_scale_view_inline1722_inline12507__ssa_v1_tensor->buffer.addr) +
        qr_scale_view_inline1722_inline12507__ssa_v1_tensor->start_offset;

    // Unpack tensor: q_rope_cos_il_inline1745_inline12266__ssa_v1
    __gm__ ChipTensor *q_rope_cos_il_inline1745_inline12266__ssa_v1_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ float *q_rope_cos_il_inline1745_inline12266__ssa_v1 =
        reinterpret_cast<__gm__ float *>(q_rope_cos_il_inline1745_inline12266__ssa_v1_tensor->buffer.addr) +
        q_rope_cos_il_inline1745_inline12266__ssa_v1_tensor->start_offset;

    // Unpack tensor: q_rope_sin_signed_inline1781_inline12527__ssa_v1
    __gm__ ChipTensor *q_rope_sin_signed_inline1781_inline12527__ssa_v1_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ float *q_rope_sin_signed_inline1781_inline12527__ssa_v1 =
        reinterpret_cast<__gm__ float *>(q_rope_sin_signed_inline1781_inline12527__ssa_v1_tensor->buffer.addr) +
        q_rope_sin_signed_inline1781_inline12527__ssa_v1_tensor->start_offset;

    // Unpack tensor: q_rope_swap_idx_inline1747_inline12787__ssa_v1
    __gm__ ChipTensor *q_rope_swap_idx_inline1747_inline12787__ssa_v1_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[4]);
    __gm__ int32_t *q_rope_swap_idx_inline1747_inline12787__ssa_v1 =
        reinterpret_cast<__gm__ int32_t *>(q_rope_swap_idx_inline1747_inline12787__ssa_v1_tensor->buffer.addr) +
        q_rope_swap_idx_inline1747_inline12787__ssa_v1_tensor->start_offset;

    // Unpack tensor: q_proj_i32_inline1756_inline12345__rv_v2
    __gm__ ChipTensor *q_proj_i32_inline1756_inline12345__rv_v2_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[5]);
    __gm__ int32_t *q_proj_i32_inline1756_inline12345__rv_v2 =
        reinterpret_cast<__gm__ int32_t *>(q_proj_i32_inline1756_inline12345__rv_v2_tensor->buffer.addr) +
        q_proj_i32_inline1756_inline12345__rv_v2_tensor->start_offset;

    // Unpack tensor: wq_b_scale_last_inline574__ssa_v0
    __gm__ ChipTensor *wq_b_scale_last_inline574__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[6]);
    __gm__ float *wq_b_scale_last_inline574__ssa_v0 =
        reinterpret_cast<__gm__ float *>(wq_b_scale_last_inline574__ssa_v0_tensor->buffer.addr) +
        wq_b_scale_last_inline574__ssa_v0_tensor->start_offset;

    // Unpack scalar: tg_inline1711_inline12594__ssa_v0
    union {
        uint64_t u64;
        int64_t val;
    } tg_inline1711_inline12594__ssa_v0_conv;
    tg_inline1711_inline12594__ssa_v0_conv.u64 = args[7];
    int64_t tg_inline1711_inline12594__ssa_v0 = tg_inline1711_inline12594__ssa_v0_conv.val;

    // Unpack scalar: t_dim_inline1772_inline12422__ssa_v0
    union {
        uint64_t u64;
        int64_t val;
    } t_dim_inline1772_inline12422__ssa_v0_conv;
    t_dim_inline1772_inline12422__ssa_v0_conv.u64 = args[8];
    int64_t t_dim_inline1772_inline12422__ssa_v0 = t_dim_inline1772_inline12422__ssa_v0_conv.val;

    // Extract dynamic dim: t_dim_inline1772_inline12422__ssa_v0_1
    int64_t t_dim_inline1772_inline12422__ssa_v0_1 =
        static_cast<int64_t>(q_flat_inline1694_inline12396__ssa_v0_tensor->shapes[0]);

    // Extract dynamic dim: t_matmul_inline1739_inline12394__ssa_v0
    int64_t t_matmul_inline1739_inline12394__ssa_v0 =
        static_cast<int64_t>(q_proj_i32_inline1756_inline12345__rv_v2_tensor->shapes[0]);

    // Forward to ptoas-generated function
    qproj_dequant_rms_nope_rope_3(
        q_flat_inline1694_inline12396__ssa_v0, qr_scale_view_inline1722_inline12507__ssa_v1,
        q_rope_cos_il_inline1745_inline12266__ssa_v1, q_rope_sin_signed_inline1781_inline12527__ssa_v1,
        q_rope_swap_idx_inline1747_inline12787__ssa_v1, q_proj_i32_inline1756_inline12345__rv_v2,
        wq_b_scale_last_inline574__ssa_v0, tg_inline1711_inline12594__ssa_v0, t_dim_inline1772_inline12422__ssa_v0,
        t_dim_inline1772_inline12422__ssa_v0_1, t_matmul_inline1739_inline12394__ssa_v0, __pypto_spmd_block_idx,
        __pypto_spmd_block_num
    );
}
