/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: qr_hadamard_quant_0
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void
qr_hadamard_quant_0(__gm__ float *v1, __gm__ float *v2, __gm__ int8_t *v3, int32_t v4, int32_t v5) {
    RoundMode v6 = RoundMode::CAST_TRUNC;
    RoundMode v7 = RoundMode::CAST_ROUND;
    SaturationMode v8 = SaturationMode::OFF;
    RoundMode v9 = RoundMode::CAST_RINT;
    const float v10 = 127.0f;
    const float v11 = 9.99999974E-5f;
    const int64_t v12 = 64;
    const int64_t v13 = 1;
    const int64_t v14 = 128;
    const int64_t v15 = 49408;
    const int64_t v16 = 256;
    const int64_t v17 = 16640;
    const int64_t v18 = 0;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %idx_inline2020_inline12677__ssa_v0, %4
    int64_t v19 = (int64_t)((uint64_t)((int64_t)v4) * (uint64_t)v12);
    // pto: %qh_amax_inline2034_inline12317__tile
    Tile<
        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v20 = Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v13, v12);
    // pto: %qh_amax_inline2034_inline12317__tile
    uint64_t v21 = (uint64_t)v18;
    TASSIGN(v20, v21);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TEXPANDS(v20, v11);
    for (int64_t i22 = v18; i22 < v14; i22 += v12) {
        // pto: %qh_a_f32_inline1999_inline12724__tile
        Tile<
            TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v23 = Tile<
                TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v12);
        // pto: %qh_a_f32_inline1999_inline12724__tile
        uint64_t v24 = (uint64_t)v17;
        TASSIGN(v23, v24);
        // pto: %qh_acc_gm_inline2006_inline12354__ssa_v1_pview
        pto::Shape<1, 1, 1, 64, 64> v25 = pto::Shape<1, 1, 1, 64, 64>();
        // pto: %qh_acc_gm_inline2006_inline12354__ssa_v1_pview
        pto::Stride<8192, 8192, 8192, 128, 1> v26 = pto::Stride<8192, 8192, 8192, 128, 1>();
        // pto: %5, %qh_acc_gm_inline2006_inline12354__ssa_v1_pview, %6
        GlobalTensor<float, pto::Shape<1, 1, 1, 64, 64>, pto::Stride<8192, 8192, 8192, 128, 1>, pto::Layout::ND> v27 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 64, 64>, pto::Stride<8192, 8192, 8192, 128, 1>, pto::Layout::ND>(
                v1 + ((v18 + (v19 < v18 ? v18 : v19) * v14) + (i22 < v18 ? v18 : i22)), v25, v26
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v23, v27);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %t__tile
        Tile<
            TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v28 = Tile<
                TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v12);
        // pto: %t__tile
        uint64_t v29 = (uint64_t)v16;
        TASSIGN(v28, v29);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        TNEG(v28, v23);
        // pto: %qh_a_abs_inline1976_inline12281__tile
        Tile<
            TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v30 = Tile<
                TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v12);
        // pto: %qh_a_abs_inline1976_inline12281__tile
        uint64_t v31 = (uint64_t)v16;
        TASSIGN(v30, v31);
        pipe_barrier(PIPE_V);
        TMAX(v30, v23, v28);
        // pto: %tmp_tile
        Tile<
            TileType::Vec, float, 64, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v32 = Tile<
                TileType::Vec, float, 64, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v14);
        // pto: %tmp_tile
        uint64_t v33 = (uint64_t)v17;
        TASSIGN(v32, v33);
        // pto: %0
        Tile<
            TileType::Vec, float, 64, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v34 = Tile<
                TileType::Vec, float, 64, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v13);
        // pto: %0
        uint64_t v35 = (uint64_t)v15;
        TASSIGN(v34, v35);
        pipe_barrier(PIPE_V);
        TROWMAX(v34, v30, v32);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        // pto: %qh_a_max_inline2011_inline12797__tile
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v36 = Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %qh_a_max_inline2011_inline12797__tile
        uint64_t v37 = (uint64_t)v15;
        TASSIGN(v36, v37);
        // pto: %1
        Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v38 = Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v13, v12);
        // pto: %1
        uint64_t v39 = (uint64_t)v18;
        TASSIGN(v38, v39);
        pipe_barrier(PIPE_V);
        TMAX(v38, v20, v36);
    }
    // pto: %2
    Tile<
        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v40 = Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v13, v12);
    // pto: %2
    uint64_t v41 = (uint64_t)v17;
    TASSIGN(v40, v41);
    TEXPANDS(v40, v10);
    // pto: %qh_scale_quant_row_inline2008_inline12443__tile
    Tile<
        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v42 = Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v13, v12);
    // pto: %qh_scale_quant_row_inline2008_inline12443__tile
    uint64_t v43 = (uint64_t)v16;
    TASSIGN(v42, v43);
    pipe_barrier(PIPE_V);
    TDIV(v42, v40, v20);
    // pto: %3
    Tile<
        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v44 = Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v13, v12);
    // pto: %3
    uint64_t v45 = (uint64_t)v17;
    TASSIGN(v44, v45);
    pipe_barrier(PIPE_V);
    TRECIP(v44, v42);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    // pto: %qh_scale_dq_inline2022_inline12725__tile
    Tile<
        TileType::Vec, float, 64, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v46 = Tile<
            TileType::Vec, float, 64, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v12, v13);
    // pto: %qh_scale_dq_inline2022_inline12725__tile
    uint64_t v47 = (uint64_t)v17;
    TASSIGN(v46, v47);
    // pto: %7
    int64_t v48 = v19 < v18 ? v18 : v19;
    // pto: %qr_hadamard_scale_dq_inline2018_inline12242__ssa_v0_pview
    pto::Shape<1, 1, 1, 64, 1> v49 = pto::Shape<1, 1, 1, 64, 1>();
    // pto: %qr_hadamard_scale_dq_inline2018_inline12242__ssa_v0_pview
    pto::Stride<64, 64, 64, 1, 512> v50 = pto::Stride<64, 64, 64, 1, 512>();
    // pto: %qr_hadamard_scale_dq_inline2018_inline12242__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 64, 1>, pto::Stride<64, 64, 64, 1, 512>, pto::Layout::DN> v51 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 64, 1>, pto::Stride<64, 64, 64, 1, 512>, pto::Layout::DN>(
            v2 + (v18 + v48), v49, v50
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v51, v46);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    // pto: %qh_scale_quant_inline1964_inline12727__tile
    Tile<
        TileType::Vec, float, 64, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v52 = Tile<
            TileType::Vec, float, 64, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v12, v13);
    // pto: %qh_scale_quant_inline1964_inline12727__tile
    uint64_t v53 = (uint64_t)v16;
    TASSIGN(v52, v53);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    for (int64_t i54 = v18; i54 < v14; i54 += v12) {
        // pto: %qh_q_f32_inline1978_inline12398__tile
        Tile<
            TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v55 = Tile<
                TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v12);
        // pto: %qh_q_f32_inline1978_inline12398__tile
        uint64_t v56 = (uint64_t)v17;
        TASSIGN(v55, v56);
        // pto: %9
        int64_t v57 = i54 < v18 ? v18 : i54;
        // pto: %10
        pto::Shape<1, 1, 1, 64, 64> v58 = pto::Shape<1, 1, 1, 64, 64>();
        // pto: %10
        pto::Stride<8192, 8192, 8192, 128, 1> v59 = pto::Stride<8192, 8192, 8192, 128, 1>();
        // pto: %10
        GlobalTensor<float, pto::Shape<1, 1, 1, 64, 64>, pto::Stride<8192, 8192, 8192, 128, 1>, pto::Layout::ND> v60 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 64, 64>, pto::Stride<8192, 8192, 8192, 128, 1>, pto::Layout::ND>(
                v1 + ((v18 + v48 * v14) + v57), v58, v59
            );
        wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
        TLOAD(v55, v60);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        // pto: %qh_q_scaled_inline2029_inline12632__tile
        Tile<
            TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v61 = Tile<
                TileType::Vec, float, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v12);
        // pto: %qh_q_scaled_inline2029_inline12632__tile
        uint64_t v62 = (uint64_t)v17;
        TASSIGN(v61, v62);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        TROWEXPANDMUL(v61, v55, v52);
        // pto: %qh_q_i32_inline2030_inline12730__tile
        Tile<
            TileType::Vec, int32_t, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v63 = Tile<
                TileType::Vec, int32_t, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v12);
        // pto: %qh_q_i32_inline2030_inline12730__tile
        uint64_t v64 = (uint64_t)v17;
        TASSIGN(v63, v64);
        pipe_barrier(PIPE_V);
        TCVT(v63, v61, v9, v8);
        // pto: %qh_q_half_inline2033_inline12731__tile
        Tile<
            TileType::Vec, half, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v65 = Tile<
                TileType::Vec, half, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v12);
        // pto: %qh_q_half_inline2033_inline12731__tile
        uint64_t v66 = (uint64_t)v17;
        TASSIGN(v65, v66);
        pipe_barrier(PIPE_V);
        TCVT(v65, v63, v7, v8);
        // pto: %qh_i8_inline1977_inline12438__tile
        Tile<
            TileType::Vec, int8_t, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v67 = Tile<
                TileType::Vec, int8_t, 64, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v12, v12);
        // pto: %qh_i8_inline1977_inline12438__tile
        uint64_t v68 = (uint64_t)v17;
        TASSIGN(v67, v68);
        pipe_barrier(PIPE_V);
        TCVT(v67, v65, v6, v8);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        // pto: %qr_hadamard_i8_inline2038_inline12719__iter_v1_pview
        pto::Shape<1, 1, 1, 64, 64> v69 = pto::Shape<1, 1, 1, 64, 64>();
        // pto: %qr_hadamard_i8_inline2038_inline12719__iter_v1_pview
        pto::Stride<8192, 8192, 8192, 128, 1> v70 = pto::Stride<8192, 8192, 8192, 128, 1>();
        // pto: %qr_hadamard_i8_inline2038_inline12719__iter_v1_pview
        GlobalTensor<int8_t, pto::Shape<1, 1, 1, 64, 64>, pto::Stride<8192, 8192, 8192, 128, 1>, pto::Layout::ND> v71 =
            GlobalTensor<int8_t, pto::Shape<1, 1, 1, 64, 64>, pto::Stride<8192, 8192, 8192, 128, 1>, pto::Layout::ND>(
                v3 + ((v18 + v48 * v14) + v57), v69, v70
            );
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        TSTORE(v71, v67);
        set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    }
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: qh_acc_gm_inline2006_inline12354__ssa_v1
    __gm__ ChipTensor *qh_acc_gm_inline2006_inline12354__ssa_v1_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *qh_acc_gm_inline2006_inline12354__ssa_v1 =
        reinterpret_cast<__gm__ float *>(qh_acc_gm_inline2006_inline12354__ssa_v1_tensor->buffer.addr) +
        qh_acc_gm_inline2006_inline12354__ssa_v1_tensor->start_offset;

    // Unpack tensor: qr_hadamard_scale_dq_inline2018_inline12242__ssa_v0
    __gm__ ChipTensor *qr_hadamard_scale_dq_inline2018_inline12242__ssa_v0_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ float *qr_hadamard_scale_dq_inline2018_inline12242__ssa_v0 =
        reinterpret_cast<__gm__ float *>(qr_hadamard_scale_dq_inline2018_inline12242__ssa_v0_tensor->buffer.addr) +
        qr_hadamard_scale_dq_inline2018_inline12242__ssa_v0_tensor->start_offset;

    // Unpack tensor: qr_hadamard_i8_inline2038_inline12719__ssa_v0
    __gm__ ChipTensor *qr_hadamard_i8_inline2038_inline12719__ssa_v0_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ int8_t *qr_hadamard_i8_inline2038_inline12719__ssa_v0 =
        reinterpret_cast<__gm__ int8_t *>(qr_hadamard_i8_inline2038_inline12719__ssa_v0_tensor->buffer.addr) +
        qr_hadamard_i8_inline2038_inline12719__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    qr_hadamard_quant_0(
        qh_acc_gm_inline2006_inline12354__ssa_v1, qr_hadamard_scale_dq_inline2018_inline12242__ssa_v0,
        qr_hadamard_i8_inline2038_inline12719__ssa_v0, __pypto_spmd_block_idx, __pypto_spmd_block_num
    );
}
