/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: quant_0
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void quant_0(__gm__ float *v1, __gm__ int8_t *v2, __gm__ float *v3, int64_t v4, int64_t v5) {
    RoundMode v6 = RoundMode::CAST_TRUNC;
    RoundMode v7 = RoundMode::CAST_ROUND;
    SaturationMode v8 = SaturationMode::OFF;
    RoundMode v9 = RoundMode::CAST_RINT;
    const half v10 = 0.0f;
    const float v11 = 0.00787401571f;
    const float v12 = 127.0f;
    const float v13 = 9.99999974E-5f;
    const int64_t v14 = 1024;
    const int64_t v15 = 1;
    const int64_t v16 = 8;
    const int64_t v17 = 65536;
    const int64_t v18 = 32768;
    const int64_t v19 = 0;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %oc_amax_inline961_inline9497__tile
    Tile<
        TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v20 = Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %oc_amax_inline961_inline9497__tile
    uint64_t v21 = (uint64_t)v19;
    TASSIGN(v20, v21);
    // pto: %0
    int64_t v22 = v4 < v19 ? v19 : v4;
    // pto: %o_r_pad_inline974_inline9624__ssa_v3_pview
    pto::Shape<1, 1, 1, 8, 1024> v23 = pto::Shape<1, 1, 1, 8, 1024>();
    // pto: %o_r_pad_inline974_inline9624__ssa_v3_pview
    pto::Stride<65536, 65536, 65536, 8192, 1> v24 = pto::Stride<65536, 65536, 65536, 8192, 1>();
    // pto: %o_r_pad_inline974_inline9624__ssa_v3_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND> v25 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND>(
            v3 + (v19 + v22), v23, v24
        );
    TLOAD(v20, v25);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    // pto: %g_abs_inline1101_inline9496__tile
    Tile<
        TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v26 = Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %g_abs_inline1101_inline9496__tile
    uint64_t v27 = (uint64_t)v19;
    TASSIGN(v26, v27);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TABS(v26, v20);
    // pto: %tmp_tile
    Tile<
        TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v28 = Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %tmp_tile
    uint64_t v29 = (uint64_t)v18;
    TASSIGN(v28, v29);
    // pto: %g_row_max_inline1027_inline9708__tile
    Tile<
        TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v30 = Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v15);
    // pto: %g_row_max_inline1027_inline9708__tile
    uint64_t v31 = (uint64_t)v17;
    TASSIGN(v30, v31);
    pipe_barrier(PIPE_V);
    TROWMAX(v30, v26, v28);
    // pto: %g_row_max_v1_inline1045_inline9559__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v32 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v16);
    // pto: %g_row_max_v1_inline1045_inline9559__tile
    uint64_t v33 = (uint64_t)v17;
    TASSIGN(v32, v33);
    // pto: %g_amax_floor_inline960_inline9872__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v34 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v16);
    // pto: %g_amax_floor_inline960_inline9872__tile
    uint64_t v35 = (uint64_t)v19;
    TASSIGN(v34, v35);
    pipe_barrier(PIPE_V);
    TEXPANDS(v34, v13);
    // pto: %g_amax_inline1037_inline9570__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v36 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v16);
    // pto: %g_amax_inline1037_inline9570__tile
    uint64_t v37 = (uint64_t)v19;
    TASSIGN(v36, v37);
    pipe_barrier(PIPE_V);
    TMAX(v36, v34, v32);
    // pto: %g_scale_num_inline959_inline9495__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v38 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v16);
    // pto: %g_scale_num_inline959_inline9495__tile
    uint64_t v39 = (uint64_t)v18;
    TASSIGN(v38, v39);
    TEXPANDS(v38, v12);
    // pto: %g_sq_row_inline958_inline9824__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v40 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v16);
    // pto: %g_sq_row_inline958_inline9824__tile
    uint64_t v41 = (uint64_t)v18;
    TASSIGN(v40, v41);
    pipe_barrier(PIPE_V);
    TDIV(v40, v38, v36);
    // pto: %g_scale_dq_inline1084_inline9494__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v42 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v16);
    // pto: %g_scale_dq_inline1084_inline9494__tile
    uint64_t v43 = (uint64_t)v19;
    TASSIGN(v42, v43);
    pipe_barrier(PIPE_V);
    TMULS(v42, v36, v11);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    // pto: %act_scale_dq_inline1008_inline9690__iter_v1_pview
    pto::Shape<1, 1, 1, 1, 8> v44 = pto::Shape<1, 1, 1, 1, 8>();
    // pto: %act_scale_dq_inline1008_inline9690__iter_v1_pview
    pto::Stride<8, 8, 8, 8, 1> v45 = pto::Stride<8, 8, 8, 8, 1>();
    // pto: %1, %act_scale_dq_inline1008_inline9690__iter_v1_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND> v46 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND>(
            v1 + (v19 + (v5 < v19 ? v19 : v5) * v16), v44, v45
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v46, v42);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    // pto: %g_sq_col_inline1082_inline9493__tile
    Tile<
        TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v47 = Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v15);
    // pto: %g_sq_col_inline1082_inline9493__tile
    uint64_t v48 = (uint64_t)v18;
    TASSIGN(v47, v48);
    // pto: %oc_q_inline1097_inline9519__tile
    Tile<
        TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v49 = Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %oc_q_inline1097_inline9519__tile
    uint64_t v50 = (uint64_t)v19;
    TASSIGN(v49, v50);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v49, v25);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    // pto: %oq_scaled_inline957_inline9491__tile
    Tile<
        TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v51 = Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %oq_scaled_inline957_inline9491__tile
    uint64_t v52 = (uint64_t)v19;
    TASSIGN(v51, v52);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TROWEXPANDMUL(v51, v49, v47);
    // pto: %oq_i32_inline956_inline9492__tile
    Tile<
        TileType::Vec, int32_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v53 = Tile<
            TileType::Vec, int32_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %oq_i32_inline956_inline9492__tile
    uint64_t v54 = (uint64_t)v19;
    TASSIGN(v53, v54);
    pipe_barrier(PIPE_V);
    TCVT(v53, v51, v9, v8);
    // pto: %oq_half_inline1026_inline9490__tile
    Tile<
        TileType::Vec, half, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v55 = Tile<
            TileType::Vec, half, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %oq_half_inline1026_inline9490__tile
    uint64_t v56 = (uint64_t)v19;
    TASSIGN(v55, v56);
    pipe_barrier(PIPE_V);
    TCVT(v55, v53, v7, v8);
    // pto: %oq_i8_inline1049_inline9489__tile
    Tile<
        TileType::Vec, int8_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v57 = Tile<
            TileType::Vec, int8_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %oq_i8_inline1049_inline9489__tile
    uint64_t v58 = (uint64_t)v19;
    TASSIGN(v57, v58);
    pipe_barrier(PIPE_V);
    TCVT(v57, v55, v6, v8);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    // pto: %o_r_i8_pad_inline1095_inline9509__iter_v1_pview
    pto::Shape<1, 1, 1, 8, 1024> v59 = pto::Shape<1, 1, 1, 8, 1024>();
    // pto: %o_r_i8_pad_inline1095_inline9509__iter_v1_pview
    pto::Stride<65536, 65536, 65536, 8192, 1> v60 = pto::Stride<65536, 65536, 65536, 8192, 1>();
    // pto: %o_r_i8_pad_inline1095_inline9509__iter_v1_pview
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND> v61 =
        GlobalTensor<int8_t, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND>(
            v2 + (v19 + v22), v59, v60
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    TSTORE(v61, v57);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    // pto: %zero_half_inline955_inline9488__tile
    Tile<
        TileType::Vec, half, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v62 = Tile<
            TileType::Vec, half, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %zero_half_inline955_inline9488__tile
    uint64_t v63 = (uint64_t)v19;
    TASSIGN(v62, v63);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    TEXPANDS(v62, v10);
    // pto: %zero_i8_inline975_inline9487__tile
    Tile<
        TileType::Vec, int8_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v64 = Tile<
            TileType::Vec, int8_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v14);
    // pto: %zero_i8_inline975_inline9487__tile
    uint64_t v65 = (uint64_t)v19;
    TASSIGN(v64, v65);
    pipe_barrier(PIPE_V);
    TCVT(v64, v62, v6, v8);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    // pto: %o_r_i8_pad_inline1095_inline9509__tile_pview
    pto::Shape<1, 1, 1, 8, 1024> v66 = pto::Shape<1, 1, 1, 8, 1024>();
    // pto: %o_r_i8_pad_inline1095_inline9509__tile_pview
    pto::Stride<65536, 65536, 65536, 8192, 1> v67 = pto::Stride<65536, 65536, 65536, 8192, 1>();
    // pto: %o_r_i8_pad_inline1095_inline9509__tile_pview
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND> v68 =
        GlobalTensor<int8_t, pto::Shape<1, 1, 1, 8, 1024>, pto::Stride<65536, 65536, 65536, 8192, 1>, pto::Layout::ND>(
            v2 + (v17 + v22), v66, v67
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    TSTORE(v68, v64);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Unpack tensor: act_scale_dq_inline1008_inline9690__iter_v1
    __gm__ ChipTensor *act_scale_dq_inline1008_inline9690__iter_v1_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *act_scale_dq_inline1008_inline9690__iter_v1 =
        reinterpret_cast<__gm__ float *>(act_scale_dq_inline1008_inline9690__iter_v1_tensor->buffer.addr) +
        act_scale_dq_inline1008_inline9690__iter_v1_tensor->start_offset;

    // Unpack tensor: o_r_i8_pad_inline1095_inline9509__iter_v1
    __gm__ ChipTensor *o_r_i8_pad_inline1095_inline9509__iter_v1_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ int8_t *o_r_i8_pad_inline1095_inline9509__iter_v1 =
        reinterpret_cast<__gm__ int8_t *>(o_r_i8_pad_inline1095_inline9509__iter_v1_tensor->buffer.addr) +
        o_r_i8_pad_inline1095_inline9509__iter_v1_tensor->start_offset;

    // Unpack tensor: o_r_pad_inline974_inline9624__ssa_v3
    __gm__ ChipTensor *o_r_pad_inline974_inline9624__ssa_v3_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ float *o_r_pad_inline974_inline9624__ssa_v3 =
        reinterpret_cast<__gm__ float *>(o_r_pad_inline974_inline9624__ssa_v3_tensor->buffer.addr) +
        o_r_pad_inline974_inline9624__ssa_v3_tensor->start_offset;

    // Unpack scalar: col_g_inline1089_inline9761__ssa_v0
    union {
        uint64_t u64;
        int64_t val;
    } col_g_inline1089_inline9761__ssa_v0_conv;
    col_g_inline1089_inline9761__ssa_v0_conv.u64 = args[3];
    int64_t col_g_inline1089_inline9761__ssa_v0 = col_g_inline1089_inline9761__ssa_v0_conv.val;

    // Unpack scalar: g_inline978_inline9508__idx_v0
    union {
        uint64_t u64;
        int64_t val;
    } g_inline978_inline9508__idx_v0_conv;
    g_inline978_inline9508__idx_v0_conv.u64 = args[4];
    int64_t g_inline978_inline9508__idx_v0 = g_inline978_inline9508__idx_v0_conv.val;

    // Forward to ptoas-generated function
    quant_0(
        act_scale_dq_inline1008_inline9690__iter_v1, o_r_i8_pad_inline1095_inline9509__iter_v1,
        o_r_pad_inline974_inline9624__ssa_v3, col_g_inline1089_inline9761__ssa_v0, g_inline978_inline9508__idx_v0
    );
}
