/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: rope_cs
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void
rope_cs(__gm__ int32_t *v1, __gm__ float *v2, __gm__ float *v3, __gm__ bfloat16_t *v4, __gm__ bfloat16_t *v5) {
    RoundMode v6 = RoundMode::CAST_TRUNC;
    SaturationMode v7 = SaturationMode::OFF;
    RoundMode v8 = RoundMode::CAST_ROUND;
    const int64_t v9 = 2;
    const int64_t v10 = 32;
    const float v11 = 2.0f;
    const float v12 = 0.5f;
    const int32_t v13 = 0;
    const float v14 = 1.0f;
    const int64_t v15 = 8;
    const int64_t v16 = 1;
    const int64_t v17 = 16;
    const int64_t v18 = 1664;
    const int64_t v19 = 1536;
    const int64_t v20 = 1024;
    const int64_t v21 = 1792;
    const int64_t v22 = 0;
    const int64_t v23 = 6912;
    const int64_t v24 = 2816;
    const int64_t v25 = 64;
    const int64_t v26 = 128;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    // pto: %swap_ones_inline1071_inline9018__tile
    Tile<
        TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v27 = Tile<
            TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %swap_ones_inline1071_inline9018__tile
    uint64_t v28 = (uint64_t)v24;
    TASSIGN(v27, v28);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
    TEXPANDS(v27, v14);
    // pto: %swap_range_i32_inline1075_inline8790__tile
    Tile<
        TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v29 = Tile<
            TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v25);
    // pto: %swap_range_i32_inline1075_inline8790__tile
    uint64_t v30 = (uint64_t)v23;
    TASSIGN(v29, v30);
    TCI<Tile<
            TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>,
        int32_t, 0>(v29, v13);
    set_flag(PIPE_S, PIPE_V, EVENT_ID0);
    // pto: %swap_range_inline1079_inline8789__tile
    Tile<
        TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v31 = Tile<
            TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v25);
    // pto: %swap_range_inline1079_inline8789__tile
    uint64_t v32 = (uint64_t)v23;
    TASSIGN(v31, v32);
    wait_flag(PIPE_S, PIPE_V, EVENT_ID0);
    TCVT(v31, v29, v8, v7);
    // pto: %swap_col_inline1116_inline8788__tile
    Tile<
        TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v33 = Tile<
            TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %swap_col_inline1116_inline8788__tile
    uint64_t v34 = (uint64_t)v24;
    TASSIGN(v33, v34);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v33, v27, v31);
    // pto: %swap_half_inline1076_inline8787__tile
    Tile<
        TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v35 = Tile<
            TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %swap_half_inline1076_inline8787__tile
    uint64_t v36 = (uint64_t)v23;
    TASSIGN(v35, v36);
    pipe_barrier(PIPE_V);
    TMULS(v35, v33, v12);
    // pto: %swap_dup_i32_inline1078_inline8786__tile
    Tile<
        TileType::Vec, int32_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v37 = Tile<
            TileType::Vec, int32_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %swap_dup_i32_inline1078_inline8786__tile
    uint64_t v38 = (uint64_t)v23;
    TASSIGN(v37, v38);
    pipe_barrier(PIPE_V);
    TCVT(v37, v35, v6, v7);
    // pto: %swap_dup_f_inline1030_inline8785__tile
    Tile<
        TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v39 = Tile<
            TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %swap_dup_f_inline1030_inline8785__tile
    uint64_t v40 = (uint64_t)v23;
    TASSIGN(v39, v40);
    pipe_barrier(PIPE_V);
    TCVT(v39, v37, v8, v7);
    // pto: %t__tile
    Tile<
        TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v41 = Tile<
            TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %t__tile
    uint64_t v42 = (uint64_t)v23;
    TASSIGN(v41, v42);
    pipe_barrier(PIPE_V);
    TMULS(v41, v39, v11);
    // pto: %swap_lane_inline987_inline8784__tile
    Tile<
        TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v43 = Tile<
            TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %swap_lane_inline987_inline8784__tile
    uint64_t v44 = (uint64_t)v23;
    TASSIGN(v43, v44);
    pipe_barrier(PIPE_V);
    TSUB(v43, v33, v41);
    // pto: %swap_next_inline1119_inline8783__tile
    Tile<
        TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v45 = Tile<
            TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %swap_next_inline1119_inline8783__tile
    uint64_t v46 = (uint64_t)v24;
    TASSIGN(v45, v46);
    pipe_barrier(PIPE_V);
    TADDS(v45, v33, v14);
    // pto: %swap_stride_inline1051_inline9021__tile
    Tile<
        TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v47 = Tile<
            TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %swap_stride_inline1051_inline9021__tile
    uint64_t v48 = (uint64_t)v23;
    TASSIGN(v47, v48);
    TMULS(v47, v43, v11);
    // pto: %swap_idx_f_inline1083_inline8782__tile
    Tile<
        TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v49 = Tile<
            TileType::Vec, float, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %swap_idx_f_inline1083_inline8782__tile
    uint64_t v50 = (uint64_t)v24;
    TASSIGN(v49, v50);
    pipe_barrier(PIPE_V);
    TSUB(v49, v45, v47);
    set_flag(PIPE_V, PIPE_S, EVENT_ID0);
    // pto: %0
    Tile<
        TileType::Vec, int32_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v51 = Tile<
            TileType::Vec, int32_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v17, v25);
    // pto: %0
    uint64_t v52 = (uint64_t)v24;
    TASSIGN(v51, v52);
    pipe_barrier(PIPE_V);
    TCVT(v51, v49, v8, v7);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    // pto: %rope_swap_idx_inline1029_inline8812__ssa_v0_pview
    pto::Shape<1, 1, 1, 16, 64> v53 = pto::Shape<1, 1, 1, 16, 64>();
    // pto: %rope_swap_idx_inline1029_inline8812__ssa_v0_pview
    pto::Stride<1024, 1024, 1024, 64, 1> v54 = pto::Stride<1024, 1024, 1024, 64, 1>();
    // pto: %rope_swap_idx_inline1029_inline8812__ssa_v0_pview
    GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 64>, pto::Stride<1024, 1024, 1024, 64, 1>, pto::Layout::ND> v55 =
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 64>, pto::Stride<1024, 1024, 1024, 64, 1>, pto::Layout::ND>(
            v1, v53, v54
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v55, v51);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    // pto: %cs_ones_inline1090_inline8781__tile
    Tile<
        TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v56 = Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %cs_ones_inline1090_inline8781__tile
    uint64_t v57 = (uint64_t)v24;
    TASSIGN(v56, v57);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    TEXPANDS(v56, v14);
    // pto: %cs_range_i32_inline1086_inline9015__tile
    Tile<
        TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v58 = Tile<
            TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v10);
    // pto: %cs_range_i32_inline1086_inline9015__tile
    uint64_t v59 = (uint64_t)v23;
    TASSIGN(v58, v59);
    wait_flag(PIPE_V, PIPE_S, EVENT_ID0);
    TCI<Tile<
            TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>,
        int32_t, 0>(v58, v13);
    set_flag(PIPE_S, PIPE_V, EVENT_ID1);
    // pto: %cs_range_inline1003_inline8780__tile
    Tile<
        TileType::Vec, float, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v60 = Tile<
            TileType::Vec, float, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v16, v10);
    // pto: %cs_range_inline1003_inline8780__tile
    uint64_t v61 = (uint64_t)v23;
    TASSIGN(v60, v61);
    wait_flag(PIPE_S, PIPE_V, EVENT_ID1);
    TCVT(v60, v58, v8, v7);
    // pto: %cs_col_inline1044_inline8779__tile
    Tile<
        TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v62 = Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %cs_col_inline1044_inline8779__tile
    uint64_t v63 = (uint64_t)v24;
    TASSIGN(v62, v63);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v62, v56, v60);
    // pto: %cs_half_inline1093_inline8778__tile
    Tile<
        TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v64 = Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %cs_half_inline1093_inline8778__tile
    uint64_t v65 = (uint64_t)v23;
    TASSIGN(v64, v65);
    pipe_barrier(PIPE_V);
    TMULS(v64, v62, v12);
    // pto: %cs_dup_i32_inline1059_inline8777__tile
    Tile<
        TileType::Vec, int32_t, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v66 = Tile<
            TileType::Vec, int32_t, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %cs_dup_i32_inline1059_inline8777__tile
    uint64_t v67 = (uint64_t)v23;
    TASSIGN(v66, v67);
    pipe_barrier(PIPE_V);
    TCVT(v66, v64, v6, v7);
    // pto: %cs_dup_f_inline1015_inline8775__tile
    Tile<
        TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v68 = Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %cs_dup_f_inline1015_inline8775__tile
    uint64_t v69 = (uint64_t)v23;
    TASSIGN(v68, v69);
    pipe_barrier(PIPE_V);
    TCVT(v68, v66, v8, v7);
    // pto: %cs_dup_idx_inline1096_inline8773__tile
    Tile<
        TileType::Vec, int32_t, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v70 = Tile<
            TileType::Vec, int32_t, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %cs_dup_idx_inline1096_inline8773__tile
    uint64_t v71 = (uint64_t)v22;
    TASSIGN(v70, v71);
    pipe_barrier(PIPE_V);
    TCVT(v70, v68, v8, v7);
    // pto: %1
    Tile<
        TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v72 = Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %1
    uint64_t v73 = (uint64_t)v23;
    TASSIGN(v72, v73);
    pipe_barrier(PIPE_V);
    TMULS(v72, v68, v11);
    // pto: %cs_lane_inline1087_inline8772__tile
    Tile<
        TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v74 = Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %cs_lane_inline1087_inline8772__tile
    uint64_t v75 = (uint64_t)v24;
    TASSIGN(v74, v75);
    pipe_barrier(PIPE_V);
    TSUB(v74, v62, v72);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    // pto: %2
    Tile<
        TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v76 = Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %2
    uint64_t v77 = (uint64_t)v24;
    TASSIGN(v76, v77);
    pipe_barrier(PIPE_V);
    TMULS(v76, v74, v11);
    // pto: %cs_sign_base_inline1100_inline8771__tile
    Tile<
        TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v78 = Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %cs_sign_base_inline1100_inline8771__tile
    uint64_t v79 = (uint64_t)v24;
    TASSIGN(v78, v79);
    pipe_barrier(PIPE_V);
    TSUBS(v78, v76, v14);
    // pto: %cs_sign_inline1094_inline8774__tile
    Tile<
        TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v80 = Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v15, v10);
    // pto: %cs_sign_inline1094_inline8774__tile
    uint64_t v81 = (uint64_t)v24;
    TASSIGN(v80, v81);
    pipe_barrier(PIPE_V);
    TNEG(v80, v78);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    for (int64_t i82 = v22; i82 < v9; i82 += v16) {
        // pto: %11
        int64_t v83 = (int64_t)((uint64_t)i82 * (uint64_t)v17);
        int64_t v84 = (int64_t)((uint64_t)i82 * (uint64_t)v10);
        // pto: %3
        Tile<
            TileType::Vec, bfloat16_t, 8, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v85 = Tile<
                TileType::Vec, bfloat16_t, 8, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v17);
        // pto: %3
        uint64_t v86 = (uint64_t)v23;
        TASSIGN(v85, v86);
        // pto: %13
        int64_t v87 = v83 < v22 ? v22 : v83;
        // pto: %rope_cos_t_inline8914__rv_v2_pview
        pto::Shape<1, 1, 1, 8, 16> v88 = pto::Shape<1, 1, 1, 8, 16>();
        // pto: %rope_cos_t_inline8914__rv_v2_pview
        pto::Stride<512, 512, 512, 64, 1> v89 = pto::Stride<512, 512, 512, 64, 1>();
        // pto: %rope_cos_t_inline8914__rv_v2_pview
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 16>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v90 =
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 16>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
                v4 + (v22 + v87), v88, v89
            );
        wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        TLOAD(v85, v90);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %cs_cos_inline1091_inline8770__tile
        Tile<
            TileType::Vec, float, 8, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v91 = Tile<
                TileType::Vec, float, 8, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v17);
        // pto: %cs_cos_inline1091_inline8770__tile
        uint64_t v92 = (uint64_t)v21;
        TASSIGN(v91, v92);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
        TCVT(v91, v85, v8, v7);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
        // pto: %4
        Tile<
            TileType::Vec, bfloat16_t, 8, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v93 = Tile<
                TileType::Vec, bfloat16_t, 8, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v17);
        // pto: %4
        uint64_t v94 = (uint64_t)v23;
        TASSIGN(v93, v94);
        // pto: %rope_sin_t_inline8931__rv_v2_pview
        pto::Shape<1, 1, 1, 8, 16> v95 = pto::Shape<1, 1, 1, 8, 16>();
        // pto: %rope_sin_t_inline8931__rv_v2_pview
        pto::Stride<512, 512, 512, 64, 1> v96 = pto::Stride<512, 512, 512, 64, 1>();
        // pto: %rope_sin_t_inline8931__rv_v2_pview
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 16>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v97 =
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 16>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
                v5 + (v22 + v87), v95, v96
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
        TLOAD(v93, v97);
        set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        // pto: %cs_sin_inline1055_inline8949__tile
        Tile<
            TileType::Vec, float, 8, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v98 = Tile<
                TileType::Vec, float, 8, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v17);
        // pto: %cs_sin_inline1055_inline8949__tile
        uint64_t v99 = (uint64_t)v20;
        TASSIGN(v98, v99);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        TCVT(v98, v93, v8, v7);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        // pto: %gather_acc_init
        Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v100 = Tile<
                TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v10);
        // pto: %gather_acc_init
        uint64_t v101 = (uint64_t)v23;
        TASSIGN(v100, v101);
        for (int64_t j102 = v22; j102 < v15; j102 += v16) {
            // pto: %gather_inp_row
            Tile<
                TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v103 = Tile<
                    TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v16, v17);
            // pto: %gather_inp_row
            uint64_t v104 = (uint64_t)v21;
            TASSIGN(v103, v104);
            // pto: %slice_view
            Tile<
                TileType::Vec, float, 1, 16, BLayout::RowMajor, 1, 16, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v105;
            // pto: %slice_view
            Tile<
                TileType::Vec, float, 1, 16, BLayout::RowMajor, 1, 16, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v106 = v105;
            // pto: %slice_view
            uint64_t v107 =
                (uint64_t)((int64_t)((uint64_t)((int64_t)((uint64_t)j102 * (uint64_t)v25)) + (uint64_t)v21));
            TASSIGN(v106, v107);
            // pto: %gather_idx_row
            Tile<
                TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v108 = Tile<
                    TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v16, v10);
            // pto: %gather_idx_row
            uint64_t v109 = (uint64_t)v22;
            TASSIGN(v108, v109);
            // pto: %15
            int64_t v110 = (int64_t)((uint64_t)j102 * (uint64_t)v26);
            // pto: %15
            Tile<
                TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, 1, 32, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v111;
            // pto: %15
            Tile<
                TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, 1, 32, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v112 = v111;
            // pto: %15
            uint64_t v113 = (uint64_t)v110;
            TASSIGN(v112, v113);
            // pto: %gather_row_tmp
            Tile<
                TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v114 = Tile<
                    TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v16, v10);
            // pto: %gather_row_tmp
            uint64_t v115 = (uint64_t)v19;
            TASSIGN(v114, v115);
            // pto: %gather_row
            Tile<
                TileType::Vec, float, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v116 = Tile<
                    TileType::Vec, float, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v16, v10);
            // pto: %gather_row
            uint64_t v117 = (uint64_t)v18;
            TASSIGN(v116, v117);
            pipe_barrier(PIPE_V);
            TGATHER(v116, v106, v112, v114);
            // pto: %assemble_view
            Tile<
                TileType::Vec, float, 1, 32, BLayout::RowMajor, 1, 32, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v118;
            // pto: %assemble_view
            Tile<
                TileType::Vec, float, 1, 32, BLayout::RowMajor, 1, 32, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v119 = v118;
            // pto: %assemble_view
            uint64_t v120 = (uint64_t)((int64_t)((uint64_t)v110 + (uint64_t)v23));
            TASSIGN(v119, v120);
            pipe_barrier(PIPE_V);
            TMOV(v119, v116);
        }
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        // pto: %cs_cos_dup_inline997_inline8932__tile
        Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v121 = Tile<
                TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v10);
        // pto: %cs_cos_dup_inline997_inline8932__tile
        uint64_t v122 = (uint64_t)v23;
        TASSIGN(v121, v122);
        // pto: %5
        Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v123 = Tile<
                TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v10);
        // pto: %5
        uint64_t v124 = (uint64_t)v21;
        TASSIGN(v123, v124);
        for (int64_t j125 = v22; j125 < v15; j125 += v16) {
            // pto: %6
            Tile<
                TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v126 = Tile<
                    TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v16, v17);
            // pto: %6
            uint64_t v127 = (uint64_t)v20;
            TASSIGN(v126, v127);
            // pto: %17
            Tile<
                TileType::Vec, float, 1, 16, BLayout::RowMajor, 1, 16, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v128;
            // pto: %17
            Tile<
                TileType::Vec, float, 1, 16, BLayout::RowMajor, 1, 16, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v129 = v128;
            // pto: %17
            uint64_t v130 =
                (uint64_t)((int64_t)((uint64_t)((int64_t)((uint64_t)j125 * (uint64_t)v25)) + (uint64_t)v20));
            TASSIGN(v129, v130);
            // pto: %7
            Tile<
                TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v131 = Tile<
                    TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v16, v10);
            // pto: %7
            uint64_t v132 = (uint64_t)v22;
            TASSIGN(v131, v132);
            // pto: %18
            int64_t v133 = (int64_t)((uint64_t)j125 * (uint64_t)v26);
            // pto: %18
            Tile<
                TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, 1, 32, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v134;
            // pto: %18
            Tile<
                TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, 1, 32, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v135 = v134;
            // pto: %18
            uint64_t v136 = (uint64_t)v133;
            TASSIGN(v135, v136);
            // pto: %8
            Tile<
                TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v137 = Tile<
                    TileType::Vec, int32_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v16, v10);
            // pto: %8
            uint64_t v138 = (uint64_t)v19;
            TASSIGN(v137, v138);
            // pto: %9
            Tile<
                TileType::Vec, float, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v139 = Tile<
                    TileType::Vec, float, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v16, v10);
            // pto: %9
            uint64_t v140 = (uint64_t)v18;
            TASSIGN(v139, v140);
            pipe_barrier(PIPE_V);
            TGATHER(v139, v129, v135, v137);
            // pto: %19
            Tile<
                TileType::Vec, float, 1, 32, BLayout::RowMajor, 1, 32, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v141;
            // pto: %19
            Tile<
                TileType::Vec, float, 1, 32, BLayout::RowMajor, 1, 32, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v142 = v141;
            // pto: %19
            uint64_t v143 = (uint64_t)((int64_t)((uint64_t)v133 + (uint64_t)v21));
            TASSIGN(v142, v143);
            pipe_barrier(PIPE_V);
            TMOV(v142, v139);
        }
        // pto: %cs_sin_dup_inline1104_inline8769__tile
        Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v144 = Tile<
                TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v10);
        // pto: %cs_sin_dup_inline1104_inline8769__tile
        uint64_t v145 = (uint64_t)v21;
        TASSIGN(v144, v145);
        // pto: %cs_sin_signed_inline1105_inline8983__tile
        Tile<
            TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v146 = Tile<
                TileType::Vec, float, 8, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v15, v10);
        // pto: %cs_sin_signed_inline1105_inline8983__tile
        uint64_t v147 = (uint64_t)v21;
        TASSIGN(v146, v147);
        pipe_barrier(PIPE_V);
        TMUL(v146, v144, v80);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
        // pto: %20
        int64_t v148 = v84 < v22 ? v22 : v84;
        // pto: %rope_cos_il_inline972_inline8894__iter_v1_pview
        pto::Shape<1, 1, 1, 8, 32> v149 = pto::Shape<1, 1, 1, 8, 32>();
        // pto: %rope_cos_il_inline972_inline8894__iter_v1_pview
        pto::Stride<512, 512, 512, 64, 1> v150 = pto::Stride<512, 512, 512, 64, 1>();
        // pto: %rope_cos_il_inline972_inline8894__iter_v1_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 32>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v151 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 8, 32>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
                v2 + (v22 + v148), v149, v150
            );
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
        TSTORE(v151, v121);
        set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
        // pto: %rope_sin_signed_inline1066_inline8798__iter_v1_pview
        pto::Shape<1, 1, 1, 8, 32> v152 = pto::Shape<1, 1, 1, 8, 32>();
        // pto: %rope_sin_signed_inline1066_inline8798__iter_v1_pview
        pto::Stride<512, 512, 512, 64, 1> v153 = pto::Stride<512, 512, 512, 64, 1>();
        // pto: %rope_sin_signed_inline1066_inline8798__iter_v1_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 8, 32>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v154 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 8, 32>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(
                v3 + (v22 + v148), v152, v153
            );
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
        TSTORE(v154, v146);
        set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
    }
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Unpack tensor: rope_swap_idx_inline1029_inline8812__ssa_v0
    __gm__ ChipTensor *rope_swap_idx_inline1029_inline8812__ssa_v0_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ int32_t *rope_swap_idx_inline1029_inline8812__ssa_v0 =
        reinterpret_cast<__gm__ int32_t *>(rope_swap_idx_inline1029_inline8812__ssa_v0_tensor->buffer.addr) +
        rope_swap_idx_inline1029_inline8812__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_cos_il_inline972_inline8894__ssa_v0
    __gm__ ChipTensor *rope_cos_il_inline972_inline8894__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ float *rope_cos_il_inline972_inline8894__ssa_v0 =
        reinterpret_cast<__gm__ float *>(rope_cos_il_inline972_inline8894__ssa_v0_tensor->buffer.addr) +
        rope_cos_il_inline972_inline8894__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_sin_signed_inline1066_inline8798__ssa_v0
    __gm__ ChipTensor *rope_sin_signed_inline1066_inline8798__ssa_v0_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ float *rope_sin_signed_inline1066_inline8798__ssa_v0 =
        reinterpret_cast<__gm__ float *>(rope_sin_signed_inline1066_inline8798__ssa_v0_tensor->buffer.addr) +
        rope_sin_signed_inline1066_inline8798__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_cos_t_inline8914__rv_v2
    __gm__ ChipTensor *rope_cos_t_inline8914__rv_v2_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ bfloat16_t *rope_cos_t_inline8914__rv_v2 =
        reinterpret_cast<__gm__ bfloat16_t *>(rope_cos_t_inline8914__rv_v2_tensor->buffer.addr) +
        rope_cos_t_inline8914__rv_v2_tensor->start_offset;

    // Unpack tensor: rope_sin_t_inline8931__rv_v2
    __gm__ ChipTensor *rope_sin_t_inline8931__rv_v2_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[4]);
    __gm__ bfloat16_t *rope_sin_t_inline8931__rv_v2 =
        reinterpret_cast<__gm__ bfloat16_t *>(rope_sin_t_inline8931__rv_v2_tensor->buffer.addr) +
        rope_sin_t_inline8931__rv_v2_tensor->start_offset;

    // Forward to ptoas-generated function
    rope_cs(
        rope_swap_idx_inline1029_inline8812__ssa_v0, rope_cos_il_inline972_inline8894__ssa_v0,
        rope_sin_signed_inline1066_inline8798__ssa_v0, rope_cos_t_inline8914__rv_v2, rope_sin_t_inline8931__rv_v2
    );
}
