/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: sh_gate_up_act_q_1
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ inline void zero_h_tile_i8_padding(__gm__ int8_t *h_tile_i8, int32_t block_idx, int32_t block_num) {
#if defined(__DAV_VEC__)
    constexpr int8_t zero = 0;
    constexpr int64_t rows_per_block = 2;
    constexpr int64_t cols = 2048;
    const int64_t padding_row = static_cast<int64_t>(block_num + block_idx) * rows_per_block;

    Tile<
        TileType::Vec, int8_t, 2, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        zero_tile = Tile<
            TileType::Vec, int8_t, 2, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(rows_per_block, cols);
    TASSIGN(zero_tile, 0);
    TEXPANDS(zero_tile, zero);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);

    pto::Shape<1, 1, 1, 2, 2048> shape = pto::Shape<1, 1, 1, 2, 2048>();
    pto::Stride<4096, 4096, 4096, 2048, 1> stride = pto::Stride<4096, 4096, 4096, 2048, 1>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 2, 2048>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND> output =
        GlobalTensor<int8_t, pto::Shape<1, 1, 1, 2, 2048>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND>(
            h_tile_i8 + padding_row * cols, shape, stride
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(output, zero_tile);
    pipe_barrier(PIPE_MTE3);
#endif  // __DAV_VEC__
}

static __aicore__ void sh_gate_up_act_q_1(
    __gm__ float *v1, __gm__ float *v2, __gm__ int32_t *v3, __gm__ int32_t *v4, __gm__ float *v5, __gm__ float *v6,
    __gm__ float *v7, __gm__ int8_t *v8, int64_t v9, int64_t v10, int32_t v11, int32_t v12
) {
    RoundMode v13 = RoundMode::CAST_TRUNC;
    RoundMode v14 = RoundMode::CAST_ROUND;
    RoundMode v15 = RoundMode::CAST_RINT;
    SaturationMode v16 = SaturationMode::OFF;
    RoundMode v17 = RoundMode::CAST_NONE;
    const float v18 = 0.0f;
    const float v19 = 127.0f;
    const float v20 = 1.0f;
    const float v21 = -10.0f;
    const float v22 = 10.0f;
    const int64_t v23 = 1024;
    const float v24 = 9.99999974E-5f;
    const int64_t v25 = 2;
    const int64_t v26 = 2048;
    const int64_t v27 = 1;
    const int64_t v28 = 8;
    const int64_t v29 = 98304;
    const int64_t v30 = 65536;
    const int64_t v31 = 32768;
    const int64_t v32 = 0;
    const int64_t v33 = 98336;
    const int64_t v34 = 163904;
    const int64_t v35 = 163872;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    zero_h_tile_i8_padding(v8, v11, v12);
    // pto: %row_block_inline2664_inline10978__ssa_v0, %20
    int64_t v36 = (int64_t)((uint64_t)((int64_t)v11) * (uint64_t)v25);
    // pto: %x_scale_inline2668_inline11156__tile
    Tile<
        TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v37 = Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v27);
    // pto: %x_scale_inline2668_inline11156__tile
    uint64_t v38 = (uint64_t)v35;
    TASSIGN(v37, v38);
    // pto: %21
    int64_t v39 = (int64_t)((uint64_t)v9 + (uint64_t)v36);
    // pto: %x_norm_scale_inline11052__ssa_v0_pview
    pto::Shape<1, 1, 1, 2, 1> v40 = pto::Shape<1, 1, 1, 2, 1>();
    // pto: %x_norm_scale_inline11052__ssa_v0_pview
    pto::Stride<2, 2, 2, 1, 8> v41 = pto::Stride<2, 2, 2, 1, 8>();
    // pto: %22, %x_norm_scale_inline11052__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 8>, pto::Layout::DN> v42 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 2, 1>, pto::Stride<2, 2, 2, 1, 8>, pto::Layout::DN>(
            v1 + (v32 + (v39 < v32 ? v32 : v39)), v40, v41
        );
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    TLOAD(v37, v42);
    // pto: %row_amax_inline2670_inline11159__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v43 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v28);
    // pto: %row_amax_inline2670_inline11159__tile
    uint64_t v44 = (uint64_t)v34;
    TASSIGN(v43, v44);
    TEXPANDS(v43, v24);
    for (int64_t i45 = v32; i45 < v25; i45 += v27) {
        // pto: %23
        int64_t v46 = (int64_t)((uint64_t)i45 * (uint64_t)v23);
        // pto: %gate_rows_i32_inline2656_inline11166__tile
        Tile<
            TileType::Vec, int32_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v47 = Tile<
                TileType::Vec, int32_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %gate_rows_i32_inline2656_inline11166__tile
        uint64_t v48 = (uint64_t)v33;
        TASSIGN(v47, v48);
        // pto: %24
        int64_t v49 = v36 < v32 ? v32 : v36;
        // pto: %25
        int64_t v50 = v46 < v32 ? v32 : v46;
        // pto: %gate_i32_inline2662_inline11084__ssa_v1_pview
        pto::Shape<1, 1, 1, 2, 1024> v51 = pto::Shape<1, 1, 1, 2, 1024>();
        // pto: %gate_i32_inline2662_inline11084__ssa_v1_pview
        pto::Stride<4096, 4096, 4096, 2048, 1> v52 = pto::Stride<4096, 4096, 4096, 2048, 1>();
        // pto: %gate_i32_inline2662_inline11084__ssa_v1_pview
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1024>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND>
            v53 = GlobalTensor<
                int32_t, pto::Shape<1, 1, 1, 2, 1024>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND>(
                v3 + ((v32 + v49 * v26) + v50), v51, v52
            );
        wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v47, v53);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %up_rows_i32_inline2677_inline11168__tile
        Tile<
            TileType::Vec, int32_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v54 = Tile<
                TileType::Vec, int32_t, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %up_rows_i32_inline2677_inline11168__tile
        uint64_t v55 = (uint64_t)v32;
        TASSIGN(v54, v55);
        // pto: %up_i32_inline2654_inline11075__ssa_v1_pview
        pto::Shape<1, 1, 1, 2, 1024> v56 = pto::Shape<1, 1, 1, 2, 1024>();
        // pto: %up_i32_inline2654_inline11075__ssa_v1_pview
        pto::Stride<4096, 4096, 4096, 2048, 1> v57 = pto::Stride<4096, 4096, 4096, 2048, 1>();
        // pto: %up_i32_inline2654_inline11075__ssa_v1_pview
        GlobalTensor<int32_t, pto::Shape<1, 1, 1, 2, 1024>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND>
            v58 = GlobalTensor<
                int32_t, pto::Shape<1, 1, 1, 2, 1024>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND>(
                v4 + ((v32 + v49 * v26) + v50), v56, v57
            );
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        TLOAD(v54, v58);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        // pto: %t__tile
        Tile<
            TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v59 = Tile<
                TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v23);
        // pto: %t__tile
        uint64_t v60 = (uint64_t)v31;
        TASSIGN(v59, v60);
        // pto: %shared_w1_scale_csa_inline531__ssa_v0_pview
        pto::Shape<1, 1, 1, 1, 1024> v61 = pto::Shape<1, 1, 1, 1, 1024>();
        // pto: %shared_w1_scale_csa_inline531__ssa_v0_pview
        pto::Stride<1024, 1024, 1024, 1024, 1> v62 = pto::Stride<1024, 1024, 1024, 1024, 1>();
        // pto: %shared_w1_scale_csa_inline531__ssa_v0_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 1024>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND> v63 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 1, 1024>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND>(
                v5 + (v32 + v50), v61, v62
            );
        TLOAD(v59, v63);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        // pto: %0
        Tile<
            TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v64 = Tile<
                TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v23);
        // pto: %0
        uint64_t v65 = (uint64_t)v30;
        TASSIGN(v64, v65);
        // pto: %shared_w3_scale_csa_inline578__ssa_v0_pview
        pto::Shape<1, 1, 1, 1, 1024> v66 = pto::Shape<1, 1, 1, 1, 1024>();
        // pto: %shared_w3_scale_csa_inline578__ssa_v0_pview
        pto::Stride<1024, 1024, 1024, 1024, 1> v67 = pto::Stride<1024, 1024, 1024, 1024, 1>();
        // pto: %shared_w3_scale_csa_inline578__ssa_v0_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 1024>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND> v68 =
            GlobalTensor<float, pto::Shape<1, 1, 1, 1, 1024>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND>(
                v6 + (v32 + v50), v66, v67
            );
        TLOAD(v64, v68);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        // pto: %w1_scale_inline2648_inline11170__tile
        Tile<
            TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v69 = Tile<
                TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v23);
        // pto: %w1_scale_inline2648_inline11170__tile
        uint64_t v70 = (uint64_t)v31;
        TASSIGN(v69, v70);
        // pto: %w3_scale_inline2651_inline11172__tile
        Tile<
            TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v71 = Tile<
                TileType::Vec, float, 1, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v23);
        // pto: %w3_scale_inline2651_inline11172__tile
        uint64_t v72 = (uint64_t)v30;
        TASSIGN(v71, v72);
        // pto: %gate_fp32_inline2678_inline11173__tile
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v73 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %gate_fp32_inline2678_inline11173__tile
        uint64_t v74 = (uint64_t)v33;
        TASSIGN(v73, v74);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        TCVT(v73, v47, v17, v16);
        // pto: %up_fp32_inline2637_inline11175__tile
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v75 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %up_fp32_inline2637_inline11175__tile
        uint64_t v76 = (uint64_t)v32;
        TASSIGN(v75, v76);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        TCVT(v75, v54, v17, v16);
        // pto: %1
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v77 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %1
        uint64_t v78 = (uint64_t)v33;
        TASSIGN(v77, v78);
        pipe_barrier(PIPE_V);
        TROWEXPANDMUL(v77, v73, v37);
        // pto: %gate_fp32_v1_inline2666_inline11177__tile
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v79 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %gate_fp32_v1_inline2666_inline11177__tile
        uint64_t v80 = (uint64_t)v33;
        TASSIGN(v79, v80);
        pipe_barrier(PIPE_V);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
        TCOLEXPANDMUL(v79, v77, v69);
        // pto: %2
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v81 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %2
        uint64_t v82 = (uint64_t)v32;
        TASSIGN(v81, v82);
        TROWEXPANDMUL(v81, v75, v37);
        // pto: %up_fp32_v1_inline2675_inline11180__tile
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v83 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %up_fp32_v1_inline2675_inline11180__tile
        uint64_t v84 = (uint64_t)v32;
        TASSIGN(v83, v84);
        pipe_barrier(PIPE_V);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
        TCOLEXPANDMUL(v83, v81, v71);
        // pto: %3
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v85 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %3
        uint64_t v86 = (uint64_t)v33;
        TASSIGN(v85, v86);
        TMINS(v85, v79, v22);
        // pto: %4
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v87 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %4
        uint64_t v88 = (uint64_t)v32;
        TASSIGN(v87, v88);
        pipe_barrier(PIPE_V);
        TMINS(v87, v83, v22);
        // pto: %5
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v89 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %5
        uint64_t v90 = (uint64_t)v32;
        TASSIGN(v89, v90);
        pipe_barrier(PIPE_V);
        TMAXS(v89, v87, v21);
        // pto: %6
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v91 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %6
        uint64_t v92 = (uint64_t)v31;
        TASSIGN(v91, v92);
        TNEG(v91, v85);
        // pto: %7
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v93 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %7
        uint64_t v94 = (uint64_t)v31;
        TASSIGN(v93, v94);
        pipe_barrier(PIPE_V);
        TEXP(v93, v91);
        // pto: %8
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v95 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %8
        uint64_t v96 = (uint64_t)v31;
        TASSIGN(v95, v96);
        pipe_barrier(PIPE_V);
        TADDS(v95, v93, v20);
        // pto: %sigmoid_inline2669_inline11088__tile
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v97 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %sigmoid_inline2669_inline11088__tile
        uint64_t v98 = (uint64_t)v30;
        TASSIGN(v97, v98);
        pipe_barrier(PIPE_V);
        TRECIP(v97, v95);
        // pto: %9
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v99 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %9
        uint64_t v100 = (uint64_t)v33;
        TASSIGN(v99, v100);
        pipe_barrier(PIPE_V);
        TMUL(v99, v85, v97);
        // pto: %gated_inline2634_inline11184__tile
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v101 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %gated_inline2634_inline11184__tile
        uint64_t v102 = (uint64_t)v33;
        TASSIGN(v101, v102);
        pipe_barrier(PIPE_V);
        TMUL(v101, v99, v89);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        // pto: %10
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v103 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %10
        uint64_t v104 = (uint64_t)v32;
        TASSIGN(v103, v104);
        pipe_barrier(PIPE_V);
        TABS(v103, v101);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        // pto: %tmp_tile
        Tile<
            TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v105 = Tile<
                TileType::Vec, float, 8, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v28, v23);
        // pto: %tmp_tile
        uint64_t v106 = (uint64_t)v31;
        TASSIGN(v105, v106);
        // pto: %11
        Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v107 = Tile<
                TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v27);
        // pto: %11
        uint64_t v108 = (uint64_t)v29;
        TASSIGN(v107, v108);
        pipe_barrier(PIPE_V);
        TROWMAX(v107, v103, v105);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        // pto: %chunk_amax_inline2653_inline11056__tile
        Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v109 = Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v25);
        // pto: %chunk_amax_inline2653_inline11056__tile
        uint64_t v110 = (uint64_t)v29;
        TASSIGN(v109, v110);
        // pto: %12
        Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v111 = Tile<
                TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v27, v28);
        // pto: %12
        uint64_t v112 = (uint64_t)v34;
        TASSIGN(v111, v112);
        pipe_barrier(PIPE_V);
        TMAX(v111, v43, v109);
        // pto: %13
        Tile<
            TileType::Vec, float, 2, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v113 = Tile<
                TileType::Vec, float, 2, 1024, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>(v25, v23);
        // pto: %13
        uint64_t v114 = (uint64_t)v33;
        TASSIGN(v113, v114);
        // pto: %slice_view
        Tile<
            TileType::Vec, float, 2, 1024, BLayout::RowMajor, 2, 1024, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v115;
        // pto: %slice_view
        Tile<
            TileType::Vec, float, 2, 1024, BLayout::RowMajor, 2, 1024, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>
            v116 = v115;
        // pto: %slice_view
        uint64_t v117 = (uint64_t)v33;
        TASSIGN(v116, v117);
        // pto: %h_tile_fp32_inline2660_inline11021__iter_v1_pview
        pto::Shape<1, 1, 1, 2, 1024> v118 = pto::Shape<1, 1, 1, 2, 1024>();
        // pto: %h_tile_fp32_inline2660_inline11021__iter_v1_pview
        pto::Stride<4096, 4096, 4096, 2048, 1> v119 = pto::Stride<4096, 4096, 4096, 2048, 1>();
        // pto: %h_tile_fp32_inline2660_inline11021__iter_v1_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 2, 1024>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND>
            v120 = GlobalTensor<
                float, pto::Shape<1, 1, 1, 2, 1024>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND>(
                v2 + ((v32 + v49 * v26) + v50), v118, v119
            );
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        TSTORE(v120, v116);
        set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    }
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    // pto: %14
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v121 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v28);
    // pto: %14
    uint64_t v122 = (uint64_t)v33;
    TASSIGN(v121, v122);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    TEXPANDS(v121, v19);
    // pto: %row_scale_q_inline2633_inline11186__tile
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v123 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v28);
    // pto: %row_scale_q_inline2633_inline11186__tile
    uint64_t v124 = (uint64_t)v32;
    TASSIGN(v123, v124);
    pipe_barrier(PIPE_V);
    TDIV(v123, v121, v43);
    // pto: %row_scale_q_col_inline2632_inline11150__tile
    Tile<
        TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v125 = Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v28, v27);
    // pto: %row_scale_q_col_inline2632_inline11150__tile
    uint64_t v126 = (uint64_t)v32;
    TASSIGN(v125, v126);
    // pto: %15
    Tile<
        TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v127 = Tile<
            TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v27, v28);
    // pto: %15
    uint64_t v128 = (uint64_t)v31;
    TASSIGN(v127, v128);
    pipe_barrier(PIPE_V);
    TRECIP(v127, v123);
    // pto: %row_scale_dq_col_inline2631_inline11234__tile
    Tile<
        TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v129 = Tile<
            TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v28, v27);
    // pto: %row_scale_dq_col_inline2631_inline11234__tile
    uint64_t v130 = (uint64_t)v31;
    TASSIGN(v129, v130);
    // pto: %16
    Tile<
        TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v131 = Tile<
            TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v28, v28);
    // pto: %16
    uint64_t v132 = (uint64_t)v33;
    TASSIGN(v131, v132);
    TEXPANDS(v131, v18);
    // pto: %row_scale_dq_inline2659_inline11146__tile
    Tile<
        TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v133 = Tile<
            TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v28, v28);
    // pto: %row_scale_dq_inline2659_inline11146__tile
    uint64_t v134 = (uint64_t)v33;
    TASSIGN(v133, v134);
    pipe_barrier(PIPE_V);
    TROWEXPAND(v133, v129);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    // pto: %17
    Tile<
        TileType::Vec, float, 2, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v135 = Tile<
            TileType::Vec, float, 2, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v28);
    // pto: %17
    uint64_t v136 = (uint64_t)v33;
    TASSIGN(v135, v136);
    // pto: %32
    Tile<TileType::Vec, float, 2, 8, BLayout::RowMajor, 2, 8, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v137;
    // pto: %32
    Tile<TileType::Vec, float, 2, 8, BLayout::RowMajor, 2, 8, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>
        v138 = v137;
    // pto: %32
    uint64_t v139 = (uint64_t)v33;
    TASSIGN(v138, v139);
    // pto: %33
    int64_t v140 = v36 < v32 ? v32 : v36;
    // pto: %h_tile_scale_dq_inline2676_inline11050__ssa_v0_pview
    pto::Shape<1, 1, 1, 2, 8> v141 = pto::Shape<1, 1, 1, 2, 8>();
    // pto: %h_tile_scale_dq_inline2676_inline11050__ssa_v0_pview
    pto::Stride<16, 16, 16, 8, 1> v142 = pto::Stride<16, 16, 16, 8, 1>();
    // pto: %h_tile_scale_dq_inline2676_inline11050__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 2, 8>, pto::Stride<16, 16, 16, 8, 1>, pto::Layout::ND> v143 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 2, 8>, pto::Stride<16, 16, 16, 8, 1>, pto::Layout::ND>(
            v7 + (v32 + v140 * v28), v141, v142
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    TSTORE(v143, v138);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    // pto: %h_fp32_inline2652_inline11188__tile
    Tile<
        TileType::Vec, float, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v144 = Tile<
            TileType::Vec, float, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %h_fp32_inline2652_inline11188__tile
    uint64_t v145 = (uint64_t)v33;
    TASSIGN(v144, v145);
    // pto: %h_tile_fp32_inline2660_inline11021__rv_v2_pview
    pto::Shape<1, 1, 1, 2, 2048> v146 = pto::Shape<1, 1, 1, 2, 2048>();
    // pto: %h_tile_fp32_inline2660_inline11021__rv_v2_pview
    pto::Stride<4096, 4096, 4096, 2048, 1> v147 = pto::Stride<4096, 4096, 4096, 2048, 1>();
    // pto: %h_tile_fp32_inline2660_inline11021__rv_v2_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 2, 2048>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND> v148 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 2, 2048>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND>(
            v2 + (v32 + v140 * v26), v146, v147
        );
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v144, v148);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
    // pto: %h_scaled_inline2629_inline11040__tile
    Tile<
        TileType::Vec, float, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v149 = Tile<
            TileType::Vec, float, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %h_scaled_inline2629_inline11040__tile
    uint64_t v150 = (uint64_t)v33;
    TASSIGN(v149, v150);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
    TROWEXPANDMUL(v149, v144, v125);
    // pto: %h_i32_inline2674_inline11190__tile
    Tile<
        TileType::Vec, int32_t, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v151 = Tile<
            TileType::Vec, int32_t, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %h_i32_inline2674_inline11190__tile
    uint64_t v152 = (uint64_t)v33;
    TASSIGN(v151, v152);
    pipe_barrier(PIPE_V);
    TCVT(v151, v149, v15, v16);
    // pto: %h_fp16_inline2628_inline11062__tile
    Tile<
        TileType::Vec, half, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v153 = Tile<
            TileType::Vec, half, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %h_fp16_inline2628_inline11062__tile
    uint64_t v154 = (uint64_t)v33;
    TASSIGN(v153, v154);
    pipe_barrier(PIPE_V);
    TCVT(v153, v151, v14, v16);
    // pto: %18
    Tile<
        TileType::Vec, int8_t, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v155 = Tile<
            TileType::Vec, int8_t, 8, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %18
    uint64_t v156 = (uint64_t)v33;
    TASSIGN(v155, v156);
    pipe_barrier(PIPE_V);
    TCVT(v155, v153, v13, v16);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    // pto: %19
    Tile<
        TileType::Vec, int8_t, 2, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v157 = Tile<
            TileType::Vec, int8_t, 2, 2048, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v25, v26);
    // pto: %19
    uint64_t v158 = (uint64_t)v33;
    TASSIGN(v157, v158);
    // pto: %35
    Tile<
        TileType::Vec, int8_t, 2, 2048, BLayout::RowMajor, 2, 2048, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v159;
    // pto: %35
    Tile<
        TileType::Vec, int8_t, 2, 2048, BLayout::RowMajor, 2, 2048, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v160 = v159;
    // pto: %35
    uint64_t v161 = (uint64_t)v33;
    TASSIGN(v160, v161);
    // pto: %h_tile_i8_inline2663_inline10980__ssa_v0_pview
    pto::Shape<1, 1, 1, 2, 2048> v162 = pto::Shape<1, 1, 1, 2, 2048>();
    // pto: %h_tile_i8_inline2663_inline10980__ssa_v0_pview
    pto::Stride<4096, 4096, 4096, 2048, 1> v163 = pto::Stride<4096, 4096, 4096, 2048, 1>();
    // pto: %h_tile_i8_inline2663_inline10980__ssa_v0_pview
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 2, 2048>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND> v164 =
        GlobalTensor<int8_t, pto::Shape<1, 1, 1, 2, 2048>, pto::Stride<4096, 4096, 4096, 2048, 1>, pto::Layout::ND>(
            v8 + (v32 + v140 * v26), v162, v163
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    TSTORE(v164, v160);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: x_norm_scale_inline11052__ssa_v0
    __gm__ ChipTensor *x_norm_scale_inline11052__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ float *x_norm_scale_inline11052__ssa_v0 =
        reinterpret_cast<__gm__ float *>(x_norm_scale_inline11052__ssa_v0_tensor->buffer.addr) +
        x_norm_scale_inline11052__ssa_v0_tensor->start_offset;

    // Unpack tensor: h_tile_fp32_inline2660_inline11021__ssa_v0
    __gm__ ChipTensor *h_tile_fp32_inline2660_inline11021__ssa_v0_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ float *h_tile_fp32_inline2660_inline11021__ssa_v0 =
        reinterpret_cast<__gm__ float *>(h_tile_fp32_inline2660_inline11021__ssa_v0_tensor->buffer.addr) +
        h_tile_fp32_inline2660_inline11021__ssa_v0_tensor->start_offset;

    // Unpack tensor: gate_i32_inline2662_inline11084__ssa_v1
    __gm__ ChipTensor *gate_i32_inline2662_inline11084__ssa_v1_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ int32_t *gate_i32_inline2662_inline11084__ssa_v1 =
        reinterpret_cast<__gm__ int32_t *>(gate_i32_inline2662_inline11084__ssa_v1_tensor->buffer.addr) +
        gate_i32_inline2662_inline11084__ssa_v1_tensor->start_offset;

    // Unpack tensor: up_i32_inline2654_inline11075__ssa_v1
    __gm__ ChipTensor *up_i32_inline2654_inline11075__ssa_v1_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ int32_t *up_i32_inline2654_inline11075__ssa_v1 =
        reinterpret_cast<__gm__ int32_t *>(up_i32_inline2654_inline11075__ssa_v1_tensor->buffer.addr) +
        up_i32_inline2654_inline11075__ssa_v1_tensor->start_offset;

    // Unpack tensor: shared_w1_scale_csa_inline531__ssa_v0
    __gm__ ChipTensor *shared_w1_scale_csa_inline531__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[4]);
    __gm__ float *shared_w1_scale_csa_inline531__ssa_v0 =
        reinterpret_cast<__gm__ float *>(shared_w1_scale_csa_inline531__ssa_v0_tensor->buffer.addr) +
        shared_w1_scale_csa_inline531__ssa_v0_tensor->start_offset;

    // Unpack tensor: shared_w3_scale_csa_inline578__ssa_v0
    __gm__ ChipTensor *shared_w3_scale_csa_inline578__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[5]);
    __gm__ float *shared_w3_scale_csa_inline578__ssa_v0 =
        reinterpret_cast<__gm__ float *>(shared_w3_scale_csa_inline578__ssa_v0_tensor->buffer.addr) +
        shared_w3_scale_csa_inline578__ssa_v0_tensor->start_offset;

    // Unpack tensor: h_tile_scale_dq_inline2676_inline11050__ssa_v0
    __gm__ ChipTensor *h_tile_scale_dq_inline2676_inline11050__ssa_v0_tensor =
        reinterpret_cast<__gm__ ChipTensor *>(args[6]);
    __gm__ float *h_tile_scale_dq_inline2676_inline11050__ssa_v0 =
        reinterpret_cast<__gm__ float *>(h_tile_scale_dq_inline2676_inline11050__ssa_v0_tensor->buffer.addr) +
        h_tile_scale_dq_inline2676_inline11050__ssa_v0_tensor->start_offset;

    // Unpack tensor: h_tile_i8_inline2663_inline10980__ssa_v0
    __gm__ ChipTensor *h_tile_i8_inline2663_inline10980__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[7]);
    __gm__ int8_t *h_tile_i8_inline2663_inline10980__ssa_v0 =
        reinterpret_cast<__gm__ int8_t *>(h_tile_i8_inline2663_inline10980__ssa_v0_tensor->buffer.addr) +
        h_tile_i8_inline2663_inline10980__ssa_v0_tensor->start_offset;

    // Unpack scalar: ts0_inline2658_inline11033__ssa_v0
    union {
        uint64_t u64;
        int64_t val;
    } ts0_inline2658_inline11033__ssa_v0_conv;
    ts0_inline2658_inline11033__ssa_v0_conv.u64 = args[8];
    int64_t ts0_inline2658_inline11033__ssa_v0 = ts0_inline2658_inline11033__ssa_v0_conv.val;

    // Unpack scalar: n0_inline2655_inline11011__ssa_v1
    union {
        uint64_t u64;
        int64_t val;
    } n0_inline2655_inline11011__ssa_v1_conv;
    n0_inline2655_inline11011__ssa_v1_conv.u64 = args[9];
    int64_t n0_inline2655_inline11011__ssa_v1 = n0_inline2655_inline11011__ssa_v1_conv.val;

    // Forward to ptoas-generated function
    sh_gate_up_act_q_1(
        x_norm_scale_inline11052__ssa_v0, h_tile_fp32_inline2660_inline11021__ssa_v0,
        gate_i32_inline2662_inline11084__ssa_v1, up_i32_inline2654_inline11075__ssa_v1,
        shared_w1_scale_csa_inline531__ssa_v0, shared_w3_scale_csa_inline578__ssa_v0,
        h_tile_scale_dq_inline2676_inline11050__ssa_v0, h_tile_i8_inline2663_inline10980__ssa_v0,
        ts0_inline2658_inline11033__ssa_v0, n0_inline2655_inline11011__ssa_v1, __pypto_spmd_block_idx,
        __pypto_spmd_block_num
    );
}
