/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: swa_rope_step
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void swa_rope_step(
    __gm__ bfloat16_t *v1, __gm__ bfloat16_t *v2, __gm__ int32_t *v3, __gm__ bfloat16_t *v4, __gm__ bfloat16_t *v5
) {
    RoundMode v6 = RoundMode::CAST_RINT;
    SaturationMode v7 = SaturationMode::OFF;
    RoundMode v8 = RoundMode::CAST_ROUND;
    const int64_t v9 = 2;
    const int64_t v10 = 4;
    const int64_t v11 = 1;
    const int64_t v12 = 64;
    const int64_t v13 = 256;
    const int64_t v14 = 0;
    const int64_t v15 = 384;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    for (int64_t i16 = v14; i16 < v10; i16 += v11) {
        for (int64_t j17 = v14; j17 < v9; j17 += v11) {
            // pto: %3, %4
            int64_t v18 = (int64_t)((uint64_t)((int64_t)((uint64_t)i16 * (uint64_t)v9)) + (uint64_t)j17);
            // pto: %5
            int32_t v19 = (v3)[v18];
            // pto: %6
            int64_t v20 = (int64_t)v19;
            // pto: %t__tile
            Tile<
                TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v21 = Tile<
                    TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v11, v12);
            // pto: %t__tile
            uint64_t v22 = (uint64_t)v15;
            TASSIGN(v21, v22);
            // pto: %7
            int64_t v23 = v20 < v14 ? v14 : v20;
            // pto: %swa_freqs_cos_inline585__ssa_v0_pview
            pto::Shape<1, 1, 1, 1, 64> v24 = pto::Shape<1, 1, 1, 1, 64>();
            // pto: %swa_freqs_cos_inline585__ssa_v0_pview
            pto::Stride<64, 64, 64, 64, 1> v25 = pto::Stride<64, 64, 64, 64, 1>();
            // pto: %swa_freqs_cos_inline585__ssa_v0_pview
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND> v26 =
                GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND>(
                    v4 + (v14 + v23 * v12), v24, v25
                );
            wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
            TLOAD(v21, v26);
            set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
            // pto: %cos_row_inline8920__tile
            Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v27 = Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v11, v12);
            // pto: %cos_row_inline8920__tile
            uint64_t v28 = (uint64_t)v14;
            TASSIGN(v27, v28);
            wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
            wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
            TCVT(v27, v21, v8, v7);
            // pto: %0
            Tile<
                TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v29 = Tile<
                    TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v11, v12);
            // pto: %0
            uint64_t v30 = (uint64_t)v13;
            TASSIGN(v29, v30);
            // pto: %swa_freqs_sin_inline606__ssa_v0_pview
            pto::Shape<1, 1, 1, 1, 64> v31 = pto::Shape<1, 1, 1, 1, 64>();
            // pto: %swa_freqs_sin_inline606__ssa_v0_pview
            pto::Stride<64, 64, 64, 64, 1> v32 = pto::Stride<64, 64, 64, 64, 1>();
            // pto: %swa_freqs_sin_inline606__ssa_v0_pview
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND> v33 =
                GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND>(
                    v5 + (v14 + v23 * v12), v31, v32
                );
            TLOAD(v29, v33);
            set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
            // pto: %sin_row_inline8954__tile
            Tile<
                TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v34 = Tile<
                    TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v11, v12);
            // pto: %sin_row_inline8954__tile
            uint64_t v35 = (uint64_t)v15;
            TASSIGN(v34, v35);
            wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
            pipe_barrier(PIPE_V);
            TCVT(v34, v29, v8, v7);
            // pto: %1
            Tile<
                TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v36 = Tile<
                    TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v11, v12);
            // pto: %1
            uint64_t v37 = (uint64_t)v14;
            TASSIGN(v36, v37);
            TCVT(v36, v27, v6, v7);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
            // pto: %9
            int64_t v38 = v18 < v14 ? v14 : v18;
            // pto: %rope_cos_t_inline8914__iter_v3_pview
            pto::Shape<1, 1, 1, 1, 64> v39 = pto::Shape<1, 1, 1, 1, 64>();
            // pto: %rope_cos_t_inline8914__iter_v3_pview
            pto::Stride<64, 64, 64, 64, 1> v40 = pto::Stride<64, 64, 64, 64, 1>();
            // pto: %rope_cos_t_inline8914__iter_v3_pview
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND> v41 =
                GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND>(
                    v1 + (v14 + v38 * v12), v39, v40
                );
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
            TSTORE(v41, v36);
            set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
            // pto: %2
            Tile<
                TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                CompactMode::Null>
                v42 = Tile<
                    TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
                    CompactMode::Null>(v11, v12);
            // pto: %2
            uint64_t v43 = (uint64_t)v14;
            TASSIGN(v42, v43);
            wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
            TCVT(v42, v34, v6, v7);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
            set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
            // pto: %rope_sin_t_inline8931__iter_v3_pview
            pto::Shape<1, 1, 1, 1, 64> v44 = pto::Shape<1, 1, 1, 1, 64>();
            // pto: %rope_sin_t_inline8931__iter_v3_pview
            pto::Stride<64, 64, 64, 64, 1> v45 = pto::Stride<64, 64, 64, 64, 1>();
            // pto: %rope_sin_t_inline8931__iter_v3_pview
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND> v46 =
                GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<64, 64, 64, 64, 1>, pto::Layout::ND>(
                    v2 + (v14 + v38 * v12), v44, v45
                );
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
            TSTORE(v46, v42);
            set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
        }
    }
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Unpack tensor: rope_cos_t_inline8914__ssa_v0
    __gm__ ChipTensor *rope_cos_t_inline8914__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ bfloat16_t *rope_cos_t_inline8914__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(rope_cos_t_inline8914__ssa_v0_tensor->buffer.addr) +
        rope_cos_t_inline8914__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_sin_t_inline8931__ssa_v0
    __gm__ ChipTensor *rope_sin_t_inline8931__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ bfloat16_t *rope_sin_t_inline8931__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(rope_sin_t_inline8931__ssa_v0_tensor->buffer.addr) +
        rope_sin_t_inline8931__ssa_v0_tensor->start_offset;

    // Unpack tensor: position_ids__ssa_v0
    __gm__ ChipTensor *position_ids__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ int32_t *position_ids__ssa_v0 =
        reinterpret_cast<__gm__ int32_t *>(position_ids__ssa_v0_tensor->buffer.addr) +
        position_ids__ssa_v0_tensor->start_offset;

    // Unpack tensor: swa_freqs_cos_inline585__ssa_v0
    __gm__ ChipTensor *swa_freqs_cos_inline585__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ bfloat16_t *swa_freqs_cos_inline585__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(swa_freqs_cos_inline585__ssa_v0_tensor->buffer.addr) +
        swa_freqs_cos_inline585__ssa_v0_tensor->start_offset;

    // Unpack tensor: swa_freqs_sin_inline606__ssa_v0
    __gm__ ChipTensor *swa_freqs_sin_inline606__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[4]);
    __gm__ bfloat16_t *swa_freqs_sin_inline606__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(swa_freqs_sin_inline606__ssa_v0_tensor->buffer.addr) +
        swa_freqs_sin_inline606__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    swa_rope_step(
        rope_cos_t_inline8914__ssa_v0, rope_sin_t_inline8931__ssa_v0, position_ids__ssa_v0,
        swa_freqs_cos_inline585__ssa_v0, swa_freqs_sin_inline606__ssa_v0
    );
}
