/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */
// Kernel Function: kv_score_proj_3
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"

#if defined(__CPU_SIM)
// PTOAS v0.50+ emits cache_line_t::ENTIRE_DATA_CACHE / SINGLE_CACHE_LINE as
// scoped identifiers, but the pto-isa cpu_stub.hpp defines them as bare macros
// (#define ENTIRE_DATA_CACHE 0) — which breaks cache_line_t::ENTIRE_DATA_CACHE
// into cache_line_t::0. Undefine the macros and provide proper namespace-scoped
// constexpr constants. The same headers also #define dcci/dsb as macros that
// would expand our own inlines, so undefine + redefine all of them here.
#include <atomic>

// Forward-declare the overloads so the undefs below don't break chained includes.
namespace pypto_sim_detail {
template <typename... Args>
static inline void sim_dcci(Args...);  // defined after the undefs
static inline void sim_dsb(int kind);  // ditto
}  // namespace pypto_sim_detail

// Undefine conflicting macros from pto-isa cpu_stub.hpp / inner_kernel.h
// so our namespace-scoped constants and inline functions are used instead.
#undef ENTIRE_DATA_CACHE
#undef SINGLE_CACHE_LINE
#undef DSB_DDR
#undef dcci
#undef dsb
#undef CACHELINE_OUT

namespace cache_line_t {
constexpr int ENTIRE_DATA_CACHE = 0;
constexpr int SINGLE_CACHE_LINE = 0;
constexpr int CACHELINE_OUT = 0;
}  // namespace cache_line_t
typedef int mem_dsb_t;
#define DSB_DDR 0

static inline void dcci(...) { std::atomic_thread_fence(std::memory_order_seq_cst); }
static inline void dsb(mem_dsb_t) { std::atomic_thread_fence(std::memory_order_seq_cst); }
#endif  // __CPU_SIM

using namespace pto;

// --- ptoas-generated code ---

template <typename ChipTensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(ChipTensor &tensor) -> decltype(tensor.data()) {
    return tensor.data();
}

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
    dcci((__gm__ void *)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void kv_score_proj_3(
    __gm__ bfloat16_t *v1, __gm__ bfloat16_t *v2, __gm__ bfloat16_t *v3, __gm__ float *v4, __gm__ float *v5, int32_t v6,
    int32_t v7
) {
    const int64_t v8 = 256;
    const int64_t v9 = 512;
    const int64_t v10 = 2;
    const int64_t v11 = 32;
    const int64_t v12 = 16;
    const int64_t v13 = 1;
    const int64_t v14 = 4096;
    const int64_t v15 = 8;
    const int64_t v16 = 32768;
    const int64_t v17 = 49152;
    const int64_t v18 = 16384;
    const int64_t v19 = 131072;
    const int64_t v20 = 98304;
    const int64_t v21 = 81920;
    const int64_t v22 = 2048;
    const int64_t v23 = 0;
    using T = float;

#if defined(__DAV_CUBE__)
    // pto: %x_flat_inline15306__ssa_v0_view
    int64_t v24 = v15 * v14;
    // pto: %x_flat_inline15306__ssa_v0_view
    int64_t v25 = v13 * v24;
    // pto: %x_flat_inline15306__ssa_v0_view
    pto::Shape<1, 1, 1, -1, -1> v26 = pto::Shape<1, 1, 1, -1, -1>(v13, v13, v13, v15, v14);
    // pto: %x_flat_inline15306__ssa_v0_view
    pto::Stride<-1, -1, -1, -1, -1> v27 = pto::Stride<-1, -1, -1, -1, -1>(v13 * v25, v25, v24, v14, v13);
    // pto: %x_flat_inline15306__ssa_v0_view
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v28 =
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(
            v1, v26, v27
        );
    // pto: %kv_acc_inline15276__phi_v5
    Tile<
        TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
        CompactMode::Null>
        v29 = Tile<
            TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
            CompactMode::Null>(v12, v11);
    // pto: %kv_acc_inline15276__phi_v5
    uint64_t v30 = (uint64_t)v23;
    TASSIGN(v29, v30);
    // pto: %score_acc_inline15299__phi_v5
    Tile<
        TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
        CompactMode::Null>
        v31 = Tile<
            TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
            CompactMode::Null>(v12, v11);
    // pto: %score_acc_inline15299__phi_v5
    uint64_t v32 = (uint64_t)v22;
    TASSIGN(v31, v32);
    // pto: %idx_inline15287__ssa_v0
    int64_t v33 = (int64_t)v6;
    // pto: %19, %20
    int64_t v34 = (int64_t)((uint64_t)(v33 / v15) * (uint64_t)v12);
    // pto: %21, %22
    int64_t v35 = (int64_t)((uint64_t)(v33 % v15) * (uint64_t)v11);
    // pto: %kv_acc_inline15276__tile
    Tile<
        TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
        CompactMode::Null>
        v36 = Tile<
            TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
            CompactMode::Null>(v12, v11);
    // pto: %kv_acc_inline15276__tile
    uint64_t v37 = (uint64_t)v23;
    TASSIGN(v36, v37);
    // pto: %score_acc_inline15299__tile
    Tile<
        TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
        CompactMode::Null>
        v38 = Tile<
            TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
            CompactMode::Null>(v12, v11);
    // pto: %score_acc_inline15299__tile
    uint64_t v39 = (uint64_t)v22;
    TASSIGN(v38, v39);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
    for (int64_t i40 = v23; i40 < v15; i40 += v10) {
        // pto: %23
        int64_t v41 = (int64_t)((uint64_t)i40 * (uint64_t)v9);
        // pto: %24
        int64_t v42 = (int64_t)((uint64_t)v15 - (uint64_t)v34);
        // pto: %26
        int64_t v43 = (int64_t)((uint64_t)v41 + (uint64_t)v9);
        // pto: %x_tile_inline15284__tile
        Tile<
            TileType::Mat, bfloat16_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
            CompactMode::Null>
            v44 = Tile<
                TileType::Mat, bfloat16_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
                CompactMode::Null>(v42, v9);
        // pto: %x_tile_inline15284__tile
        uint64_t v45 = (uint64_t)v21;
        TASSIGN(v44, v45);
        // pto: %28
        int64_t v46 = v34 < v23 ? v23 : v34;
        // pto: %29
        int64_t v47 = v41 < v23 ? v23 : v41;
        // pto: %x_flat_inline15306__ssa_v0_pview
        __gm__ bfloat16_t *v48 = PTOAS__GLOBAL_TENSOR_DATA(v28);
        // pto: %x_flat_inline15306__ssa_v0_pview
        int64_t v49 = v42 * v14;
        // pto: %x_flat_inline15306__ssa_v0_pview
        int64_t v50 = v13 * v49;
        // pto: %x_flat_inline15306__ssa_v0_pview
        pto::Shape<1, 1, 1, -1, 512> v51 = pto::Shape<1, 1, 1, -1, 512>(v13, v13, v13, v42, v9);
        // pto: %x_flat_inline15306__ssa_v0_pview
        pto::Stride<-1, -1, -1, -1, -1> v52 = pto::Stride<-1, -1, -1, -1, -1>(v13 * v50, v50, v49, v14, v13);
        // pto: %x_flat_inline15306__ssa_v0_pview
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v53 =
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(
                v48 + ((v23 + v46 * v14) + v47 * v13), v51, v52
            );
        wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
        TLOAD(v44, v53);
        // pto: %wkv_tile_inline15298__tile
        Tile<
            TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
            CompactMode::Null>
            v54 = Tile<
                TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
                CompactMode::Null>(v11, v9);
        // pto: %wkv_tile_inline15298__tile
        uint64_t v55 = (uint64_t)v20;
        TASSIGN(v54, v55);
        // pto: %30
        int64_t v56 = v35 < v23 ? v23 : v35;
        // pto: %csa_inner_wkv_last_inline580__ssa_v0_pview
        pto::Shape<1, 1, 1, 32, 512> v57 = pto::Shape<1, 1, 1, 32, 512>();
        // pto: %csa_inner_wkv_last_inline580__ssa_v0_pview
        pto::Stride<131072, 131072, 131072, 4096, 1> v58 = pto::Stride<131072, 131072, 131072, 4096, 1>();
        // pto: %csa_inner_wkv_last_inline580__ssa_v0_pview
        GlobalTensor<
            bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<131072, 131072, 131072, 4096, 1>, pto::Layout::ND>
            v59 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<131072, 131072, 131072, 4096, 1>,
                pto::Layout::ND>(v2 + ((v23 + v56 * v14) + v47), v57, v58);
        TLOAD(v54, v59);
        // pto: %wgate_tile_inline15301__tile
        Tile<
            TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
            CompactMode::Null>
            v60 = Tile<
                TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
                CompactMode::Null>(v11, v9);
        // pto: %wgate_tile_inline15301__tile
        uint64_t v61 = (uint64_t)v19;
        TASSIGN(v60, v61);
        // pto: %csa_inner_wgate_last_inline511__ssa_v0_pview
        pto::Shape<1, 1, 1, 32, 512> v62 = pto::Shape<1, 1, 1, 32, 512>();
        // pto: %csa_inner_wgate_last_inline511__ssa_v0_pview
        pto::Stride<131072, 131072, 131072, 4096, 1> v63 = pto::Stride<131072, 131072, 131072, 4096, 1>();
        // pto: %csa_inner_wgate_last_inline511__ssa_v0_pview
        GlobalTensor<
            bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<131072, 131072, 131072, 4096, 1>, pto::Layout::ND>
            v64 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<131072, 131072, 131072, 4096, 1>,
                pto::Layout::ND>(v3 + ((v23 + v56 * v14) + v47), v62, v63);
        TLOAD(v60, v64);
        set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
        // pto: %0
        Tile<
            TileType::Mat, bfloat16_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
            CompactMode::Null>
            v65 = Tile<
                TileType::Mat, bfloat16_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
                CompactMode::Null>(v42, v9);
        // pto: %0
        uint64_t v66 = (uint64_t)v23;
        TASSIGN(v65, v66);
        // pto: %35
        int64_t v67 = v43 < v23 ? v23 : v43;
        // pto: %36
        __gm__ bfloat16_t *v68 = PTOAS__GLOBAL_TENSOR_DATA(v28);
        // pto: %36
        int64_t v69 = v42 * v14;
        // pto: %36
        int64_t v70 = v13 * v69;
        // pto: %36
        pto::Shape<1, 1, 1, -1, 512> v71 = pto::Shape<1, 1, 1, -1, 512>(v13, v13, v13, v42, v9);
        // pto: %36
        pto::Stride<-1, -1, -1, -1, -1> v72 = pto::Stride<-1, -1, -1, -1, -1>(v13 * v70, v70, v69, v14, v13);
        // pto: %36
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v73 =
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(
                v68 + ((v23 + v46 * v14) + v67 * v13), v71, v72
            );
        wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
        TLOAD(v65, v73);
        set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
        // pto: %1
        Tile<
            TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
            CompactMode::Null>
            v74 = Tile<
                TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
                CompactMode::Null>(v11, v9);
        // pto: %1
        uint64_t v75 = (uint64_t)v18;
        TASSIGN(v74, v75);
        // pto: %39
        pto::Shape<1, 1, 1, 32, 512> v76 = pto::Shape<1, 1, 1, 32, 512>();
        // pto: %39
        pto::Stride<131072, 131072, 131072, 4096, 1> v77 = pto::Stride<131072, 131072, 131072, 4096, 1>();
        // pto: %39
        GlobalTensor<
            bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<131072, 131072, 131072, 4096, 1>, pto::Layout::ND>
            v78 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<131072, 131072, 131072, 4096, 1>,
                pto::Layout::ND>(v2 + ((v23 + v56 * v14) + v67), v76, v77);
        wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
        TLOAD(v74, v78);
        set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
        // pto: %2
        Tile<
            TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
            CompactMode::Null>
            v79 = Tile<
                TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
                CompactMode::Null>(v11, v9);
        // pto: %2
        uint64_t v80 = (uint64_t)v17;
        TASSIGN(v79, v80);
        // pto: %42
        pto::Shape<1, 1, 1, 32, 512> v81 = pto::Shape<1, 1, 1, 32, 512>();
        // pto: %42
        pto::Stride<131072, 131072, 131072, 4096, 1> v82 = pto::Stride<131072, 131072, 131072, 4096, 1>();
        // pto: %42
        GlobalTensor<
            bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<131072, 131072, 131072, 4096, 1>, pto::Layout::ND>
            v83 = GlobalTensor<
                bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<131072, 131072, 131072, 4096, 1>,
                pto::Layout::ND>(v3 + ((v23 + v56 * v14) + v67), v81, v82);
        wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
        TLOAD(v79, v83);
        set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
        // pto: %43
        v29.SetValidShape(v42, v11);
        v31.SetValidShape(v42, v11);
        wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
        if (v41 == v23) {
            // pto: %wkv_tile_inline15298__tile_t
            Tile<
                TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>
                v84 = Tile<
                    TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512,
                    PadValue::Null, CompactMode::Null>(v9, v11);
            // pto: %wkv_tile_inline15298__tile_t
            uint64_t v85 = (uint64_t)v20;
            TASSIGN(v84, v85);
            // pto: %x_tile_inline15284__tile_Left
            Tile<
                TileType::Left, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
                CompactMode::Null>
                v86 = Tile<
                    TileType::Left, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512,
                    PadValue::Null, CompactMode::Null>(v42, v9);
            // pto: %x_tile_inline15284__tile_Left
            uint64_t v87 = (uint64_t)v23;
            TASSIGN(v86, v87);
            TMOV(v86, v44);
            // pto: %wkv_tile_inline15298__tile_t_Right
            Tile<
                TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>
                v88 = Tile<
                    TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512,
                    PadValue::Null, CompactMode::Null>(v9, v11);
            // pto: %wkv_tile_inline15298__tile_t_Right
            uint64_t v89 = (uint64_t)v23;
            TASSIGN(v88, v89);
            TMOV(v88, v84);
            set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
            // pto: %3
            Tile<
                TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                CompactMode::Null>
                v90 = Tile<
                    TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                    CompactMode::Null>(v42, v11);
            // pto: %3
            uint64_t v91 = (uint64_t)v23;
            TASSIGN(v90, v91);
            wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
            TMATMUL(v90, v86, v88);
            set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
            // pto: %wgate_tile_inline15301__tile_t
            Tile<
                TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>
                v92 = Tile<
                    TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512,
                    PadValue::Null, CompactMode::Null>(v9, v11);
            // pto: %wgate_tile_inline15301__tile_t
            uint64_t v93 = (uint64_t)v19;
            TASSIGN(v92, v93);
            // pto: %wgate_tile_inline15301__tile_t_Right
            Tile<
                TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>
                v94 = Tile<
                    TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512,
                    PadValue::Null, CompactMode::Null>(v9, v11);
            // pto: %wgate_tile_inline15301__tile_t_Right
            uint64_t v95 = (uint64_t)v23;
            TASSIGN(v94, v95);
            wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
            TMOV(v94, v92);
            set_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
            // pto: %4
            Tile<
                TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                CompactMode::Null>
                v96 = Tile<
                    TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                    CompactMode::Null>(v42, v11);
            // pto: %4
            uint64_t v97 = (uint64_t)v22;
            TASSIGN(v96, v97);
            wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
            TMATMUL(v96, v86, v94);
        } else {
            // pto: %5
            Tile<
                TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>
                v98 = Tile<
                    TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512,
                    PadValue::Null, CompactMode::Null>(v9, v11);
            // pto: %5
            uint64_t v99 = (uint64_t)v20;
            TASSIGN(v98, v99);
            // pto: %6
            Tile<
                TileType::Left, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
                CompactMode::Null>
                v100 = Tile<
                    TileType::Left, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512,
                    PadValue::Null, CompactMode::Null>(v42, v9);
            // pto: %6
            uint64_t v101 = (uint64_t)v23;
            TASSIGN(v100, v101);
            TMOV(v100, v44);
            // pto: %7
            Tile<
                TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>
                v102 = Tile<
                    TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512,
                    PadValue::Null, CompactMode::Null>(v9, v11);
            // pto: %7
            uint64_t v103 = (uint64_t)v23;
            TASSIGN(v102, v103);
            TMOV(v102, v98);
            set_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
            // pto: %8
            Tile<
                TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                CompactMode::Null>
                v104 = Tile<
                    TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                    CompactMode::Null>(v12, v11);
            // pto: %8
            uint64_t v105 = (uint64_t)v23;
            TASSIGN(v104, v105);
            wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
            TMATMUL_ACC(v104, v104, v100, v102);
            set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
            // pto: %9
            Tile<
                TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>
                v106 = Tile<
                    TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512,
                    PadValue::Null, CompactMode::Null>(v9, v11);
            // pto: %9
            uint64_t v107 = (uint64_t)v19;
            TASSIGN(v106, v107);
            // pto: %10
            Tile<
                TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>
                v108 = Tile<
                    TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512,
                    PadValue::Null, CompactMode::Null>(v9, v11);
            // pto: %10
            uint64_t v109 = (uint64_t)v23;
            TASSIGN(v108, v109);
            wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
            TMOV(v108, v106);
            set_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
            // pto: %11
            Tile<
                TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                CompactMode::Null>
                v110 = Tile<
                    TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                    CompactMode::Null>(v12, v11);
            // pto: %11
            uint64_t v111 = (uint64_t)v22;
            TASSIGN(v110, v111);
            wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
            TMATMUL_ACC(v110, v110, v100, v108);
        }
        set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
        // pto: %12
        Tile<
            TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
            CompactMode::Null>
            v112 = Tile<
                TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>(v9, v11);
        // pto: %12
        uint64_t v113 = (uint64_t)v18;
        TASSIGN(v112, v113);
        // pto: %13
        Tile<
            TileType::Left, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
            CompactMode::Null>
            v114 = Tile<
                TileType::Left, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null,
                CompactMode::Null>(v42, v9);
        // pto: %13
        uint64_t v115 = (uint64_t)v18;
        TASSIGN(v114, v115);
        wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
        TMOV(v114, v65);
        set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
        // pto: %14
        Tile<
            TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
            CompactMode::Null>
            v116 = Tile<
                TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>(v9, v11);
        // pto: %14
        uint64_t v117 = (uint64_t)v16;
        TASSIGN(v116, v117);
        wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
        TMOV(v116, v112);
        set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID4);
        // pto: %15
        Tile<
            TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
            CompactMode::Null>
            v118 = Tile<
                TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                CompactMode::Null>(v12, v11);
        // pto: %15
        uint64_t v119 = (uint64_t)v23;
        TASSIGN(v118, v119);
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID4);
        TMATMUL_ACC(v118, v118, v114, v116);
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
        // pto: %16
        Tile<
            TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
            CompactMode::Null>
            v120 = Tile<
                TileType::Mat, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>(v9, v11);
        // pto: %16
        uint64_t v121 = (uint64_t)v17;
        TASSIGN(v120, v121);
        // pto: %17
        Tile<
            TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
            CompactMode::Null>
            v122 = Tile<
                TileType::Right, bfloat16_t, 512, 32, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null,
                CompactMode::Null>(v9, v11);
        // pto: %17
        uint64_t v123 = (uint64_t)v16;
        TASSIGN(v122, v123);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
        wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
        TMOV(v122, v120);
        set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID5);
        // pto: %18
        Tile<
            TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
            CompactMode::Null>
            v124 = Tile<
                TileType::Acc, float, 16, 32, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null,
                CompactMode::Null>(v12, v11);
        // pto: %18
        uint64_t v125 = (uint64_t)v22;
        TASSIGN(v124, v125);
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID5);
        TMATMUL_ACC(v124, v124, v114, v122);
    }
    set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
    // pto: %44
    int64_t v126 = v34 < v23 ? v23 : v34;
    // pto: %45
    int64_t v127 = v35 < v23 ? v23 : v35;
    // pto: %kv_proj_pad_inline15316__ssa_v0_pview
    pto::Shape<1, 1, 1, 16, 32> v128 = pto::Shape<1, 1, 1, 16, 32>();
    // pto: %kv_proj_pad_inline15316__ssa_v0_pview
    pto::Stride<4096, 4096, 4096, 256, 1> v129 = pto::Stride<4096, 4096, 4096, 256, 1>();
    // pto: %kv_proj_pad_inline15316__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v130 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(
            v4 + ((v23 + v126 * v8) + v127), v128, v129
        );
    wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
    TSTORE(v130, v36);
    // pto: %score_proj_pad_inline15304__ssa_v0_pview
    pto::Shape<1, 1, 1, 16, 32> v131 = pto::Shape<1, 1, 1, 16, 32>();
    // pto: %score_proj_pad_inline15304__ssa_v0_pview
    pto::Stride<4096, 4096, 4096, 256, 1> v132 = pto::Stride<4096, 4096, 4096, 256, 1>();
    // pto: %score_proj_pad_inline15304__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v133 =
        GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(
            v5 + ((v23 + v126 * v8) + v127), v131, v132
        );
    TSTORE(v133, v38);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
#endif  // __DAV_CUBE__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: x_flat_inline15306__ssa_v0
    __gm__ ChipTensor *x_flat_inline15306__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[0]);
    __gm__ bfloat16_t *x_flat_inline15306__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(x_flat_inline15306__ssa_v0_tensor->buffer.addr) +
        x_flat_inline15306__ssa_v0_tensor->start_offset;

    // Unpack tensor: csa_inner_wkv_last_inline580__ssa_v0
    __gm__ ChipTensor *csa_inner_wkv_last_inline580__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[1]);
    __gm__ bfloat16_t *csa_inner_wkv_last_inline580__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(csa_inner_wkv_last_inline580__ssa_v0_tensor->buffer.addr) +
        csa_inner_wkv_last_inline580__ssa_v0_tensor->start_offset;

    // Unpack tensor: csa_inner_wgate_last_inline511__ssa_v0
    __gm__ ChipTensor *csa_inner_wgate_last_inline511__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[2]);
    __gm__ bfloat16_t *csa_inner_wgate_last_inline511__ssa_v0 =
        reinterpret_cast<__gm__ bfloat16_t *>(csa_inner_wgate_last_inline511__ssa_v0_tensor->buffer.addr) +
        csa_inner_wgate_last_inline511__ssa_v0_tensor->start_offset;

    // Unpack tensor: kv_proj_pad_inline15316__ssa_v0
    __gm__ ChipTensor *kv_proj_pad_inline15316__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[3]);
    __gm__ float *kv_proj_pad_inline15316__ssa_v0 =
        reinterpret_cast<__gm__ float *>(kv_proj_pad_inline15316__ssa_v0_tensor->buffer.addr) +
        kv_proj_pad_inline15316__ssa_v0_tensor->start_offset;

    // Unpack tensor: score_proj_pad_inline15304__ssa_v0
    __gm__ ChipTensor *score_proj_pad_inline15304__ssa_v0_tensor = reinterpret_cast<__gm__ ChipTensor *>(args[4]);
    __gm__ float *score_proj_pad_inline15304__ssa_v0 =
        reinterpret_cast<__gm__ float *>(score_proj_pad_inline15304__ssa_v0_tensor->buffer.addr) +
        score_proj_pad_inline15304__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    kv_score_proj_3(
        x_flat_inline15306__ssa_v0, csa_inner_wkv_last_inline580__ssa_v0, csa_inner_wgate_last_inline511__ssa_v0,
        kv_proj_pad_inline15316__ssa_v0, score_proj_pad_inline15304__ssa_v0, __pypto_spmd_block_idx,
        __pypto_spmd_block_num
    );
}
